"""Tests for the cards and the publication gate (PLAN M6.02-M6.04)."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

import pytest

from maia.evaluation.andbench import Track, TrackResult
from maia.evaluation.matrix import Config, from_results
from maia.publication.cards import (
    DATASET_LICENSE,
    DATASET_REPO,
    GGUF_REPO,
    MODEL_LICENSE,
    MODEL_REPO,
    CardFacts,
    Language,
    NotPublishableError,
    PublicationReport,
    check_cards,
    dataset_card,
    expected_repos,
    missing_limitations,
    missing_sections,
    model_card,
    publish,
    render,
)
from maia.publication.compliance import ComplianceReport
from maia.schemas import Source


def matrix() -> object:
    return from_results(
        {
            Config.BASE: [TrackResult(track=Track.OBERT, score=0.50, items=100)],
            Config.BASE_RAG: [TrackResult(track=Track.OBERT, score=0.70, items=100)],
            Config.TUNED: [TrackResult(track=Track.OBERT, score=0.72, items=100)],
            Config.TUNED_RAG: [TrackResult(track=Track.OBERT, score=0.92, items=100)],
        }
    )


def facts(**overrides: object) -> CardFacts:
    base = {
        "examples": 12_000,
        "corpus_documents": 8_500,
        "sources": (Source.JURIDIC, Source.VIQUIPEDIA),
        "matrix": matrix(),
    }
    return CardFacts(**{**base, **overrides})  # type: ignore[arg-type]


def clean_compliance() -> ComplianceReport:
    return ComplianceReport(examples=12_000, corpus_supplied=True, card_checked=True)


@dataclass
class FakeHub:
    created: list[tuple[str, str, bool]] = field(default_factory=list)
    uploaded: list[tuple[str, str]] = field(default_factory=list)

    def create_repo(self, repo_id: str, *, repo_type: str, private: bool, exist_ok: bool) -> object:
        self.created.append((repo_id, repo_type, private))
        return None

    def upload_folder(
        self, *, repo_id: str, folder_path: str, repo_type: str, commit_message: str
    ) -> object:
        self.uploaded.append((repo_id, commit_message))
        return None


# ─────────────────────────────────────────────────────────────
# Both languages carry the same sections
# ─────────────────────────────────────────────────────────────


@pytest.mark.unit
def test_the_model_card_is_complete_in_both_languages() -> None:
    card = model_card(facts())
    assert missing_sections(card) == []
    assert missing_limitations(card) == []


@pytest.mark.unit
def test_a_card_missing_the_english_limitations_is_caught() -> None:
    """Worse than a monolingual card: it presents a complete document to a reader who
    cannot check."""
    card = model_card(facts())
    for text in LIMITATIONS_EN:
        card = card.replace(text, "")
    problems = missing_limitations(card, language=Language.EN)
    assert len(problems) == 3
    assert missing_limitations(card, language=Language.CA) == []


LIMITATIONS_EN = (
    "Answers were generated by a frontier model",
    "never to imitate an identifiable person's speech",
    "This is not legal advice",
)


@pytest.mark.unit
@pytest.mark.parametrize("language", list(Language))
def test_every_required_section_appears_in_each_language(language: Language) -> None:
    assert missing_sections(model_card(facts()), language=language) == []


@pytest.mark.unit
def test_a_card_missing_a_section_is_caught() -> None:
    stripped = model_card(facts()).replace("### Límits", "")
    assert "ca: limitations" in missing_sections(stripped)


# ─────────────────────────────────────────────────────────────
# The limitations name real constraints
# ─────────────────────────────────────────────────────────────


@pytest.mark.unit
def test_the_synthetic_limitation_says_only_a_sample_was_reviewed() -> None:
    card = model_card(facts())
    assert "A sample was reviewed by hand (DoD-F2); the rest was not." in card
    assert "Una mostra es va revisar a mà" in card


@pytest.mark.unit
def test_the_oral_limitation_states_d7() -> None:
    """Register and lexicon only, never to imitate an identifiable person."""
    card = model_card(facts())
    assert "never to imitate an identifiable person" in card
    assert "mai per imitar la parla d'una persona identificable" in card


@pytest.mark.unit
def test_the_legal_limitation_explains_why_it_is_tempting() -> None:
    """The model is trained on consolidated law, which is what invites the mistake."""
    card = model_card(facts())
    assert "trained on consolidated Andorran law, which is exactly what makes that use" in card
    assert "assessorament jurídic" in card


# ─────────────────────────────────────────────────────────────
# The evaluation table is rendered, not retyped
# ─────────────────────────────────────────────────────────────


@pytest.mark.unit
def test_the_card_embeds_the_f4_matrix() -> None:
    """A hand-copied table is a second source of truth that drifts towards flattery."""
    card = model_card(facts())
    assert "| fine-tune +RAG | 0.920 |" in card
    assert "| contribution |" in card
    assert "both pieces contribute" in card


@pytest.mark.unit
def test_a_card_without_a_matrix_says_so_rather_than_omitting_it() -> None:
    card = model_card(facts(matrix=None))
    assert "has not been measured yet" in card
    assert "encara no s'ha mesurat" in card
    assert missing_sections(card) == []


@pytest.mark.unit
def test_the_card_credits_andbench_rather_than_an_in_house_benchmark() -> None:
    card = model_card(facts())
    assert "not with an in-house benchmark" in card
    assert "no amb un benchmark propi" in card


# ─────────────────────────────────────────────────────────────
# Licences and attributions
# ─────────────────────────────────────────────────────────────


@pytest.mark.unit
def test_the_model_card_states_both_licences() -> None:
    card = model_card(facts())
    assert f"license: {MODEL_LICENSE}" in card
    assert f"Model: **{MODEL_LICENSE}**. Dataset: **{DATASET_LICENSE}**." in card


@pytest.mark.unit
def test_the_dataset_card_credits_every_source() -> None:
    card = dataset_card(facts())
    assert f"license: {DATASET_LICENSE}" in card
    assert "`viquipedia`" in card
    assert "`juridic`" in card
    assert "## Attributions" in card


@pytest.mark.unit
def test_the_dataset_card_carries_the_limitations_too() -> None:
    """A dataset card without them describes data that does not exist either."""
    assert missing_limitations(dataset_card(facts()), language=Language.EN) == []


@pytest.mark.unit
def test_the_dataset_card_states_the_example_count() -> None:
    assert "12,000 Catalan instruction examples" in dataset_card(facts())


# ─────────────────────────────────────────────────────────────
# Publication is gated on M6.01
# ─────────────────────────────────────────────────────────────


@pytest.mark.unit
def test_publication_requires_the_legal_gate_to_have_passed(tmp_path: Path) -> None:
    """A check that runs after the upload is not a gate."""
    blocked = ComplianceReport(examples=1, corpus_supplied=False, card_checked=False)
    assert not blocked.passed
    with pytest.raises(NotPublishableError, match=r"the M6\.01 legal gate has not passed"):
        publish(facts(), blocked, FakeHub(), {MODEL_REPO: tmp_path / "model"})


@pytest.mark.unit
def test_nothing_is_uploaded_when_the_gate_blocks(tmp_path: Path) -> None:
    hub = FakeHub()
    with pytest.raises(NotPublishableError):
        publish(facts(), ComplianceReport(), hub, {MODEL_REPO: tmp_path / "model"})
    assert hub.uploaded == []
    assert hub.created == []


@pytest.mark.unit
def test_a_clean_gate_publishes_all_three_repos(tmp_path: Path) -> None:
    hub = FakeHub()
    staging = {repo: tmp_path / repo.split("/")[-1] for repo in expected_repos()}
    report = publish(facts(), clean_compliance(), hub, staging)
    assert report.passed
    assert sorted(report.repos) == sorted(expected_repos())
    assert "the PO validates DoD-F6" in render(report)


@pytest.mark.unit
def test_the_dataset_repo_is_created_as_a_dataset(tmp_path: Path) -> None:
    hub = FakeHub()
    staging = {repo: tmp_path / repo.split("/")[-1] for repo in expected_repos()}
    publish(facts(), clean_compliance(), hub, staging)
    kinds = {repo: kind for repo, kind, _ in hub.created}
    assert kinds[DATASET_REPO] == "dataset"
    assert kinds[MODEL_REPO] == "model"
    assert kinds[GGUF_REPO] == "model"


@pytest.mark.unit
def test_each_repo_gets_the_right_card(tmp_path: Path) -> None:
    staging = {repo: tmp_path / repo.split("/")[-1] for repo in expected_repos()}
    publish(facts(), clean_compliance(), FakeHub(), staging)
    model_readme = (staging[MODEL_REPO] / "README.md").read_text(encoding="utf-8")
    dataset_readme = (staging[DATASET_REPO] / "README.md").read_text(encoding="utf-8")
    assert "MAIA — Model Andorrà" in model_readme
    assert "andorra-instruct-ca" in dataset_readme
    assert "## Attributions" in dataset_readme


@pytest.mark.unit
def test_publication_is_private_by_default(tmp_path: Path) -> None:
    hub = FakeHub()
    publish(facts(), clean_compliance(), hub, {MODEL_REPO: tmp_path / "m"})
    assert hub.created[0][2] is True


@pytest.mark.unit
def test_publishing_publicly_is_a_choice(tmp_path: Path) -> None:
    hub = FakeHub()
    publish(facts(), clean_compliance(), hub, {MODEL_REPO: tmp_path / "m"}, private=False)
    assert hub.created[0][2] is False


@pytest.mark.unit
def test_an_incomplete_card_blocks_the_upload(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A card is the only part of this project most people will read."""
    monkeypatch.setattr("maia.publication.cards.model_card", lambda facts_: "# MAIA\n")
    hub = FakeHub()
    with pytest.raises(NotPublishableError, match="the cards are incomplete"):
        publish(facts(), clean_compliance(), hub, {MODEL_REPO: tmp_path / "m"})
    assert hub.uploaded == []


@pytest.mark.unit
def test_the_commit_message_records_what_went_out(tmp_path: Path) -> None:
    hub = FakeHub()
    publish(facts(candidate="cand2"), clean_compliance(), hub, {MODEL_REPO: tmp_path / "m"})
    assert hub.uploaded[0][1] == "MAIA cand2: 12,000 examples"


# ─────────────────────────────────────────────────────────────
# Card checking as one list
# ─────────────────────────────────────────────────────────────


@pytest.mark.unit
def test_a_complete_pair_of_cards_has_no_problems() -> None:
    assert check_cards(model_card(facts()), dataset_card(facts())) == []


@pytest.mark.unit
def test_a_dataset_card_without_its_licence_is_a_problem() -> None:
    # The licence appears in the front matter *and* in the attribution section, so removing one
    # does not remove the statement — which is the point. Both have to go for this to fail.
    stripped = dataset_card(facts()).replace(DATASET_LICENSE, "").replace("CC-BY-SA-4.0", "")
    problems = check_cards(model_card(facts()), stripped)
    assert any("dataset licence" in problem for problem in problems)


@pytest.mark.unit
def test_an_empty_report_does_not_pass() -> None:
    assert not PublicationReport().passed
    assert "✗ not published" in render(PublicationReport())


@pytest.mark.unit
def test_the_repo_names_are_the_plans() -> None:
    assert expected_repos() == (
        "ericrisco/maia-12b-it",
        "ericrisco/maia-12b-it-GGUF",
        "ericrisco/andorra-instruct-ca",
    )


@pytest.mark.unit
def test_a_blocked_report_says_what_blocked_it() -> None:
    blocked = PublicationReport(blocked_by="the M6.01 legal gate has not passed")
    rendered = render(blocked)
    assert "✗ not published" in rendered
    assert "blocked: the M6.01 legal gate has not passed" in rendered
    assert "PO validates" not in rendered


@pytest.mark.unit
def test_the_committed_cards_are_complete() -> None:
    """`docs/*-card.md` are the drafts a human edits before release; they must start complete."""
    docs = Path(__file__).resolve().parents[1] / "docs"
    model = (docs / "model-card.md").read_text(encoding="utf-8")
    dataset = (docs / "dataset-card.md").read_text(encoding="utf-8")
    assert check_cards(model, dataset) == []
