graph TD
  spk-007["Angelina Mas"] ---|2 formes escasses| spk-053["Roser Bastida"]
  spk-014["Daniel Armengol"] ---|2 formes escasses| spk-024["Jaume Bartumeu Cassany"]
  spk-014["Daniel Armengol"] ---|2 formes escasses| spk-026["Jordi Farràs Forné"]
  spk-015["Enric Casadevall Medrano"] ---|2 formes escasses| spk-024["Jaume Bartumeu Cassany"]
  spk-015["Enric Casadevall Medrano"] ---|2 formes escasses| spk-037["Maria Reig Moles"]
  spk-016["Enric Dolsa Font"] ---|2 formes escasses| spk-024["Jaume Bartumeu Cassany"]
  spk-022["Guillem Areny Argelich"] ---|2 formes escasses| spk-024["Jaume Bartumeu Cassany"]
  spk-022["Guillem Areny Argelich"] ---|2 formes escasses| spk-036["Ludmilla Lacueva"]
  spk-022["Guillem Areny Argelich"] ---|2 formes escasses| spk-044["Olga Adellach Coma"]
  spk-022["Guillem Areny Argelich"] ---|2 formes escasses| spk-048["Ramon Canut Bové"]
  spk-024["Jaume Bartumeu Cassany"] ---|2 formes escasses| spk-026["Jordi Farràs Forné"]
  spk-024["Jaume Bartumeu Cassany"] ---|2 formes escasses| spk-037["Maria Reig Moles"]
  spk-024["Jaume Bartumeu Cassany"] ---|2 formes escasses| spk-048["Ramon Canut Bové"]
