graph LR
  pa-004 ---|2 formes fortes| pa-009
  pa-004 ---|2 formes fortes| pa-036
  pa-007 ---|2 formes fortes| pa-014
  pa-007 ---|2 formes fortes| pa-045
  pa-009 ---|2 formes fortes| pa-016
  pa-009 ---|3 formes fortes| pa-036
  pa-009 ---|2 formes fortes| pa-045
  pa-009 ---|2 formes fortes| pa-056
  pa-009 ---|2 formes fortes| pa-065
  pa-010 ---|2 formes fortes| pa-022
  pa-010 ---|2 formes fortes| pa-056
  pa-014 ---|2 formes fortes| pa-018
  pa-014 ---|2 formes fortes| pa-021
  pa-014 ---|2 formes fortes| pa-025
  pa-014 ---|2 formes fortes| pa-027
  pa-014 ---|2 formes fortes| pa-030
  pa-014 ---|2 formes fortes| pa-040
  pa-014 ---|2 formes fortes| pa-056
  pa-014 ---|2 formes fortes| pa-061
  pa-014 ---|2 formes fortes| pa-062
  pa-016 ---|2 formes fortes| pa-036
  pa-016 ---|3 formes fortes| pa-065
  pa-018 ---|2 formes fortes| pa-021
  pa-018 ---|2 formes fortes| pa-025
  pa-018 ---|2 formes fortes| pa-062
  pa-019 ---|2 formes fortes| pa-036
  pa-019 ---|2 formes fortes| pa-038
  pa-019 ---|2 formes fortes| pa-039
  pa-019 ---|2 formes fortes| pa-048
  pa-019 ---|2 formes fortes| pa-061
  pa-021 ---|2 formes fortes| pa-025
  pa-021 ---|2 formes fortes| pa-062
  pa-022 ---|2 formes fortes| pa-056
  pa-025 ---|2 formes fortes| pa-062
  pa-026 ---|2 formes fortes| pa-055
  pa-027 ---|2 formes fortes| pa-030
  pa-027 ---|2 formes fortes| pa-040
  pa-027 ---|2 formes fortes| pa-056
  pa-027 ---|2 formes fortes| pa-061
  pa-030 ---|2 formes fortes| pa-038
  pa-030 ---|2 formes fortes| pa-040
  pa-030 ---|2 formes fortes| pa-041
  pa-030 ---|3 formes fortes| pa-056
  pa-030 ---|2 formes fortes| pa-061
  pa-031 ---|2 formes fortes| pa-040
  pa-033 ---|2 formes fortes| pa-038
  pa-036 ---|2 formes fortes| pa-045
  pa-036 ---|2 formes fortes| pa-056
  pa-036 ---|2 formes fortes| pa-061
  pa-036 ---|2 formes fortes| pa-065
  pa-038 ---|2 formes fortes| pa-039
  pa-038 ---|2 formes fortes| pa-041
  pa-038 ---|2 formes fortes| pa-056
  pa-040 ---|2 formes fortes| pa-056
  pa-040 ---|2 formes fortes| pa-061
  pa-041 ---|2 formes fortes| pa-056
  pa-045 ---|2 formes fortes| pa-056
  pa-048 ---|2 formes fortes| pa-061
  pa-056 ---|2 formes fortes| pa-061
