graph TD
  spk-007[Angelina Mas] ---|10 formes| spk-016[Enric Dolsa Font]
  spk-016[Enric Dolsa Font] ---|10 formes| spk-044[Olga Adellach Coma]
  spk-044[Olga Adellach Coma] ---|10 formes| spk-054[Roser Jordana]
  spk-007[Angelina Mas] ---|9 formes| spk-044[Olga Adellach Coma]
  spk-008[Antoni Armengol Vila] ---|9 formes| spk-044[Olga Adellach Coma]
  spk-010[Antoni Morell] ---|9 formes| spk-044[Olga Adellach Coma]
  spk-016[Enric Dolsa Font] ---|9 formes| spk-043[Nadia Aleix Tugas]
  spk-018[Eudald Guillamet] ---|9 formes| spk-044[Olga Adellach Coma]
  spk-026[Jordi Farràs Forné] ---|9 formes| spk-044[Olga Adellach Coma]
  spk-037[Maria Reig Moles] ---|9 formes| spk-044[Olga Adellach Coma]
  spk-037[Maria Reig Moles] ---|9 formes| spk-054[Roser Jordana]
  spk-005[Alfred Llahí] ---|8 formes| spk-044[Olga Adellach Coma]
  spk-007[Angelina Mas] ---|8 formes| spk-024[Jaume Bartumeu Cassany]
  spk-007[Angelina Mas] ---|8 formes| spk-037[Maria Reig Moles]
  spk-007[Angelina Mas] ---|8 formes| spk-038[Mercè Segura]
  spk-007[Angelina Mas] ---|8 formes| spk-045[Patrick Pérez]
  spk-007[Angelina Mas] ---|8 formes| spk-054[Roser Jordana]
  spk-007[Angelina Mas] ---|8 formes| spk-057[Teo Armengol]
  spk-008[Antoni Armengol Vila] ---|8 formes| spk-016[Enric Dolsa Font]
  spk-010[Antoni Morell] ---|8 formes| spk-054[Roser Jordana]
  spk-016[Enric Dolsa Font] ---|8 formes| spk-031[Josep Areny Fité]
  spk-016[Enric Dolsa Font] ---|8 formes| spk-037[Maria Reig Moles]
  spk-016[Enric Dolsa Font] ---|8 formes| spk-038[Mercè Segura]
  spk-016[Enric Dolsa Font] ---|8 formes| spk-040[Miquel Armengol Pons]
  spk-016[Enric Dolsa Font] ---|8 formes| spk-042[Mossèn Ramon de Canillo]
  spk-016[Enric Dolsa Font] ---|8 formes| spk-054[Roser Jordana]
  spk-018[Eudald Guillamet] ---|8 formes| spk-054[Roser Jordana]
  spk-028[Jordi Mas Torres] ---|8 formes| spk-044[Olga Adellach Coma]
  spk-037[Maria Reig Moles] ---|8 formes| spk-041[Miquel Naudi Casal]
  spk-037[Maria Reig Moles] ---|8 formes| spk-042[Mossèn Ramon de Canillo]
  spk-038[Mercè Segura] ---|8 formes| spk-053[Roser Bastida]
  spk-040[Miquel Armengol Pons] ---|8 formes| spk-044[Olga Adellach Coma]
  spk-042[Mossèn Ramon de Canillo] ---|8 formes| spk-044[Olga Adellach Coma]
  spk-043[Nadia Aleix Tugas] ---|8 formes| spk-044[Olga Adellach Coma]
  spk-044[Olga Adellach Coma] ---|8 formes| spk-045[Patrick Pérez]
  spk-044[Olga Adellach Coma] ---|8 formes| spk-053[Roser Bastida]
  spk-044[Olga Adellach Coma] ---|8 formes| spk-057[Teo Armengol]
  spk-005[Alfred Llahí] ---|7 formes| spk-007[Angelina Mas]
  spk-005[Alfred Llahí] ---|7 formes| spk-016[Enric Dolsa Font]
  spk-005[Alfred Llahí] ---|7 formes| spk-018[Eudald Guillamet]
  spk-007[Angelina Mas] ---|7 formes| spk-018[Eudald Guillamet]
  spk-007[Angelina Mas] ---|7 formes| spk-026[Jordi Farràs Forné]
  spk-007[Angelina Mas] ---|7 formes| spk-040[Miquel Armengol Pons]
  spk-007[Angelina Mas] ---|7 formes| spk-041[Miquel Naudi Casal]
  spk-007[Angelina Mas] ---|7 formes| spk-042[Mossèn Ramon de Canillo]
  spk-007[Angelina Mas] ---|7 formes| spk-046[Pere Altimir Pintat]
  spk-008[Antoni Armengol Vila] ---|7 formes| spk-010[Antoni Morell]
  spk-008[Antoni Armengol Vila] ---|7 formes| spk-031[Josep Areny Fité]
  spk-008[Antoni Armengol Vila] ---|7 formes| spk-037[Maria Reig Moles]
  spk-008[Antoni Armengol Vila] ---|7 formes| spk-043[Nadia Aleix Tugas]
  spk-008[Antoni Armengol Vila] ---|7 formes| spk-054[Roser Jordana]
  spk-009[Antoni Jordi Areny] ---|7 formes| spk-044[Olga Adellach Coma]
  spk-010[Antoni Morell] ---|7 formes| spk-016[Enric Dolsa Font]
  spk-010[Antoni Morell] ---|7 formes| spk-037[Maria Reig Moles]
  spk-010[Antoni Morell] ---|7 formes| spk-045[Patrick Pérez]
  spk-011[Carles Sasplugas] ---|7 formes| spk-026[Jordi Farràs Forné]
  spk-011[Carles Sasplugas] ---|7 formes| spk-044[Olga Adellach Coma]
  spk-011[Carles Sasplugas] ---|7 formes| spk-046[Pere Altimir Pintat]
  spk-011[Carles Sasplugas] ---|7 formes| spk-053[Roser Bastida]
  spk-014[Daniel Armengol] ---|7 formes| spk-044[Olga Adellach Coma]
  spk-016[Enric Dolsa Font] ---|7 formes| spk-018[Eudald Guillamet]
  spk-016[Enric Dolsa Font] ---|7 formes| spk-024[Jaume Bartumeu Cassany]
  spk-016[Enric Dolsa Font] ---|7 formes| spk-033[Josep Garrallà Rossell]
  spk-016[Enric Dolsa Font] ---|7 formes| spk-041[Miquel Naudi Casal]
  spk-016[Enric Dolsa Font] ---|7 formes| spk-045[Patrick Pérez]
  spk-016[Enric Dolsa Font] ---|7 formes| spk-053[Roser Bastida]
  spk-016[Enric Dolsa Font] ---|7 formes| spk-057[Teo Armengol]
  spk-017[Esther Jover] ---|7 formes| spk-044[Olga Adellach Coma]
  spk-018[Eudald Guillamet] ---|7 formes| spk-026[Jordi Farràs Forné]
  spk-018[Eudald Guillamet] ---|7 formes| spk-028[Jordi Mas Torres]
  spk-018[Eudald Guillamet] ---|7 formes| spk-037[Maria Reig Moles]
  spk-024[Jaume Bartumeu Cassany] ---|7 formes| spk-026[Jordi Farràs Forné]
  spk-024[Jaume Bartumeu Cassany] ---|7 formes| spk-040[Miquel Armengol Pons]
  spk-024[Jaume Bartumeu Cassany] ---|7 formes| spk-044[Olga Adellach Coma]
  spk-026[Jordi Farràs Forné] ---|7 formes| spk-037[Maria Reig Moles]
  spk-026[Jordi Farràs Forné] ---|7 formes| spk-046[Pere Altimir Pintat]
  spk-026[Jordi Farràs Forné] ---|7 formes| spk-053[Roser Bastida]
  spk-026[Jordi Farràs Forné] ---|7 formes| spk-054[Roser Jordana]
  spk-028[Jordi Mas Torres] ---|7 formes| spk-054[Roser Jordana]
  spk-031[Josep Areny Fité] ---|7 formes| spk-044[Olga Adellach Coma]
  spk-037[Maria Reig Moles] ---|7 formes| spk-043[Nadia Aleix Tugas]
  spk-037[Maria Reig Moles] ---|7 formes| spk-045[Patrick Pérez]
  spk-037[Maria Reig Moles] ---|7 formes| spk-046[Pere Altimir Pintat]
  spk-038[Mercè Segura] ---|7 formes| spk-044[Olga Adellach Coma]
  spk-038[Mercè Segura] ---|7 formes| spk-057[Teo Armengol]
  spk-040[Miquel Armengol Pons] ---|7 formes| spk-057[Teo Armengol]
  spk-041[Miquel Naudi Casal] ---|7 formes| spk-044[Olga Adellach Coma]
  spk-041[Miquel Naudi Casal] ---|7 formes| spk-054[Roser Jordana]
  spk-042[Mossèn Ramon de Canillo] ---|7 formes| spk-053[Roser Bastida]
  spk-042[Mossèn Ramon de Canillo] ---|7 formes| spk-054[Roser Jordana]
  spk-043[Nadia Aleix Tugas] ---|7 formes| spk-053[Roser Bastida]
  spk-044[Olga Adellach Coma] ---|7 formes| spk-046[Pere Altimir Pintat]
  spk-044[Olga Adellach Coma] ---|7 formes| spk-048[Ramon Canut Bové]
  spk-044[Olga Adellach Coma] ---|7 formes| spk-059[Xavier Planas]
  spk-045[Patrick Pérez] ---|7 formes| spk-054[Roser Jordana]
  spk-046[Pere Altimir Pintat] ---|7 formes| spk-053[Roser Bastida]
  spk-054[Roser Jordana] ---|7 formes| spk-057[Teo Armengol]
  spk-001[Alan Ward] ---|6 formes| spk-007[Angelina Mas]
  spk-001[Alan Ward] ---|6 formes| spk-024[Jaume Bartumeu Cassany]
  spk-001[Alan Ward] ---|6 formes| spk-042[Mossèn Ramon de Canillo]
  spk-001[Alan Ward] ---|6 formes| spk-044[Olga Adellach Coma]
  spk-003[Albert Roig] ---|6 formes| spk-044[Olga Adellach Coma]
  spk-005[Alfred Llahí] ---|6 formes| spk-009[Antoni Jordi Areny]
  spk-005[Alfred Llahí] ---|6 formes| spk-017[Esther Jover]
  spk-005[Alfred Llahí] ---|6 formes| spk-026[Jordi Farràs Forné]
  spk-005[Alfred Llahí] ---|6 formes| spk-028[Jordi Mas Torres]
  spk-005[Alfred Llahí] ---|6 formes| spk-043[Nadia Aleix Tugas]
  spk-005[Alfred Llahí] ---|6 formes| spk-054[Roser Jordana]
  spk-006[Andreu Gaspà Picart] ---|6 formes| spk-007[Angelina Mas]
  spk-006[Andreu Gaspà Picart] ---|6 formes| spk-016[Enric Dolsa Font]
  spk-006[Andreu Gaspà Picart] ---|6 formes| spk-037[Maria Reig Moles]
  spk-006[Andreu Gaspà Picart] ---|6 formes| spk-041[Miquel Naudi Casal]
  spk-006[Andreu Gaspà Picart] ---|6 formes| spk-042[Mossèn Ramon de Canillo]
  spk-007[Angelina Mas] ---|6 formes| spk-008[Antoni Armengol Vila]
  spk-007[Angelina Mas] ---|6 formes| spk-009[Antoni Jordi Areny]
  spk-007[Angelina Mas] ---|6 formes| spk-010[Antoni Morell]
  spk-007[Angelina Mas] ---|6 formes| spk-011[Carles Sasplugas]
  spk-007[Angelina Mas] ---|6 formes| spk-014[Daniel Armengol]
  spk-007[Angelina Mas] ---|6 formes| spk-028[Jordi Mas Torres]
  spk-007[Angelina Mas] ---|6 formes| spk-031[Josep Areny Fité]
  spk-007[Angelina Mas] ---|6 formes| spk-043[Nadia Aleix Tugas]
  spk-007[Angelina Mas] ---|6 formes| spk-048[Ramon Canut Bové]
  spk-007[Angelina Mas] ---|6 formes| spk-053[Roser Bastida]
  spk-008[Antoni Armengol Vila] ---|6 formes| spk-011[Carles Sasplugas]
  spk-008[Antoni Armengol Vila] ---|6 formes| spk-026[Jordi Farràs Forné]
  spk-008[Antoni Armengol Vila] ---|6 formes| spk-041[Miquel Naudi Casal]
  spk-008[Antoni Armengol Vila] ---|6 formes| spk-042[Mossèn Ramon de Canillo]
  spk-008[Antoni Armengol Vila] ---|6 formes| spk-045[Patrick Pérez]
  spk-008[Antoni Armengol Vila] ---|6 formes| spk-053[Roser Bastida]
  spk-008[Antoni Armengol Vila] ---|6 formes| spk-059[Xavier Planas]
  spk-009[Antoni Jordi Areny] ---|6 formes| spk-016[Enric Dolsa Font]
  spk-009[Antoni Jordi Areny] ---|6 formes| spk-043[Nadia Aleix Tugas]
  spk-009[Antoni Jordi Areny] ---|6 formes| spk-053[Roser Bastida]
  spk-010[Antoni Morell] ---|6 formes| spk-018[Eudald Guillamet]
  spk-010[Antoni Morell] ---|6 formes| spk-042[Mossèn Ramon de Canillo]
  spk-011[Carles Sasplugas] ---|6 formes| spk-037[Maria Reig Moles]
  spk-011[Carles Sasplugas] ---|6 formes| spk-045[Patrick Pérez]
  spk-014[Daniel Armengol] ---|6 formes| spk-016[Enric Dolsa Font]
  spk-014[Daniel Armengol] ---|6 formes| spk-040[Miquel Armengol Pons]
  spk-014[Daniel Armengol] ---|6 formes| spk-042[Mossèn Ramon de Canillo]
  spk-014[Daniel Armengol] ---|6 formes| spk-054[Roser Jordana]
  spk-014[Daniel Armengol] ---|6 formes| spk-057[Teo Armengol]
  spk-015[Enric Casadevall Medrano] ---|6 formes| spk-024[Jaume Bartumeu Cassany]
  spk-015[Enric Casadevall Medrano] ---|6 formes| spk-044[Olga Adellach Coma]
  spk-015[Enric Casadevall Medrano] ---|6 formes| spk-053[Roser Bastida]
  spk-016[Enric Dolsa Font] ---|6 formes| spk-026[Jordi Farràs Forné]
  spk-016[Enric Dolsa Font] ---|6 formes| spk-028[Jordi Mas Torres]
  spk-016[Enric Dolsa Font] ---|6 formes| spk-046[Pere Altimir Pintat]
  spk-016[Enric Dolsa Font] ---|6 formes| spk-059[Xavier Planas]
  spk-018[Eudald Guillamet] ---|6 formes| spk-042[Mossèn Ramon de Canillo]
  spk-018[Eudald Guillamet] ---|6 formes| spk-043[Nadia Aleix Tugas]
  spk-018[Eudald Guillamet] ---|6 formes| spk-045[Patrick Pérez]
  spk-018[Eudald Guillamet] ---|6 formes| spk-046[Pere Altimir Pintat]
  spk-018[Eudald Guillamet] ---|6 formes| spk-048[Ramon Canut Bové]
  spk-018[Eudald Guillamet] ---|6 formes| spk-050[Robert Lizarte]
  spk-018[Eudald Guillamet] ---|6 formes| spk-057[Teo Armengol]
  spk-024[Jaume Bartumeu Cassany] ---|6 formes| spk-033[Josep Garrallà Rossell]
  spk-024[Jaume Bartumeu Cassany] ---|6 formes| spk-057[Teo Armengol]
  spk-026[Jordi Farràs Forné] ---|6 formes| spk-028[Jordi Mas Torres]
  spk-026[Jordi Farràs Forné] ---|6 formes| spk-035[Ladislau Baró Solà]
  spk-026[Jordi Farràs Forné] ---|6 formes| spk-038[Mercè Segura]
  spk-026[Jordi Farràs Forné] ---|6 formes| spk-040[Miquel Armengol Pons]
  spk-026[Jordi Farràs Forné] ---|6 formes| spk-045[Patrick Pérez]
  spk-026[Jordi Farràs Forné] ---|6 formes| spk-048[Ramon Canut Bové]
  spk-026[Jordi Farràs Forné] ---|6 formes| spk-057[Teo Armengol]
  spk-028[Jordi Mas Torres] ---|6 formes| spk-037[Maria Reig Moles]
  spk-028[Jordi Mas Torres] ---|6 formes| spk-038[Mercè Segura]
  spk-028[Jordi Mas Torres] ---|6 formes| spk-043[Nadia Aleix Tugas]
  spk-028[Jordi Mas Torres] ---|6 formes| spk-048[Ramon Canut Bové]
  spk-028[Jordi Mas Torres] ---|6 formes| spk-057[Teo Armengol]
  spk-031[Josep Areny Fité] ---|6 formes| spk-038[Mercè Segura]
  spk-031[Josep Areny Fité] ---|6 formes| spk-040[Miquel Armengol Pons]
  spk-031[Josep Areny Fité] ---|6 formes| spk-043[Nadia Aleix Tugas]
  spk-033[Josep Garrallà Rossell] ---|6 formes| spk-044[Olga Adellach Coma]
  spk-035[Ladislau Baró Solà] ---|6 formes| spk-044[Olga Adellach Coma]
  spk-035[Ladislau Baró Solà] ---|6 formes| spk-053[Roser Bastida]
  spk-037[Maria Reig Moles] ---|6 formes| spk-038[Mercè Segura]
  spk-037[Maria Reig Moles] ---|6 formes| spk-040[Miquel Armengol Pons]
  spk-037[Maria Reig Moles] ---|6 formes| spk-048[Ramon Canut Bové]
  spk-037[Maria Reig Moles] ---|6 formes| spk-053[Roser Bastida]
  spk-037[Maria Reig Moles] ---|6 formes| spk-057[Teo Armengol]
  spk-038[Mercè Segura] ---|6 formes| spk-040[Miquel Armengol Pons]
  spk-038[Mercè Segura] ---|6 formes| spk-041[Miquel Naudi Casal]
  spk-038[Mercè Segura] ---|6 formes| spk-043[Nadia Aleix Tugas]
  spk-038[Mercè Segura] ---|6 formes| spk-045[Patrick Pérez]
  spk-038[Mercè Segura] ---|6 formes| spk-046[Pere Altimir Pintat]
  spk-038[Mercè Segura] ---|6 formes| spk-054[Roser Jordana]
  spk-040[Miquel Armengol Pons] ---|6 formes| spk-048[Ramon Canut Bové]
  spk-040[Miquel Armengol Pons] ---|6 formes| spk-054[Roser Jordana]
  spk-041[Miquel Naudi Casal] ---|6 formes| spk-042[Mossèn Ramon de Canillo]
  spk-041[Miquel Naudi Casal] ---|6 formes| spk-043[Nadia Aleix Tugas]
  spk-041[Miquel Naudi Casal] ---|6 formes| spk-046[Pere Altimir Pintat]
  spk-042[Mossèn Ramon de Canillo] ---|6 formes| spk-043[Nadia Aleix Tugas]
  spk-042[Mossèn Ramon de Canillo] ---|6 formes| spk-046[Pere Altimir Pintat]
  spk-043[Nadia Aleix Tugas] ---|6 formes| spk-046[Pere Altimir Pintat]
  spk-043[Nadia Aleix Tugas] ---|6 formes| spk-054[Roser Jordana]
  spk-044[Olga Adellach Coma] ---|6 formes| spk-050[Robert Lizarte]
  spk-045[Patrick Pérez] ---|6 formes| spk-046[Pere Altimir Pintat]
  spk-045[Patrick Pérez] ---|6 formes| spk-048[Ramon Canut Bové]
  spk-045[Patrick Pérez] ---|6 formes| spk-057[Teo Armengol]
  spk-046[Pere Altimir Pintat] ---|6 formes| spk-054[Roser Jordana]
  spk-048[Ramon Canut Bové] ---|6 formes| spk-054[Roser Jordana]
  spk-048[Ramon Canut Bové] ---|6 formes| spk-057[Teo Armengol]
  spk-001[Alan Ward] ---|5 formes| spk-003[Albert Roig]
  spk-001[Alan Ward] ---|5 formes| spk-005[Alfred Llahí]
  spk-001[Alan Ward] ---|5 formes| spk-006[Andreu Gaspà Picart]
  spk-001[Alan Ward] ---|5 formes| spk-009[Antoni Jordi Areny]
  spk-001[Alan Ward] ---|5 formes| spk-016[Enric Dolsa Font]
  spk-001[Alan Ward] ---|5 formes| spk-018[Eudald Guillamet]
  spk-001[Alan Ward] ---|5 formes| spk-022[Guillem Areny Argelich]
  spk-001[Alan Ward] ---|5 formes| spk-033[Josep Garrallà Rossell]
  spk-001[Alan Ward] ---|5 formes| spk-037[Maria Reig Moles]
  spk-001[Alan Ward] ---|5 formes| spk-050[Robert Lizarte]
  spk-001[Alan Ward] ---|5 formes| spk-054[Roser Jordana]
  spk-002[Albert Gelabert Grau] ---|5 formes| spk-011[Carles Sasplugas]
  spk-002[Albert Gelabert Grau] ---|5 formes| spk-026[Jordi Farràs Forné]
  spk-002[Albert Gelabert Grau] ---|5 formes| spk-044[Olga Adellach Coma]
  spk-003[Albert Roig] ---|5 formes| spk-005[Alfred Llahí]
  spk-003[Albert Roig] ---|5 formes| spk-007[Angelina Mas]
  spk-003[Albert Roig] ---|5 formes| spk-009[Antoni Jordi Areny]
  spk-003[Albert Roig] ---|5 formes| spk-014[Daniel Armengol]
  spk-003[Albert Roig] ---|5 formes| spk-016[Enric Dolsa Font]
  spk-003[Albert Roig] ---|5 formes| spk-017[Esther Jover]
  spk-003[Albert Roig] ---|5 formes| spk-024[Jaume Bartumeu Cassany]
  spk-003[Albert Roig] ---|5 formes| spk-026[Jordi Farràs Forné]
  spk-003[Albert Roig] ---|5 formes| spk-033[Josep Garrallà Rossell]
  spk-003[Albert Roig] ---|5 formes| spk-042[Mossèn Ramon de Canillo]
  spk-003[Albert Roig] ---|5 formes| spk-053[Roser Bastida]
  spk-005[Alfred Llahí] ---|5 formes| spk-008[Antoni Armengol Vila]
  spk-005[Alfred Llahí] ---|5 formes| spk-010[Antoni Morell]
  spk-005[Alfred Llahí] ---|5 formes| spk-014[Daniel Armengol]
  spk-005[Alfred Llahí] ---|5 formes| spk-015[Enric Casadevall Medrano]
  spk-005[Alfred Llahí] ---|5 formes| spk-022[Guillem Areny Argelich]
  spk-005[Alfred Llahí] ---|5 formes| spk-024[Jaume Bartumeu Cassany]
  spk-005[Alfred Llahí] ---|5 formes| spk-030[Josep Areny]
  spk-005[Alfred Llahí] ---|5 formes| spk-031[Josep Areny Fité]
  spk-005[Alfred Llahí] ---|5 formes| spk-037[Maria Reig Moles]
  spk-005[Alfred Llahí] ---|5 formes| spk-038[Mercè Segura]
  spk-005[Alfred Llahí] ---|5 formes| spk-040[Miquel Armengol Pons]
  spk-005[Alfred Llahí] ---|5 formes| spk-041[Miquel Naudi Casal]
  spk-005[Alfred Llahí] ---|5 formes| spk-042[Mossèn Ramon de Canillo]
  spk-005[Alfred Llahí] ---|5 formes| spk-046[Pere Altimir Pintat]
  spk-005[Alfred Llahí] ---|5 formes| spk-050[Robert Lizarte]
  spk-005[Alfred Llahí] ---|5 formes| spk-053[Roser Bastida]
  spk-005[Alfred Llahí] ---|5 formes| spk-057[Teo Armengol]
  spk-005[Alfred Llahí] ---|5 formes| spk-059[Xavier Planas]
  spk-006[Andreu Gaspà Picart] ---|5 formes| spk-028[Jordi Mas Torres]
  spk-006[Andreu Gaspà Picart] ---|5 formes| spk-038[Mercè Segura]
  spk-006[Andreu Gaspà Picart] ---|5 formes| spk-043[Nadia Aleix Tugas]
  spk-006[Andreu Gaspà Picart] ---|5 formes| spk-044[Olga Adellach Coma]
  spk-006[Andreu Gaspà Picart] ---|5 formes| spk-054[Roser Jordana]
  spk-007[Angelina Mas] ---|5 formes| spk-015[Enric Casadevall Medrano]
  spk-007[Angelina Mas] ---|5 formes| spk-027[Jordi Marquet]
  spk-007[Angelina Mas] ---|5 formes| spk-033[Josep Garrallà Rossell]
  spk-007[Angelina Mas] ---|5 formes| spk-039[Miquel Aleix Areny]
  spk-007[Angelina Mas] ---|5 formes| spk-050[Robert Lizarte]
  spk-008[Antoni Armengol Vila] ---|5 formes| spk-009[Antoni Jordi Areny]
  spk-008[Antoni Armengol Vila] ---|5 formes| spk-017[Esther Jover]
  spk-008[Antoni Armengol Vila] ---|5 formes| spk-018[Eudald Guillamet]
  spk-008[Antoni Armengol Vila] ---|5 formes| spk-028[Jordi Mas Torres]
  spk-008[Antoni Armengol Vila] ---|5 formes| spk-033[Josep Garrallà Rossell]
  spk-008[Antoni Armengol Vila] ---|5 formes| spk-038[Mercè Segura]
  spk-008[Antoni Armengol Vila] ---|5 formes| spk-039[Miquel Aleix Areny]
  spk-008[Antoni Armengol Vila] ---|5 formes| spk-040[Miquel Armengol Pons]
  spk-008[Antoni Armengol Vila] ---|5 formes| spk-046[Pere Altimir Pintat]
  spk-009[Antoni Jordi Areny] ---|5 formes| spk-015[Enric Casadevall Medrano]
  spk-009[Antoni Jordi Areny] ---|5 formes| spk-026[Jordi Farràs Forné]
  spk-009[Antoni Jordi Areny] ---|5 formes| spk-037[Maria Reig Moles]
  spk-009[Antoni Jordi Areny] ---|5 formes| spk-038[Mercè Segura]
  spk-009[Antoni Jordi Areny] ---|5 formes| spk-039[Miquel Aleix Areny]
  spk-009[Antoni Jordi Areny] ---|5 formes| spk-041[Miquel Naudi Casal]
  spk-009[Antoni Jordi Areny] ---|5 formes| spk-054[Roser Jordana]
  spk-009[Antoni Jordi Areny] ---|5 formes| spk-059[Xavier Planas]
  spk-010[Antoni Morell] ---|5 formes| spk-014[Daniel Armengol]
  spk-010[Antoni Morell] ---|5 formes| spk-026[Jordi Farràs Forné]
  spk-010[Antoni Morell] ---|5 formes| spk-028[Jordi Mas Torres]
  spk-010[Antoni Morell] ---|5 formes| spk-031[Josep Areny Fité]
  spk-010[Antoni Morell] ---|5 formes| spk-040[Miquel Armengol Pons]
  spk-010[Antoni Morell] ---|5 formes| spk-041[Miquel Naudi Casal]
  spk-010[Antoni Morell] ---|5 formes| spk-043[Nadia Aleix Tugas]
  spk-010[Antoni Morell] ---|5 formes| spk-048[Ramon Canut Bové]
  spk-010[Antoni Morell] ---|5 formes| spk-051[Rosa Maria Mandicó Alcobé]
  spk-010[Antoni Morell] ---|5 formes| spk-057[Teo Armengol]
  spk-011[Carles Sasplugas] ---|5 formes| spk-016[Enric Dolsa Font]
  spk-011[Carles Sasplugas] ---|5 formes| spk-018[Eudald Guillamet]
  spk-011[Carles Sasplugas] ---|5 formes| spk-035[Ladislau Baró Solà]
  spk-011[Carles Sasplugas] ---|5 formes| spk-038[Mercè Segura]
  spk-011[Carles Sasplugas] ---|5 formes| spk-041[Miquel Naudi Casal]
  spk-011[Carles Sasplugas] ---|5 formes| spk-042[Mossèn Ramon de Canillo]
  spk-011[Carles Sasplugas] ---|5 formes| spk-043[Nadia Aleix Tugas]
  spk-011[Carles Sasplugas] ---|5 formes| spk-054[Roser Jordana]
  spk-014[Daniel Armengol] ---|5 formes| spk-018[Eudald Guillamet]
  spk-014[Daniel Armengol] ---|5 formes| spk-024[Jaume Bartumeu Cassany]
  spk-014[Daniel Armengol] ---|5 formes| spk-026[Jordi Farràs Forné]
  spk-014[Daniel Armengol] ---|5 formes| spk-037[Maria Reig Moles]
  spk-014[Daniel Armengol] ---|5 formes| spk-038[Mercè Segura]
  spk-014[Daniel Armengol] ---|5 formes| spk-053[Roser Bastida]
  spk-015[Enric Casadevall Medrano] ---|5 formes| spk-016[Enric Dolsa Font]
  spk-015[Enric Casadevall Medrano] ---|5 formes| spk-026[Jordi Farràs Forné]
  spk-015[Enric Casadevall Medrano] ---|5 formes| spk-035[Ladislau Baró Solà]
  spk-015[Enric Casadevall Medrano] ---|5 formes| spk-040[Miquel Armengol Pons]
  spk-015[Enric Casadevall Medrano] ---|5 formes| spk-059[Xavier Planas]
  spk-016[Enric Dolsa Font] ---|5 formes| spk-017[Esther Jover]
  spk-016[Enric Dolsa Font] ---|5 formes| spk-027[Jordi Marquet]
  spk-016[Enric Dolsa Font] ---|5 formes| spk-039[Miquel Aleix Areny]
  spk-016[Enric Dolsa Font] ---|5 formes| spk-048[Ramon Canut Bové]
  spk-016[Enric Dolsa Font] ---|5 formes| spk-050[Robert Lizarte]
  spk-017[Esther Jover] ---|5 formes| spk-018[Eudald Guillamet]
  spk-017[Esther Jover] ---|5 formes| spk-026[Jordi Farràs Forné]
  spk-017[Esther Jover] ---|5 formes| spk-028[Jordi Mas Torres]
  spk-017[Esther Jover] ---|5 formes| spk-031[Josep Areny Fité]
  spk-017[Esther Jover] ---|5 formes| spk-053[Roser Bastida]
  spk-018[Eudald Guillamet] ---|5 formes| spk-020[Gabriel Dallerès Codina]
  spk-018[Eudald Guillamet] ---|5 formes| spk-022[Guillem Areny Argelich]
  spk-018[Eudald Guillamet] ---|5 formes| spk-024[Jaume Bartumeu Cassany]
  spk-018[Eudald Guillamet] ---|5 formes| spk-038[Mercè Segura]
  spk-018[Eudald Guillamet] ---|5 formes| spk-040[Miquel Armengol Pons]
  spk-018[Eudald Guillamet] ---|5 formes| spk-041[Miquel Naudi Casal]
  spk-018[Eudald Guillamet] ---|5 formes| spk-053[Roser Bastida]
  spk-019[Francina Pons] ---|5 formes| spk-044[Olga Adellach Coma]
  spk-020[Gabriel Dallerès Codina] ---|5 formes| spk-037[Maria Reig Moles]
  spk-020[Gabriel Dallerès Codina] ---|5 formes| spk-044[Olga Adellach Coma]
  spk-020[Gabriel Dallerès Codina] ---|5 formes| spk-054[Roser Jordana]
  spk-022[Guillem Areny Argelich] ---|5 formes| spk-028[Jordi Mas Torres]
  spk-022[Guillem Areny Argelich] ---|5 formes| spk-037[Maria Reig Moles]
  spk-022[Guillem Areny Argelich] ---|5 formes| spk-042[Mossèn Ramon de Canillo]
  spk-022[Guillem Areny Argelich] ---|5 formes| spk-044[Olga Adellach Coma]
  spk-022[Guillem Areny Argelich] ---|5 formes| spk-054[Roser Jordana]
  spk-024[Jaume Bartumeu Cassany] ---|5 formes| spk-035[Ladislau Baró Solà]
  spk-024[Jaume Bartumeu Cassany] ---|5 formes| spk-037[Maria Reig Moles]
  spk-024[Jaume Bartumeu Cassany] ---|5 formes| spk-038[Mercè Segura]
  spk-024[Jaume Bartumeu Cassany] ---|5 formes| spk-042[Mossèn Ramon de Canillo]
  spk-024[Jaume Bartumeu Cassany] ---|5 formes| spk-048[Ramon Canut Bové]
  spk-024[Jaume Bartumeu Cassany] ---|5 formes| spk-053[Roser Bastida]
  spk-024[Jaume Bartumeu Cassany] ---|5 formes| spk-054[Roser Jordana]
  spk-026[Jordi Farràs Forné] ---|5 formes| spk-033[Josep Garrallà Rossell]
  spk-026[Jordi Farràs Forné] ---|5 formes| spk-041[Miquel Naudi Casal]
  spk-026[Jordi Farràs Forné] ---|5 formes| spk-042[Mossèn Ramon de Canillo]
  spk-026[Jordi Farràs Forné] ---|5 formes| spk-043[Nadia Aleix Tugas]
  spk-026[Jordi Farràs Forné] ---|5 formes| spk-051[Rosa Maria Mandicó Alcobé]
  spk-026[Jordi Farràs Forné] ---|5 formes| spk-059[Xavier Planas]
  spk-027[Jordi Marquet] ---|5 formes| spk-042[Mossèn Ramon de Canillo]
  spk-028[Jordi Mas Torres] ---|5 formes| spk-031[Josep Areny Fité]
  spk-028[Jordi Mas Torres] ---|5 formes| spk-040[Miquel Armengol Pons]
  spk-028[Jordi Mas Torres] ---|5 formes| spk-041[Miquel Naudi Casal]
  spk-028[Jordi Mas Torres] ---|5 formes| spk-042[Mossèn Ramon de Canillo]
  spk-028[Jordi Mas Torres] ---|5 formes| spk-045[Patrick Pérez]
  spk-028[Jordi Mas Torres] ---|5 formes| spk-046[Pere Altimir Pintat]
  spk-028[Jordi Mas Torres] ---|5 formes| spk-050[Robert Lizarte]
  spk-028[Jordi Mas Torres] ---|5 formes| spk-053[Roser Bastida]
  spk-031[Josep Areny Fité] ---|5 formes| spk-037[Maria Reig Moles]
  spk-031[Josep Areny Fité] ---|5 formes| spk-041[Miquel Naudi Casal]
  spk-031[Josep Areny Fité] ---|5 formes| spk-042[Mossèn Ramon de Canillo]
  spk-031[Josep Areny Fité] ---|5 formes| spk-045[Patrick Pérez]
  spk-031[Josep Areny Fité] ---|5 formes| spk-053[Roser Bastida]
  spk-031[Josep Areny Fité] ---|5 formes| spk-054[Roser Jordana]
  spk-031[Josep Areny Fité] ---|5 formes| spk-057[Teo Armengol]
  spk-033[Josep Garrallà Rossell] ---|5 formes| spk-038[Mercè Segura]
  spk-033[Josep Garrallà Rossell] ---|5 formes| spk-042[Mossèn Ramon de Canillo]
  spk-033[Josep Garrallà Rossell] ---|5 formes| spk-053[Roser Bastida]
  spk-033[Josep Garrallà Rossell] ---|5 formes| spk-054[Roser Jordana]
  spk-033[Josep Garrallà Rossell] ---|5 formes| spk-059[Xavier Planas]
  spk-035[Ladislau Baró Solà] ---|5 formes| spk-046[Pere Altimir Pintat]
  spk-037[Maria Reig Moles] ---|5 formes| spk-050[Robert Lizarte]
  spk-037[Maria Reig Moles] ---|5 formes| spk-059[Xavier Planas]
  spk-038[Mercè Segura] ---|5 formes| spk-042[Mossèn Ramon de Canillo]
  spk-038[Mercè Segura] ---|5 formes| spk-048[Ramon Canut Bové]
  spk-039[Miquel Aleix Areny] ---|5 formes| spk-044[Olga Adellach Coma]
  spk-040[Miquel Armengol Pons] ---|5 formes| spk-042[Mossèn Ramon de Canillo]
  spk-040[Miquel Armengol Pons] ---|5 formes| spk-043[Nadia Aleix Tugas]
  spk-040[Miquel Armengol Pons] ---|5 formes| spk-045[Patrick Pérez]
  spk-040[Miquel Armengol Pons] ---|5 formes| spk-053[Roser Bastida]
  spk-041[Miquel Naudi Casal] ---|5 formes| spk-045[Patrick Pérez]
  spk-041[Miquel Naudi Casal] ---|5 formes| spk-053[Roser Bastida]
  spk-041[Miquel Naudi Casal] ---|5 formes| spk-057[Teo Armengol]
  spk-041[Miquel Naudi Casal] ---|5 formes| spk-059[Xavier Planas]
  spk-042[Mossèn Ramon de Canillo] ---|5 formes| spk-045[Patrick Pérez]
  spk-042[Mossèn Ramon de Canillo] ---|5 formes| spk-050[Robert Lizarte]
  spk-042[Mossèn Ramon de Canillo] ---|5 formes| spk-057[Teo Armengol]
  spk-042[Mossèn Ramon de Canillo] ---|5 formes| spk-059[Xavier Planas]
  spk-043[Nadia Aleix Tugas] ---|5 formes| spk-045[Patrick Pérez]
  spk-043[Nadia Aleix Tugas] ---|5 formes| spk-059[Xavier Planas]
  spk-044[Olga Adellach Coma] ---|5 formes| spk-049[Robert Cassany Vila]
  spk-044[Olga Adellach Coma] ---|5 formes| spk-051[Rosa Maria Mandicó Alcobé]
  spk-045[Patrick Pérez] ---|5 formes| spk-053[Roser Bastida]
  spk-046[Pere Altimir Pintat] ---|5 formes| spk-057[Teo Armengol]
  spk-050[Robert Lizarte] ---|5 formes| spk-054[Roser Jordana]
  spk-050[Robert Lizarte] ---|5 formes| spk-057[Teo Armengol]
  spk-051[Rosa Maria Mandicó Alcobé] ---|5 formes| spk-053[Roser Bastida]
  spk-053[Roser Bastida] ---|5 formes| spk-054[Roser Jordana]
  spk-053[Roser Bastida] ---|5 formes| spk-057[Teo Armengol]
  spk-053[Roser Bastida] ---|5 formes| spk-059[Xavier Planas]
  spk-054[Roser Jordana] ---|5 formes| spk-059[Xavier Planas]
  spk-001[Alan Ward] ---|4 formes| spk-014[Daniel Armengol]
  spk-001[Alan Ward] ---|4 formes| spk-015[Enric Casadevall Medrano]
  spk-001[Alan Ward] ---|4 formes| spk-017[Esther Jover]
  spk-001[Alan Ward] ---|4 formes| spk-026[Jordi Farràs Forné]
  spk-001[Alan Ward] ---|4 formes| spk-028[Jordi Mas Torres]
  spk-001[Alan Ward] ---|4 formes| spk-030[Josep Areny]
  spk-001[Alan Ward] ---|4 formes| spk-041[Miquel Naudi Casal]
  spk-001[Alan Ward] ---|4 formes| spk-049[Robert Cassany Vila]
  spk-001[Alan Ward] ---|4 formes| spk-053[Roser Bastida]
  spk-001[Alan Ward] ---|4 formes| spk-057[Teo Armengol]
  spk-001[Alan Ward] ---|4 formes| spk-059[Xavier Planas]
  spk-002[Albert Gelabert Grau] ---|4 formes| spk-007[Angelina Mas]
  spk-002[Albert Gelabert Grau] ---|4 formes| spk-008[Antoni Armengol Vila]
  spk-002[Albert Gelabert Grau] ---|4 formes| spk-015[Enric Casadevall Medrano]
  spk-002[Albert Gelabert Grau] ---|4 formes| spk-016[Enric Dolsa Font]
  spk-002[Albert Gelabert Grau] ---|4 formes| spk-024[Jaume Bartumeu Cassany]
  spk-002[Albert Gelabert Grau] ---|4 formes| spk-029[Jordi Torres Alís]
  spk-002[Albert Gelabert Grau] ---|4 formes| spk-035[Ladislau Baró Solà]
  spk-002[Albert Gelabert Grau] ---|4 formes| spk-046[Pere Altimir Pintat]
  spk-002[Albert Gelabert Grau] ---|4 formes| spk-053[Roser Bastida]
  spk-002[Albert Gelabert Grau] ---|4 formes| spk-059[Xavier Planas]
  spk-003[Albert Roig] ---|4 formes| spk-006[Andreu Gaspà Picart]
  spk-003[Albert Roig] ---|4 formes| spk-008[Antoni Armengol Vila]
  spk-003[Albert Roig] ---|4 formes| spk-015[Enric Casadevall Medrano]
  spk-003[Albert Roig] ---|4 formes| spk-018[Eudald Guillamet]
  spk-003[Albert Roig] ---|4 formes| spk-028[Jordi Mas Torres]
  spk-003[Albert Roig] ---|4 formes| spk-038[Mercè Segura]
  spk-003[Albert Roig] ---|4 formes| spk-040[Miquel Armengol Pons]
  spk-003[Albert Roig] ---|4 formes| spk-054[Roser Jordana]
  spk-003[Albert Roig] ---|4 formes| spk-057[Teo Armengol]
  spk-003[Albert Roig] ---|4 formes| spk-059[Xavier Planas]
  spk-005[Alfred Llahí] ---|4 formes| spk-006[Andreu Gaspà Picart]
  spk-005[Alfred Llahí] ---|4 formes| spk-011[Carles Sasplugas]
  spk-005[Alfred Llahí] ---|4 formes| spk-033[Josep Garrallà Rossell]
  spk-005[Alfred Llahí] ---|4 formes| spk-039[Miquel Aleix Areny]
  spk-005[Alfred Llahí] ---|4 formes| spk-045[Patrick Pérez]
  spk-005[Alfred Llahí] ---|4 formes| spk-048[Ramon Canut Bové]
  spk-005[Alfred Llahí] ---|4 formes| spk-049[Robert Cassany Vila]
  spk-005[Alfred Llahí] ---|4 formes| spk-051[Rosa Maria Mandicó Alcobé]
  spk-005[Alfred Llahí] ---|4 formes| spk-055[Ruth Casabella]
  spk-005[Alfred Llahí] ---|4 formes| spk-056[Sara Ubach]
  spk-006[Andreu Gaspà Picart] ---|4 formes| spk-008[Antoni Armengol Vila]
  spk-006[Andreu Gaspà Picart] ---|4 formes| spk-009[Antoni Jordi Areny]
  spk-006[Andreu Gaspà Picart] ---|4 formes| spk-018[Eudald Guillamet]
  spk-006[Andreu Gaspà Picart] ---|4 formes| spk-022[Guillem Areny Argelich]
  spk-006[Andreu Gaspà Picart] ---|4 formes| spk-031[Josep Areny Fité]
  spk-006[Andreu Gaspà Picart] ---|4 formes| spk-033[Josep Garrallà Rossell]
  spk-006[Andreu Gaspà Picart] ---|4 formes| spk-046[Pere Altimir Pintat]
  spk-006[Andreu Gaspà Picart] ---|4 formes| spk-050[Robert Lizarte]
  spk-006[Andreu Gaspà Picart] ---|4 formes| spk-053[Roser Bastida]
  spk-006[Andreu Gaspà Picart] ---|4 formes| spk-057[Teo Armengol]
  spk-007[Angelina Mas] ---|4 formes| spk-017[Esther Jover]
  spk-007[Angelina Mas] ---|4 formes| spk-019[Francina Pons]
  spk-007[Angelina Mas] ---|4 formes| spk-020[Gabriel Dallerès Codina]
  spk-007[Angelina Mas] ---|4 formes| spk-022[Guillem Areny Argelich]
  spk-007[Angelina Mas] ---|4 formes| spk-025[Joan Santamaria Terré]
  spk-007[Angelina Mas] ---|4 formes| spk-030[Josep Areny]
  spk-007[Angelina Mas] ---|4 formes| spk-035[Ladislau Baró Solà]
  spk-007[Angelina Mas] ---|4 formes| spk-051[Rosa Maria Mandicó Alcobé]
  spk-007[Angelina Mas] ---|4 formes| spk-059[Xavier Planas]
  spk-008[Antoni Armengol Vila] ---|4 formes| spk-014[Daniel Armengol]
  spk-008[Antoni Armengol Vila] ---|4 formes| spk-015[Enric Casadevall Medrano]
  spk-008[Antoni Armengol Vila] ---|4 formes| spk-024[Jaume Bartumeu Cassany]
  spk-008[Antoni Armengol Vila] ---|4 formes| spk-027[Jordi Marquet]
  spk-008[Antoni Armengol Vila] ---|4 formes| spk-034[Josep Marsal Riba]
  spk-008[Antoni Armengol Vila] ---|4 formes| spk-035[Ladislau Baró Solà]
  spk-008[Antoni Armengol Vila] ---|4 formes| spk-048[Ramon Canut Bové]
  spk-008[Antoni Armengol Vila] ---|4 formes| spk-051[Rosa Maria Mandicó Alcobé]
  spk-008[Antoni Armengol Vila] ---|4 formes| spk-057[Teo Armengol]
  spk-009[Antoni Jordi Areny] ---|4 formes| spk-010[Antoni Morell]
  spk-009[Antoni Jordi Areny] ---|4 formes| spk-011[Carles Sasplugas]
  spk-009[Antoni Jordi Areny] ---|4 formes| spk-014[Daniel Armengol]
  spk-009[Antoni Jordi Areny] ---|4 formes| spk-017[Esther Jover]
  spk-009[Antoni Jordi Areny] ---|4 formes| spk-018[Eudald Guillamet]
  spk-009[Antoni Jordi Areny] ---|4 formes| spk-019[Francina Pons]
  spk-009[Antoni Jordi Areny] ---|4 formes| spk-020[Gabriel Dallerès Codina]
  spk-009[Antoni Jordi Areny] ---|4 formes| spk-022[Guillem Areny Argelich]
  spk-009[Antoni Jordi Areny] ---|4 formes| spk-024[Jaume Bartumeu Cassany]
  spk-009[Antoni Jordi Areny] ---|4 formes| spk-028[Jordi Mas Torres]
  spk-009[Antoni Jordi Areny] ---|4 formes| spk-030[Josep Areny]
  spk-009[Antoni Jordi Areny] ---|4 formes| spk-033[Josep Garrallà Rossell]
  spk-009[Antoni Jordi Areny] ---|4 formes| spk-040[Miquel Armengol Pons]
  spk-009[Antoni Jordi Areny] ---|4 formes| spk-042[Mossèn Ramon de Canillo]
  spk-009[Antoni Jordi Areny] ---|4 formes| spk-046[Pere Altimir Pintat]
  spk-009[Antoni Jordi Areny] ---|4 formes| spk-049[Robert Cassany Vila]
  spk-009[Antoni Jordi Areny] ---|4 formes| spk-051[Rosa Maria Mandicó Alcobé]
  spk-009[Antoni Jordi Areny] ---|4 formes| spk-057[Teo Armengol]
  spk-010[Antoni Morell] ---|4 formes| spk-011[Carles Sasplugas]
  spk-010[Antoni Morell] ---|4 formes| spk-017[Esther Jover]
  spk-010[Antoni Morell] ---|4 formes| spk-020[Gabriel Dallerès Codina]
  spk-010[Antoni Morell] ---|4 formes| spk-030[Josep Areny]
  spk-010[Antoni Morell] ---|4 formes| spk-036[Ludmilla Lacueva]
  spk-010[Antoni Morell] ---|4 formes| spk-038[Mercè Segura]
  spk-010[Antoni Morell] ---|4 formes| spk-039[Miquel Aleix Areny]
  spk-010[Antoni Morell] ---|4 formes| spk-046[Pere Altimir Pintat]
  spk-010[Antoni Morell] ---|4 formes| spk-053[Roser Bastida]
  spk-010[Antoni Morell] ---|4 formes| spk-059[Xavier Planas]
  spk-011[Carles Sasplugas] ---|4 formes| spk-015[Enric Casadevall Medrano]
  spk-011[Carles Sasplugas] ---|4 formes| spk-017[Esther Jover]
  spk-011[Carles Sasplugas] ---|4 formes| spk-019[Francina Pons]
  spk-011[Carles Sasplugas] ---|4 formes| spk-020[Gabriel Dallerès Codina]
  spk-011[Carles Sasplugas] ---|4 formes| spk-024[Jaume Bartumeu Cassany]
  spk-011[Carles Sasplugas] ---|4 formes| spk-025[Joan Santamaria Terré]
  spk-011[Carles Sasplugas] ---|4 formes| spk-028[Jordi Mas Torres]
  spk-011[Carles Sasplugas] ---|4 formes| spk-029[Jordi Torres Alís]
  spk-011[Carles Sasplugas] ---|4 formes| spk-031[Josep Areny Fité]
  spk-011[Carles Sasplugas] ---|4 formes| spk-048[Ramon Canut Bové]
  spk-011[Carles Sasplugas] ---|4 formes| spk-057[Teo Armengol]
  spk-011[Carles Sasplugas] ---|4 formes| spk-059[Xavier Planas]
  spk-014[Daniel Armengol] ---|4 formes| spk-015[Enric Casadevall Medrano]
  spk-014[Daniel Armengol] ---|4 formes| spk-017[Esther Jover]
  spk-014[Daniel Armengol] ---|4 formes| spk-027[Jordi Marquet]
  spk-014[Daniel Armengol] ---|4 formes| spk-028[Jordi Mas Torres]
  spk-014[Daniel Armengol] ---|4 formes| spk-031[Josep Areny Fité]
  spk-014[Daniel Armengol] ---|4 formes| spk-033[Josep Garrallà Rossell]
  spk-014[Daniel Armengol] ---|4 formes| spk-041[Miquel Naudi Casal]
  spk-014[Daniel Armengol] ---|4 formes| spk-045[Patrick Pérez]
  spk-014[Daniel Armengol] ---|4 formes| spk-046[Pere Altimir Pintat]
  spk-014[Daniel Armengol] ---|4 formes| spk-048[Ramon Canut Bové]
  spk-014[Daniel Armengol] ---|4 formes| spk-050[Robert Lizarte]
  spk-014[Daniel Armengol] ---|4 formes| spk-051[Rosa Maria Mandicó Alcobé]
  spk-014[Daniel Armengol] ---|4 formes| spk-059[Xavier Planas]
  spk-015[Enric Casadevall Medrano] ---|4 formes| spk-017[Esther Jover]
  spk-015[Enric Casadevall Medrano] ---|4 formes| spk-027[Jordi Marquet]
  spk-015[Enric Casadevall Medrano] ---|4 formes| spk-029[Jordi Torres Alís]
  spk-015[Enric Casadevall Medrano] ---|4 formes| spk-031[Josep Areny Fité]
  spk-015[Enric Casadevall Medrano] ---|4 formes| spk-033[Josep Garrallà Rossell]
  spk-015[Enric Casadevall Medrano] ---|4 formes| spk-038[Mercè Segura]
  spk-015[Enric Casadevall Medrano] ---|4 formes| spk-039[Miquel Aleix Areny]
  spk-015[Enric Casadevall Medrano] ---|4 formes| spk-042[Mossèn Ramon de Canillo]
  spk-015[Enric Casadevall Medrano] ---|4 formes| spk-043[Nadia Aleix Tugas]
  spk-015[Enric Casadevall Medrano] ---|4 formes| spk-046[Pere Altimir Pintat]
  spk-015[Enric Casadevall Medrano] ---|4 formes| spk-057[Teo Armengol]
  spk-016[Enric Dolsa Font] ---|4 formes| spk-020[Gabriel Dallerès Codina]
  spk-016[Enric Dolsa Font] ---|4 formes| spk-030[Josep Areny]
  spk-016[Enric Dolsa Font] ---|4 formes| spk-034[Josep Marsal Riba]
  spk-016[Enric Dolsa Font] ---|4 formes| spk-035[Ladislau Baró Solà]
  spk-016[Enric Dolsa Font] ---|4 formes| spk-051[Rosa Maria Mandicó Alcobé]
  spk-017[Esther Jover] ---|4 formes| spk-019[Francina Pons]
  spk-017[Esther Jover] ---|4 formes| spk-024[Jaume Bartumeu Cassany]
  spk-017[Esther Jover] ---|4 formes| spk-033[Josep Garrallà Rossell]
  spk-017[Esther Jover] ---|4 formes| spk-038[Mercè Segura]
  spk-017[Esther Jover] ---|4 formes| spk-040[Miquel Armengol Pons]
  spk-017[Esther Jover] ---|4 formes| spk-042[Mossèn Ramon de Canillo]
  spk-017[Esther Jover] ---|4 formes| spk-043[Nadia Aleix Tugas]
  spk-017[Esther Jover] ---|4 formes| spk-048[Ramon Canut Bové]
  spk-017[Esther Jover] ---|4 formes| spk-050[Robert Lizarte]
  spk-017[Esther Jover] ---|4 formes| spk-054[Roser Jordana]
  spk-017[Esther Jover] ---|4 formes| spk-055[Ruth Casabella]
  spk-017[Esther Jover] ---|4 formes| spk-057[Teo Armengol]
  spk-017[Esther Jover] ---|4 formes| spk-059[Xavier Planas]
  spk-018[Eudald Guillamet] ---|4 formes| spk-031[Josep Areny Fité]
  spk-018[Eudald Guillamet] ---|4 formes| spk-033[Josep Garrallà Rossell]
  spk-018[Eudald Guillamet] ---|4 formes| spk-035[Ladislau Baró Solà]
  spk-018[Eudald Guillamet] ---|4 formes| spk-036[Ludmilla Lacueva]
  spk-018[Eudald Guillamet] ---|4 formes| spk-049[Robert Cassany Vila]
  spk-018[Eudald Guillamet] ---|4 formes| spk-056[Sara Ubach]
  spk-018[Eudald Guillamet] ---|4 formes| spk-059[Xavier Planas]
  spk-019[Francina Pons] ---|4 formes| spk-026[Jordi Farràs Forné]
  spk-019[Francina Pons] ---|4 formes| spk-028[Jordi Mas Torres]
  spk-019[Francina Pons] ---|4 formes| spk-038[Mercè Segura]
  spk-019[Francina Pons] ---|4 formes| spk-048[Ramon Canut Bové]
  spk-019[Francina Pons] ---|4 formes| spk-053[Roser Bastida]
  spk-019[Francina Pons] ---|4 formes| spk-057[Teo Armengol]
  spk-020[Gabriel Dallerès Codina] ---|4 formes| spk-026[Jordi Farràs Forné]
  spk-020[Gabriel Dallerès Codina] ---|4 formes| spk-042[Mossèn Ramon de Canillo]
  spk-020[Gabriel Dallerès Codina] ---|4 formes| spk-043[Nadia Aleix Tugas]
  spk-020[Gabriel Dallerès Codina] ---|4 formes| spk-045[Patrick Pérez]
  spk-020[Gabriel Dallerès Codina] ---|4 formes| spk-046[Pere Altimir Pintat]
  spk-020[Gabriel Dallerès Codina] ---|4 formes| spk-048[Ramon Canut Bové]
  spk-020[Gabriel Dallerès Codina] ---|4 formes| spk-053[Roser Bastida]
  spk-022[Guillem Areny Argelich] ---|4 formes| spk-026[Jordi Farràs Forné]
  spk-022[Guillem Areny Argelich] ---|4 formes| spk-041[Miquel Naudi Casal]
  spk-022[Guillem Areny Argelich] ---|4 formes| spk-043[Nadia Aleix Tugas]
  spk-022[Guillem Areny Argelich] ---|4 formes| spk-046[Pere Altimir Pintat]
  spk-022[Guillem Areny Argelich] ---|4 formes| spk-050[Robert Lizarte]
  spk-022[Guillem Areny Argelich] ---|4 formes| spk-053[Roser Bastida]
  spk-022[Guillem Areny Argelich] ---|4 formes| spk-057[Teo Armengol]
  spk-024[Jaume Bartumeu Cassany] ---|4 formes| spk-027[Jordi Marquet]
  spk-024[Jaume Bartumeu Cassany] ---|4 formes| spk-028[Jordi Mas Torres]
  spk-024[Jaume Bartumeu Cassany] ---|4 formes| spk-029[Jordi Torres Alís]
  spk-024[Jaume Bartumeu Cassany] ---|4 formes| spk-031[Josep Areny Fité]
  spk-024[Jaume Bartumeu Cassany] ---|4 formes| spk-045[Patrick Pérez]
  spk-024[Jaume Bartumeu Cassany] ---|4 formes| spk-046[Pere Altimir Pintat]
  spk-024[Jaume Bartumeu Cassany] ---|4 formes| spk-050[Robert Lizarte]
  spk-024[Jaume Bartumeu Cassany] ---|4 formes| spk-051[Rosa Maria Mandicó Alcobé]
  spk-024[Jaume Bartumeu Cassany] ---|4 formes| spk-059[Xavier Planas]
  spk-025[Joan Santamaria Terré] ---|4 formes| spk-026[Jordi Farràs Forné]
  spk-025[Joan Santamaria Terré] ---|4 formes| spk-038[Mercè Segura]
  spk-025[Joan Santamaria Terré] ---|4 formes| spk-044[Olga Adellach Coma]
  spk-025[Joan Santamaria Terré] ---|4 formes| spk-046[Pere Altimir Pintat]
  spk-025[Joan Santamaria Terré] ---|4 formes| spk-053[Roser Bastida]
  spk-025[Joan Santamaria Terré] ---|4 formes| spk-057[Teo Armengol]
  spk-026[Jordi Farràs Forné] ---|4 formes| spk-029[Jordi Torres Alís]
  spk-026[Jordi Farràs Forné] ---|4 formes| spk-031[Josep Areny Fité]
  spk-026[Jordi Farràs Forné] ---|4 formes| spk-049[Robert Cassany Vila]
  spk-026[Jordi Farràs Forné] ---|4 formes| spk-050[Robert Lizarte]
  spk-027[Jordi Marquet] ---|4 formes| spk-031[Josep Areny Fité]
  spk-027[Jordi Marquet] ---|4 formes| spk-037[Maria Reig Moles]
  spk-027[Jordi Marquet] ---|4 formes| spk-039[Miquel Aleix Areny]
  spk-027[Jordi Marquet] ---|4 formes| spk-040[Miquel Armengol Pons]
  spk-027[Jordi Marquet] ---|4 formes| spk-044[Olga Adellach Coma]
  spk-027[Jordi Marquet] ---|4 formes| spk-053[Roser Bastida]
  spk-028[Jordi Mas Torres] ---|4 formes| spk-033[Josep Garrallà Rossell]
  spk-028[Jordi Mas Torres] ---|4 formes| spk-035[Ladislau Baró Solà]
  spk-029[Jordi Torres Alís] ---|4 formes| spk-035[Ladislau Baró Solà]
  spk-029[Jordi Torres Alís] ---|4 formes| spk-044[Olga Adellach Coma]
  spk-029[Jordi Torres Alís] ---|4 formes| spk-053[Roser Bastida]
  spk-030[Josep Areny] ---|4 formes| spk-042[Mossèn Ramon de Canillo]
  spk-030[Josep Areny] ---|4 formes| spk-044[Olga Adellach Coma]
  spk-031[Josep Areny Fité] ---|4 formes| spk-033[Josep Garrallà Rossell]
  spk-031[Josep Areny Fité] ---|4 formes| spk-034[Josep Marsal Riba]
  spk-031[Josep Areny Fité] ---|4 formes| spk-039[Miquel Aleix Areny]
  spk-031[Josep Areny Fité] ---|4 formes| spk-046[Pere Altimir Pintat]
  spk-031[Josep Areny Fité] ---|4 formes| spk-048[Ramon Canut Bové]
  spk-031[Josep Areny Fité] ---|4 formes| spk-059[Xavier Planas]
  spk-033[Josep Garrallà Rossell] ---|4 formes| spk-035[Ladislau Baró Solà]
  spk-033[Josep Garrallà Rossell] ---|4 formes| spk-037[Maria Reig Moles]
  spk-033[Josep Garrallà Rossell] ---|4 formes| spk-040[Miquel Armengol Pons]
  spk-033[Josep Garrallà Rossell] ---|4 formes| spk-041[Miquel Naudi Casal]
  spk-033[Josep Garrallà Rossell] ---|4 formes| spk-043[Nadia Aleix Tugas]
  spk-033[Josep Garrallà Rossell] ---|4 formes| spk-057[Teo Armengol]
  spk-034[Josep Marsal Riba] ---|4 formes| spk-042[Mossèn Ramon de Canillo]
  spk-034[Josep Marsal Riba] ---|4 formes| spk-044[Olga Adellach Coma]
  spk-034[Josep Marsal Riba] ---|4 formes| spk-059[Xavier Planas]
  spk-035[Ladislau Baró Solà] ---|4 formes| spk-037[Maria Reig Moles]
  spk-035[Ladislau Baró Solà] ---|4 formes| spk-038[Mercè Segura]
  spk-035[Ladislau Baró Solà] ---|4 formes| spk-040[Miquel Armengol Pons]
  spk-035[Ladislau Baró Solà] ---|4 formes| spk-042[Mossèn Ramon de Canillo]
  spk-035[Ladislau Baró Solà] ---|4 formes| spk-043[Nadia Aleix Tugas]
  spk-035[Ladislau Baró Solà] ---|4 formes| spk-054[Roser Jordana]
  spk-035[Ladislau Baró Solà] ---|4 formes| spk-057[Teo Armengol]
  spk-035[Ladislau Baró Solà] ---|4 formes| spk-059[Xavier Planas]
  spk-036[Ludmilla Lacueva] ---|4 formes| spk-037[Maria Reig Moles]
  spk-036[Ludmilla Lacueva] ---|4 formes| spk-044[Olga Adellach Coma]
  spk-036[Ludmilla Lacueva] ---|4 formes| spk-054[Roser Jordana]
  spk-037[Maria Reig Moles] ---|4 formes| spk-039[Miquel Aleix Areny]
  spk-037[Maria Reig Moles] ---|4 formes| spk-049[Robert Cassany Vila]
  spk-037[Maria Reig Moles] ---|4 formes| spk-051[Rosa Maria Mandicó Alcobé]
  spk-037[Maria Reig Moles] ---|4 formes| spk-056[Sara Ubach]
  spk-038[Mercè Segura] ---|4 formes| spk-050[Robert Lizarte]
  spk-038[Mercè Segura] ---|4 formes| spk-051[Rosa Maria Mandicó Alcobé]
  spk-039[Miquel Aleix Areny] ---|4 formes| spk-040[Miquel Armengol Pons]
  spk-039[Miquel Aleix Areny] ---|4 formes| spk-041[Miquel Naudi Casal]
  spk-039[Miquel Aleix Areny] ---|4 formes| spk-043[Nadia Aleix Tugas]
  spk-039[Miquel Aleix Areny] ---|4 formes| spk-054[Roser Jordana]
  spk-039[Miquel Aleix Areny] ---|4 formes| spk-059[Xavier Planas]
  spk-040[Miquel Armengol Pons] ---|4 formes| spk-041[Miquel Naudi Casal]
  spk-040[Miquel Armengol Pons] ---|4 formes| spk-046[Pere Altimir Pintat]
  spk-040[Miquel Armengol Pons] ---|4 formes| spk-050[Robert Lizarte]
  spk-040[Miquel Armengol Pons] ---|4 formes| spk-051[Rosa Maria Mandicó Alcobé]
  spk-040[Miquel Armengol Pons] ---|4 formes| spk-059[Xavier Planas]
  spk-041[Miquel Naudi Casal] ---|4 formes| spk-049[Robert Cassany Vila]
  spk-041[Miquel Naudi Casal] ---|4 formes| spk-050[Robert Lizarte]
  spk-041[Miquel Naudi Casal] ---|4 formes| spk-056[Sara Ubach]
  spk-042[Mossèn Ramon de Canillo] ---|4 formes| spk-048[Ramon Canut Bové]
  spk-042[Mossèn Ramon de Canillo] ---|4 formes| spk-051[Rosa Maria Mandicó Alcobé]
  spk-042[Mossèn Ramon de Canillo] ---|4 formes| spk-055[Ruth Casabella]
  spk-043[Nadia Aleix Tugas] ---|4 formes| spk-048[Ramon Canut Bové]
  spk-043[Nadia Aleix Tugas] ---|4 formes| spk-050[Robert Lizarte]
  spk-043[Nadia Aleix Tugas] ---|4 formes| spk-057[Teo Armengol]
  spk-044[Olga Adellach Coma] ---|4 formes| spk-055[Ruth Casabella]
  spk-044[Olga Adellach Coma] ---|4 formes| spk-056[Sara Ubach]
  spk-045[Patrick Pérez] ---|4 formes| spk-051[Rosa Maria Mandicó Alcobé]
  spk-046[Pere Altimir Pintat] ---|4 formes| spk-048[Ramon Canut Bové]
  spk-046[Pere Altimir Pintat] ---|4 formes| spk-050[Robert Lizarte]
  spk-046[Pere Altimir Pintat] ---|4 formes| spk-059[Xavier Planas]
  spk-048[Ramon Canut Bové] ---|4 formes| spk-050[Robert Lizarte]
  spk-048[Ramon Canut Bové] ---|4 formes| spk-051[Rosa Maria Mandicó Alcobé]
  spk-048[Ramon Canut Bové] ---|4 formes| spk-053[Roser Bastida]
  spk-049[Robert Cassany Vila] ---|4 formes| spk-054[Roser Jordana]
  spk-049[Robert Cassany Vila] ---|4 formes| spk-059[Xavier Planas]
  spk-050[Robert Lizarte] ---|4 formes| spk-053[Roser Bastida]
  spk-051[Rosa Maria Mandicó Alcobé] ---|4 formes| spk-054[Roser Jordana]
  spk-054[Roser Jordana] ---|4 formes| spk-056[Sara Ubach]
