flowchart LR
  pa001["pa-001 Albert Gelabert"]
  pa002["pa-002 Jordi Farràs"]
  pa003["pa-003 Roser Bastida"]
  t1["és a dir"]
  t2["evidentment"]
  t3["bueno"]
  t4["perífrasis d'obligació"]
  t5["ensenyança"]
  t6["reformeta"]
  pa001 -->|usa| t3
  pa002 -->|usa| t1
  pa003 -->|usa| t1
  pa002 -->|usa| t2
  pa003 -->|usa| t2
  pa002 -->|usa| t3
  pa003 -->|usa| t3
  pa002 -->|usa| t4
  pa003 -->|usa| t4
  pa003 -->|lèxic| t5
  pa002 -->|lèxic| t6
