flowchart LR
  prosodia1["prosodia-1"]
  prosodia2["prosodia-2"]
  prosodia3["prosodia-3"]
  prosodia4["prosodia-4"]
  pa001["pa-001"] --> prosodia2
  pa002["pa-002"] --> prosodia4
  pa003["pa-003"] --> prosodia3
  pa004["pa-004"] --> prosodia4
  pa005["pa-005"] --> prosodia4
  pa006["pa-006"] --> prosodia2
  pa007["pa-007"] --> prosodia3
  pa008["pa-008"] --> prosodia2
  pa009["pa-009"] --> prosodia2
  pa010["pa-010"] --> prosodia2
  pa011["pa-011"] --> prosodia3
  pa012["pa-012"] --> prosodia3
  pa013["pa-013"] --> prosodia3
  pa014["pa-014"] --> prosodia2
  pa015["pa-015"] --> prosodia1
  pa016["pa-016"] --> prosodia2
  pa017["pa-017"] --> prosodia2
  pa018["pa-018"] --> prosodia2
  pa019["pa-019"] --> prosodia2
  pa020["pa-020"] --> prosodia2
  pa021["pa-021"] --> prosodia2
  pa022["pa-022"] --> prosodia2
  pa023["pa-023"] --> prosodia2
  pa024["pa-024"] --> prosodia3
  pa025["pa-025"] --> prosodia2
  pa026["pa-026"] --> prosodia4
  pa027["pa-027"] --> prosodia2
  pa028["pa-028"] --> prosodia2
  pa029["pa-029"] --> prosodia2
  pa030["pa-030"] --> prosodia2
  pa031["pa-031"] --> prosodia2
  pa032["pa-032"] --> prosodia2
  pa033["pa-033"] --> prosodia2
  pa034["pa-034"] --> prosodia2
  pa035["pa-035"] --> prosodia2
  pa036["pa-036"] --> prosodia2
  pa037["pa-037"] --> prosodia2
  pa038["pa-038"] --> prosodia3
  pa039["pa-039"] --> prosodia2
  pa040["pa-040"] --> prosodia2
  pa041["pa-041"] --> prosodia3
  pa042["pa-042"] --> prosodia3
  pa043["pa-043"] --> prosodia3
  pa045["pa-045"] --> prosodia4
  pa046["pa-046"] --> prosodia2
  pa048["pa-048"] --> prosodia4
  pa049["pa-049"] --> prosodia2
  pa051["pa-051"] --> prosodia1
  pa052["pa-052"] --> prosodia1
  pa053["pa-053"] --> prosodia1
  pa054["pa-054"] --> prosodia1
  pa055["pa-055"] --> prosodia4
  pa056["pa-056"] --> prosodia2
  pa057["pa-057"] --> prosodia2
  pa058["pa-058"] --> prosodia2
  pa059["pa-059"] --> prosodia2
  pa060["pa-060"] --> prosodia2
  pa061["pa-061"] --> prosodia3
  pa062["pa-062"] --> prosodia4
  pa063["pa-063"] --> prosodia2
  pa064["pa-064"] --> prosodia2
  pa065["pa-065"] --> prosodia2
  pa066["pa-066"] --> prosodia3
