graph TD
  spk-016["Enric Dolsa Font"] ---|19 formes| spk-024["Jaume Bartumeu Cassany"]
  spk-015["Enric Casadevall Medrano"] ---|18 formes| spk-024["Jaume Bartumeu Cassany"]
  spk-016["Enric Dolsa Font"] ---|18 formes| spk-048["Ramon Canut Bové"]
  spk-024["Jaume Bartumeu Cassany"] ---|18 formes| spk-026["Jordi Farràs Forné"]
  spk-024["Jaume Bartumeu Cassany"] ---|18 formes| spk-048["Ramon Canut Bové"]
  spk-026["Jordi Farràs Forné"] ---|18 formes| spk-048["Ramon Canut Bové"]
  spk-016["Enric Dolsa Font"] ---|17 formes| spk-026["Jordi Farràs Forné"]
  spk-037["Maria Reig Moles"] ---|17 formes| spk-039["Miquel Aleix Areny"]
  spk-044["Olga Adellach Coma"] ---|17 formes| spk-048["Ramon Canut Bové"]
  spk-002["Albert Gelabert Grau"] ---|16 formes| spk-024["Jaume Bartumeu Cassany"]
  spk-003["Albert Roig"] ---|16 formes| spk-024["Jaume Bartumeu Cassany"]
  spk-005["Alfred Llahí"] ---|16 formes| spk-026["Jordi Farràs Forné"]
  spk-005["Alfred Llahí"] ---|16 formes| spk-039["Miquel Aleix Areny"]
  spk-005["Alfred Llahí"] ---|16 formes| spk-048["Ramon Canut Bové"]
  spk-007["Angelina Mas"] ---|16 formes| spk-039["Miquel Aleix Areny"]
  spk-015["Enric Casadevall Medrano"] ---|16 formes| spk-016["Enric Dolsa Font"]
  spk-015["Enric Casadevall Medrano"] ---|16 formes| spk-044["Olga Adellach Coma"]
  spk-016["Enric Dolsa Font"] ---|16 formes| spk-044["Olga Adellach Coma"]
  spk-024["Jaume Bartumeu Cassany"] ---|16 formes| spk-037["Maria Reig Moles"]
  spk-024["Jaume Bartumeu Cassany"] ---|16 formes| spk-039["Miquel Aleix Areny"]
  spk-024["Jaume Bartumeu Cassany"] ---|16 formes| spk-044["Olga Adellach Coma"]
  spk-026["Jordi Farràs Forné"] ---|16 formes| spk-028["Jordi Mas Torres"]
  spk-026["Jordi Farràs Forné"] ---|16 formes| spk-039["Miquel Aleix Areny"]
  spk-026["Jordi Farràs Forné"] ---|16 formes| spk-044["Olga Adellach Coma"]
  spk-028["Jordi Mas Torres"] ---|16 formes| spk-048["Ramon Canut Bové"]
  spk-002["Albert Gelabert Grau"] ---|15 formes| spk-026["Jordi Farràs Forné"]
  spk-005["Alfred Llahí"] ---|15 formes| spk-016["Enric Dolsa Font"]
  spk-005["Alfred Llahí"] ---|15 formes| spk-024["Jaume Bartumeu Cassany"]
  spk-007["Angelina Mas"] ---|15 formes| spk-016["Enric Dolsa Font"]
  spk-007["Angelina Mas"] ---|15 formes| spk-024["Jaume Bartumeu Cassany"]
  spk-007["Angelina Mas"] ---|15 formes| spk-044["Olga Adellach Coma"]
  spk-007["Angelina Mas"] ---|15 formes| spk-051["Rosa Maria Mandicó Alcobé"]
  spk-015["Enric Casadevall Medrano"] ---|15 formes| spk-026["Jordi Farràs Forné"]
  spk-015["Enric Casadevall Medrano"] ---|15 formes| spk-037["Maria Reig Moles"]
  spk-016["Enric Dolsa Font"] ---|15 formes| spk-035["Ladislau Baró Solà"]
  spk-016["Enric Dolsa Font"] ---|15 formes| spk-039["Miquel Aleix Areny"]
  spk-016["Enric Dolsa Font"] ---|15 formes| spk-051["Rosa Maria Mandicó Alcobé"]
  spk-022["Guillem Areny Argelich"] ---|15 formes| spk-024["Jaume Bartumeu Cassany"]
  spk-024["Jaume Bartumeu Cassany"] ---|15 formes| spk-035["Ladislau Baró Solà"]
  spk-026["Jordi Farràs Forné"] ---|15 formes| spk-035["Ladislau Baró Solà"]
  spk-026["Jordi Farràs Forné"] ---|15 formes| spk-051["Rosa Maria Mandicó Alcobé"]
  spk-035["Ladislau Baró Solà"] ---|15 formes| spk-044["Olga Adellach Coma"]
  spk-035["Ladislau Baró Solà"] ---|15 formes| spk-048["Ramon Canut Bové"]
  spk-039["Miquel Aleix Areny"] ---|15 formes| spk-048["Ramon Canut Bové"]
  spk-039["Miquel Aleix Areny"] ---|15 formes| spk-051["Rosa Maria Mandicó Alcobé"]
  spk-043["Nadia Aleix Tugas"] ---|15 formes| spk-048["Ramon Canut Bové"]
  spk-044["Olga Adellach Coma"] ---|15 formes| spk-051["Rosa Maria Mandicó Alcobé"]
  spk-048["Ramon Canut Bové"] ---|15 formes| spk-051["Rosa Maria Mandicó Alcobé"]
  spk-002["Albert Gelabert Grau"] ---|14 formes| spk-007["Angelina Mas"]
  spk-002["Albert Gelabert Grau"] ---|14 formes| spk-015["Enric Casadevall Medrano"]
  spk-002["Albert Gelabert Grau"] ---|14 formes| spk-044["Olga Adellach Coma"]
  spk-002["Albert Gelabert Grau"] ---|14 formes| spk-048["Ramon Canut Bové"]
  spk-003["Albert Roig"] ---|14 formes| spk-016["Enric Dolsa Font"]
  spk-003["Albert Roig"] ---|14 formes| spk-026["Jordi Farràs Forné"]
  spk-005["Alfred Llahí"] ---|14 formes| spk-007["Angelina Mas"]
  spk-005["Alfred Llahí"] ---|14 formes| spk-028["Jordi Mas Torres"]
  spk-007["Angelina Mas"] ---|14 formes| spk-010["Antoni Morell"]
  spk-007["Angelina Mas"] ---|14 formes| spk-018["Eudald Guillamet"]
  spk-007["Angelina Mas"] ---|14 formes| spk-026["Jordi Farràs Forné"]
  spk-007["Angelina Mas"] ---|14 formes| spk-035["Ladislau Baró Solà"]
  spk-007["Angelina Mas"] ---|14 formes| spk-037["Maria Reig Moles"]
  spk-007["Angelina Mas"] ---|14 formes| spk-048["Ramon Canut Bové"]
  spk-007["Angelina Mas"] ---|14 formes| spk-057["Teo Armengol"]
  spk-015["Enric Casadevall Medrano"] ---|14 formes| spk-039["Miquel Aleix Areny"]
  spk-015["Enric Casadevall Medrano"] ---|14 formes| spk-048["Ramon Canut Bové"]
  spk-015["Enric Casadevall Medrano"] ---|14 formes| spk-051["Rosa Maria Mandicó Alcobé"]
  spk-016["Enric Dolsa Font"] ---|14 formes| spk-028["Jordi Mas Torres"]
  spk-016["Enric Dolsa Font"] ---|14 formes| spk-037["Maria Reig Moles"]
  spk-016["Enric Dolsa Font"] ---|14 formes| spk-043["Nadia Aleix Tugas"]
  spk-016["Enric Dolsa Font"] ---|14 formes| spk-057["Teo Armengol"]
  spk-022["Guillem Areny Argelich"] ---|14 formes| spk-048["Ramon Canut Bové"]
  spk-024["Jaume Bartumeu Cassany"] ---|14 formes| spk-043["Nadia Aleix Tugas"]
  spk-024["Jaume Bartumeu Cassany"] ---|14 formes| spk-051["Rosa Maria Mandicó Alcobé"]
  spk-026["Jordi Farràs Forné"] ---|14 formes| spk-037["Maria Reig Moles"]
  spk-026["Jordi Farràs Forné"] ---|14 formes| spk-043["Nadia Aleix Tugas"]
  spk-028["Jordi Mas Torres"] ---|14 formes| spk-039["Miquel Aleix Areny"]
  spk-028["Jordi Mas Torres"] ---|14 formes| spk-043["Nadia Aleix Tugas"]
  spk-037["Maria Reig Moles"] ---|14 formes| spk-048["Ramon Canut Bové"]
  spk-037["Maria Reig Moles"] ---|14 formes| spk-051["Rosa Maria Mandicó Alcobé"]
  spk-039["Miquel Aleix Areny"] ---|14 formes| spk-043["Nadia Aleix Tugas"]
  spk-042["Mossèn Ramon de Canillo"] ---|14 formes| spk-044["Olga Adellach Coma"]
  spk-042["Mossèn Ramon de Canillo"] ---|14 formes| spk-051["Rosa Maria Mandicó Alcobé"]
  spk-002["Albert Gelabert Grau"] ---|13 formes| spk-010["Antoni Morell"]
  spk-002["Albert Gelabert Grau"] ---|13 formes| spk-016["Enric Dolsa Font"]
  spk-002["Albert Gelabert Grau"] ---|13 formes| spk-020["Gabriel Dallerès Codina"]
  spk-002["Albert Gelabert Grau"] ---|13 formes| spk-035["Ladislau Baró Solà"]
  spk-002["Albert Gelabert Grau"] ---|13 formes| spk-037["Maria Reig Moles"]
  spk-002["Albert Gelabert Grau"] ---|13 formes| spk-039["Miquel Aleix Areny"]
  spk-002["Albert Gelabert Grau"] ---|13 formes| spk-042["Mossèn Ramon de Canillo"]
  spk-003["Albert Roig"] ---|13 formes| spk-005["Alfred Llahí"]
  spk-003["Albert Roig"] ---|13 formes| spk-007["Angelina Mas"]
  spk-003["Albert Roig"] ---|13 formes| spk-035["Ladislau Baró Solà"]
  spk-003["Albert Roig"] ---|13 formes| spk-039["Miquel Aleix Areny"]
  spk-005["Alfred Llahí"] ---|13 formes| spk-022["Guillem Areny Argelich"]
  spk-005["Alfred Llahí"] ---|13 formes| spk-025["Joan Santamaria Terré"]
  spk-005["Alfred Llahí"] ---|13 formes| spk-051["Rosa Maria Mandicó Alcobé"]
  spk-007["Angelina Mas"] ---|13 formes| spk-015["Enric Casadevall Medrano"]
  spk-007["Angelina Mas"] ---|13 formes| spk-020["Gabriel Dallerès Codina"]
  spk-007["Angelina Mas"] ---|13 formes| spk-040["Miquel Armengol Pons"]
  spk-007["Angelina Mas"] ---|13 formes| spk-042["Mossèn Ramon de Canillo"]
  spk-007["Angelina Mas"] ---|13 formes| spk-043["Nadia Aleix Tugas"]
  spk-008["Antoni Armengol Vila"] ---|13 formes| spk-039["Miquel Aleix Areny"]
  spk-010["Antoni Morell"] ---|13 formes| spk-018["Eudald Guillamet"]
  spk-010["Antoni Morell"] ---|13 formes| spk-042["Mossèn Ramon de Canillo"]
  spk-015["Enric Casadevall Medrano"] ---|13 formes| spk-020["Gabriel Dallerès Codina"]
  spk-015["Enric Casadevall Medrano"] ---|13 formes| spk-027["Jordi Marquet"]
  spk-015["Enric Casadevall Medrano"] ---|13 formes| spk-035["Ladislau Baró Solà"]
  spk-015["Enric Casadevall Medrano"] ---|13 formes| spk-040["Miquel Armengol Pons"]
  spk-016["Enric Dolsa Font"] ---|13 formes| spk-018["Eudald Guillamet"]
  spk-016["Enric Dolsa Font"] ---|13 formes| spk-031["Josep Areny Fité"]
  spk-016["Enric Dolsa Font"] ---|13 formes| spk-042["Mossèn Ramon de Canillo"]
  spk-018["Eudald Guillamet"] ---|13 formes| spk-048["Ramon Canut Bové"]
  spk-020["Gabriel Dallerès Codina"] ---|13 formes| spk-024["Jaume Bartumeu Cassany"]
  spk-020["Gabriel Dallerès Codina"] ---|13 formes| spk-039["Miquel Aleix Areny"]
  spk-020["Gabriel Dallerès Codina"] ---|13 formes| spk-044["Olga Adellach Coma"]
  spk-022["Guillem Areny Argelich"] ---|13 formes| spk-026["Jordi Farràs Forné"]
  spk-022["Guillem Areny Argelich"] ---|13 formes| spk-039["Miquel Aleix Areny"]
  spk-024["Jaume Bartumeu Cassany"] ---|13 formes| spk-028["Jordi Mas Torres"]
  spk-024["Jaume Bartumeu Cassany"] ---|13 formes| spk-040["Miquel Armengol Pons"]
  spk-024["Jaume Bartumeu Cassany"] ---|13 formes| spk-057["Teo Armengol"]
  spk-026["Jordi Farràs Forné"] ---|13 formes| spk-042["Mossèn Ramon de Canillo"]
  spk-028["Jordi Mas Torres"] ---|13 formes| spk-044["Olga Adellach Coma"]
  spk-035["Ladislau Baró Solà"] ---|13 formes| spk-039["Miquel Aleix Areny"]
  spk-035["Ladislau Baró Solà"] ---|13 formes| spk-043["Nadia Aleix Tugas"]
  spk-035["Ladislau Baró Solà"] ---|13 formes| spk-051["Rosa Maria Mandicó Alcobé"]
  spk-037["Maria Reig Moles"] ---|13 formes| spk-044["Olga Adellach Coma"]
  spk-039["Miquel Aleix Areny"] ---|13 formes| spk-044["Olga Adellach Coma"]
  spk-040["Miquel Armengol Pons"] ---|13 formes| spk-044["Olga Adellach Coma"]
  spk-042["Mossèn Ramon de Canillo"] ---|13 formes| spk-048["Ramon Canut Bové"]
  spk-048["Ramon Canut Bové"] ---|13 formes| spk-057["Teo Armengol"]
  spk-001["Alan Ward"] ---|12 formes| spk-024["Jaume Bartumeu Cassany"]
  spk-002["Albert Gelabert Grau"] ---|12 formes| spk-012["Casimir Arajol"]
  spk-002["Albert Gelabert Grau"] ---|12 formes| spk-018["Eudald Guillamet"]
  spk-002["Albert Gelabert Grau"] ---|12 formes| spk-021["Gualbert Osorio"]
  spk-002["Albert Gelabert Grau"] ---|12 formes| spk-040["Miquel Armengol Pons"]
  spk-002["Albert Gelabert Grau"] ---|12 formes| spk-043["Nadia Aleix Tugas"]
  spk-002["Albert Gelabert Grau"] ---|12 formes| spk-051["Rosa Maria Mandicó Alcobé"]
  spk-002["Albert Gelabert Grau"] ---|12 formes| spk-054["Roser Jordana"]
  spk-003["Albert Roig"] ---|12 formes| spk-015["Enric Casadevall Medrano"]
  spk-003["Albert Roig"] ---|12 formes| spk-025["Joan Santamaria Terré"]
  spk-003["Albert Roig"] ---|12 formes| spk-044["Olga Adellach Coma"]
  spk-003["Albert Roig"] ---|12 formes| spk-048["Ramon Canut Bové"]
  spk-003["Albert Roig"] ---|12 formes| spk-051["Rosa Maria Mandicó Alcobé"]
  spk-005["Alfred Llahí"] ---|12 formes| spk-015["Enric Casadevall Medrano"]
  spk-005["Alfred Llahí"] ---|12 formes| spk-020["Gabriel Dallerès Codina"]
  spk-005["Alfred Llahí"] ---|12 formes| spk-035["Ladislau Baró Solà"]
  spk-005["Alfred Llahí"] ---|12 formes| spk-037["Maria Reig Moles"]
  spk-005["Alfred Llahí"] ---|12 formes| spk-043["Nadia Aleix Tugas"]
  spk-005["Alfred Llahí"] ---|12 formes| spk-044["Olga Adellach Coma"]
  spk-005["Alfred Llahí"] ---|12 formes| spk-057["Teo Armengol"]
  spk-007["Angelina Mas"] ---|12 formes| spk-008["Antoni Armengol Vila"]
  spk-007["Angelina Mas"] ---|12 formes| spk-012["Casimir Arajol"]
  spk-007["Angelina Mas"] ---|12 formes| spk-021["Gualbert Osorio"]
  spk-007["Angelina Mas"] ---|12 formes| spk-022["Guillem Areny Argelich"]
  spk-007["Angelina Mas"] ---|12 formes| spk-028["Jordi Mas Torres"]
  spk-007["Angelina Mas"] ---|12 formes| spk-030["Josep Areny"]
  spk-007["Angelina Mas"] ---|12 formes| spk-031["Josep Areny Fité"]
  spk-007["Angelina Mas"] ---|12 formes| spk-045["Patrick Pérez"]
  spk-007["Angelina Mas"] ---|12 formes| spk-054["Roser Jordana"]
  spk-008["Antoni Armengol Vila"] ---|12 formes| spk-016["Enric Dolsa Font"]
  spk-008["Antoni Armengol Vila"] ---|12 formes| spk-024["Jaume Bartumeu Cassany"]
  spk-008["Antoni Armengol Vila"] ---|12 formes| spk-026["Jordi Farràs Forné"]
  spk-008["Antoni Armengol Vila"] ---|12 formes| spk-042["Mossèn Ramon de Canillo"]
  spk-008["Antoni Armengol Vila"] ---|12 formes| spk-044["Olga Adellach Coma"]
  spk-008["Antoni Armengol Vila"] ---|12 formes| spk-051["Rosa Maria Mandicó Alcobé"]
  spk-010["Antoni Morell"] ---|12 formes| spk-012["Casimir Arajol"]
  spk-010["Antoni Morell"] ---|12 formes| spk-016["Enric Dolsa Font"]
  spk-010["Antoni Morell"] ---|12 formes| spk-020["Gabriel Dallerès Codina"]
  spk-010["Antoni Morell"] ---|12 formes| spk-021["Gualbert Osorio"]
  spk-010["Antoni Morell"] ---|12 formes| spk-039["Miquel Aleix Areny"]
  spk-010["Antoni Morell"] ---|12 formes| spk-044["Olga Adellach Coma"]
  spk-010["Antoni Morell"] ---|12 formes| spk-048["Ramon Canut Bové"]
  spk-010["Antoni Morell"] ---|12 formes| spk-051["Rosa Maria Mandicó Alcobé"]
  spk-010["Antoni Morell"] ---|12 formes| spk-054["Roser Jordana"]
  spk-012["Casimir Arajol"] ---|12 formes| spk-037["Maria Reig Moles"]
  spk-012["Casimir Arajol"] ---|12 formes| spk-044["Olga Adellach Coma"]
  spk-012["Casimir Arajol"] ---|12 formes| spk-048["Ramon Canut Bové"]
  spk-012["Casimir Arajol"] ---|12 formes| spk-051["Rosa Maria Mandicó Alcobé"]
  spk-014["Daniel Armengol"] ---|12 formes| spk-016["Enric Dolsa Font"]
  spk-014["Daniel Armengol"] ---|12 formes| spk-024["Jaume Bartumeu Cassany"]
  spk-014["Daniel Armengol"] ---|12 formes| spk-048["Ramon Canut Bové"]
  spk-015["Enric Casadevall Medrano"] ---|12 formes| spk-025["Joan Santamaria Terré"]
  spk-015["Enric Casadevall Medrano"] ---|12 formes| spk-030["Josep Areny"]
  spk-015["Enric Casadevall Medrano"] ---|12 formes| spk-042["Mossèn Ramon de Canillo"]
  spk-015["Enric Casadevall Medrano"] ---|12 formes| spk-043["Nadia Aleix Tugas"]
  spk-015["Enric Casadevall Medrano"] ---|12 formes| spk-046["Pere Altimir Pintat"]
  spk-015["Enric Casadevall Medrano"] ---|12 formes| spk-050["Robert Lizarte"]
  spk-016["Enric Dolsa Font"] ---|12 formes| spk-021["Gualbert Osorio"]
  spk-016["Enric Dolsa Font"] ---|12 formes| spk-025["Joan Santamaria Terré"]
  spk-016["Enric Dolsa Font"] ---|12 formes| spk-027["Jordi Marquet"]
  spk-016["Enric Dolsa Font"] ---|12 formes| spk-030["Josep Areny"]
  spk-016["Enric Dolsa Font"] ---|12 formes| spk-040["Miquel Armengol Pons"]
  spk-016["Enric Dolsa Font"] ---|12 formes| spk-050["Robert Lizarte"]
  spk-016["Enric Dolsa Font"] ---|12 formes| spk-054["Roser Jordana"]
  spk-018["Eudald Guillamet"] ---|12 formes| spk-024["Jaume Bartumeu Cassany"]
  spk-018["Eudald Guillamet"] ---|12 formes| spk-035["Ladislau Baró Solà"]
  spk-018["Eudald Guillamet"] ---|12 formes| spk-037["Maria Reig Moles"]
  spk-018["Eudald Guillamet"] ---|12 formes| spk-042["Mossèn Ramon de Canillo"]
  spk-018["Eudald Guillamet"] ---|12 formes| spk-044["Olga Adellach Coma"]
  spk-018["Eudald Guillamet"] ---|12 formes| spk-045["Patrick Pérez"]
  spk-018["Eudald Guillamet"] ---|12 formes| spk-054["Roser Jordana"]
  spk-019["Francina Pons"] ---|12 formes| spk-024["Jaume Bartumeu Cassany"]
  spk-019["Francina Pons"] ---|12 formes| spk-026["Jordi Farràs Forné"]
  spk-020["Gabriel Dallerès Codina"] ---|12 formes| spk-035["Ladislau Baró Solà"]
  spk-020["Gabriel Dallerès Codina"] ---|12 formes| spk-037["Maria Reig Moles"]
  spk-020["Gabriel Dallerès Codina"] ---|12 formes| spk-040["Miquel Armengol Pons"]
  spk-020["Gabriel Dallerès Codina"] ---|12 formes| spk-048["Ramon Canut Bové"]
  spk-020["Gabriel Dallerès Codina"] ---|12 formes| spk-051["Rosa Maria Mandicó Alcobé"]
  spk-021["Gualbert Osorio"] ---|12 formes| spk-042["Mossèn Ramon de Canillo"]
  spk-021["Gualbert Osorio"] ---|12 formes| spk-044["Olga Adellach Coma"]
  spk-021["Gualbert Osorio"] ---|12 formes| spk-048["Ramon Canut Bové"]
  spk-021["Gualbert Osorio"] ---|12 formes| spk-051["Rosa Maria Mandicó Alcobé"]
  spk-021["Gualbert Osorio"] ---|12 formes| spk-054["Roser Jordana"]
  spk-022["Guillem Areny Argelich"] ---|12 formes| spk-028["Jordi Mas Torres"]
  spk-022["Guillem Areny Argelich"] ---|12 formes| spk-044["Olga Adellach Coma"]
  spk-024["Jaume Bartumeu Cassany"] ---|12 formes| spk-025["Joan Santamaria Terré"]
  spk-024["Jaume Bartumeu Cassany"] ---|12 formes| spk-027["Jordi Marquet"]
  spk-024["Jaume Bartumeu Cassany"] ---|12 formes| spk-031["Josep Areny Fité"]
  spk-024["Jaume Bartumeu Cassany"] ---|12 formes| spk-042["Mossèn Ramon de Canillo"]
  spk-025["Joan Santamaria Terré"] ---|12 formes| spk-026["Jordi Farràs Forné"]
  spk-025["Joan Santamaria Terré"] ---|12 formes| spk-048["Ramon Canut Bové"]
  spk-026["Jordi Farràs Forné"] ---|12 formes| spk-057["Teo Armengol"]
  spk-027["Jordi Marquet"] ---|12 formes| spk-044["Olga Adellach Coma"]
  spk-027["Jordi Marquet"] ---|12 formes| spk-048["Ramon Canut Bové"]
  spk-027["Jordi Marquet"] ---|12 formes| spk-051["Rosa Maria Mandicó Alcobé"]
  spk-028["Jordi Mas Torres"] ---|12 formes| spk-035["Ladislau Baró Solà"]
  spk-028["Jordi Mas Torres"] ---|12 formes| spk-037["Maria Reig Moles"]
  spk-028["Jordi Mas Torres"] ---|12 formes| spk-042["Mossèn Ramon de Canillo"]
  spk-028["Jordi Mas Torres"] ---|12 formes| spk-051["Rosa Maria Mandicó Alcobé"]
  spk-028["Jordi Mas Torres"] ---|12 formes| spk-057["Teo Armengol"]
  spk-031["Josep Areny Fité"] ---|12 formes| spk-044["Olga Adellach Coma"]
  spk-035["Ladislau Baró Solà"] ---|12 formes| spk-037["Maria Reig Moles"]
  spk-035["Ladislau Baró Solà"] ---|12 formes| spk-040["Miquel Armengol Pons"]
  spk-035["Ladislau Baró Solà"] ---|12 formes| spk-042["Mossèn Ramon de Canillo"]
  spk-037["Maria Reig Moles"] ---|12 formes| spk-043["Nadia Aleix Tugas"]
  spk-039["Miquel Aleix Areny"] ---|12 formes| spk-042["Mossèn Ramon de Canillo"]
  spk-040["Miquel Armengol Pons"] ---|12 formes| spk-048["Ramon Canut Bové"]
  spk-040["Miquel Armengol Pons"] ---|12 formes| spk-051["Rosa Maria Mandicó Alcobé"]
  spk-042["Mossèn Ramon de Canillo"] ---|12 formes| spk-043["Nadia Aleix Tugas"]
  spk-042["Mossèn Ramon de Canillo"] ---|12 formes| spk-054["Roser Jordana"]
  spk-043["Nadia Aleix Tugas"] ---|12 formes| spk-044["Olga Adellach Coma"]
  spk-043["Nadia Aleix Tugas"] ---|12 formes| spk-051["Rosa Maria Mandicó Alcobé"]
  spk-043["Nadia Aleix Tugas"] ---|12 formes| spk-057["Teo Armengol"]
  spk-044["Olga Adellach Coma"] ---|12 formes| spk-045["Patrick Pérez"]
  spk-044["Olga Adellach Coma"] ---|12 formes| spk-054["Roser Jordana"]
  spk-044["Olga Adellach Coma"] ---|12 formes| spk-057["Teo Armengol"]
  spk-045["Patrick Pérez"] ---|12 formes| spk-048["Ramon Canut Bové"]
  spk-048["Ramon Canut Bové"] ---|12 formes| spk-054["Roser Jordana"]
  spk-051["Rosa Maria Mandicó Alcobé"] ---|12 formes| spk-054["Roser Jordana"]
  spk-001["Alan Ward"] ---|11 formes| spk-016["Enric Dolsa Font"]
  spk-001["Alan Ward"] ---|11 formes| spk-057["Teo Armengol"]
  spk-002["Albert Gelabert Grau"] ---|11 formes| spk-005["Alfred Llahí"]
  spk-002["Albert Gelabert Grau"] ---|11 formes| spk-014["Daniel Armengol"]
  spk-002["Albert Gelabert Grau"] ---|11 formes| spk-028["Jordi Mas Torres"]
  spk-002["Albert Gelabert Grau"] ---|11 formes| spk-045["Patrick Pérez"]
  spk-002["Albert Gelabert Grau"] ---|11 formes| spk-046["Pere Altimir Pintat"]
  spk-003["Albert Roig"] ---|11 formes| spk-008["Antoni Armengol Vila"]
  spk-003["Albert Roig"] ---|11 formes| spk-019["Francina Pons"]
  spk-003["Albert Roig"] ---|11 formes| spk-020["Gabriel Dallerès Codina"]
  spk-003["Albert Roig"] ---|11 formes| spk-028["Jordi Mas Torres"]
  spk-003["Albert Roig"] ---|11 formes| spk-042["Mossèn Ramon de Canillo"]
  spk-003["Albert Roig"] ---|11 formes| spk-057["Teo Armengol"]
  spk-005["Alfred Llahí"] ---|11 formes| spk-030["Josep Areny"]
  spk-005["Alfred Llahí"] ---|11 formes| spk-040["Miquel Armengol Pons"]
  spk-005["Alfred Llahí"] ---|11 formes| spk-050["Robert Lizarte"]
  spk-006["Andreu Gaspà Picart"] ---|11 formes| spk-016["Enric Dolsa Font"]
  spk-007["Angelina Mas"] ---|11 formes| spk-009["Antoni Jordi Areny"]
  spk-007["Angelina Mas"] ---|11 formes| spk-027["Jordi Marquet"]
  spk-007["Angelina Mas"] ---|11 formes| spk-034["Josep Marsal Riba"]
  spk-007["Angelina Mas"] ---|11 formes| spk-046["Pere Altimir Pintat"]
  spk-007["Angelina Mas"] ---|11 formes| spk-053["Roser Bastida"]
  spk-008["Antoni Armengol Vila"] ---|11 formes| spk-015["Enric Casadevall Medrano"]
  spk-008["Antoni Armengol Vila"] ---|11 formes| spk-035["Ladislau Baró Solà"]
  spk-008["Antoni Armengol Vila"] ---|11 formes| spk-037["Maria Reig Moles"]
  spk-008["Antoni Armengol Vila"] ---|11 formes| spk-048["Ramon Canut Bové"]
  spk-009["Antoni Jordi Areny"] ---|11 formes| spk-039["Miquel Aleix Areny"]
  spk-010["Antoni Morell"] ---|11 formes| spk-024["Jaume Bartumeu Cassany"]
  spk-010["Antoni Morell"] ---|11 formes| spk-035["Ladislau Baró Solà"]
  spk-010["Antoni Morell"] ---|11 formes| spk-037["Maria Reig Moles"]
  spk-010["Antoni Morell"] ---|11 formes| spk-040["Miquel Armengol Pons"]
  spk-010["Antoni Morell"] ---|11 formes| spk-045["Patrick Pérez"]
  spk-011["Carles Sasplugas"] ---|11 formes| spk-026["Jordi Farràs Forné"]
  spk-011["Carles Sasplugas"] ---|11 formes| spk-035["Ladislau Baró Solà"]
  spk-012["Casimir Arajol"] ---|11 formes| spk-015["Enric Casadevall Medrano"]
  spk-012["Casimir Arajol"] ---|11 formes| spk-016["Enric Dolsa Font"]
  spk-012["Casimir Arajol"] ---|11 formes| spk-018["Eudald Guillamet"]
  spk-012["Casimir Arajol"] ---|11 formes| spk-020["Gabriel Dallerès Codina"]
  spk-012["Casimir Arajol"] ---|11 formes| spk-021["Gualbert Osorio"]
  spk-012["Casimir Arajol"] ---|11 formes| spk-024["Jaume Bartumeu Cassany"]
  spk-012["Casimir Arajol"] ---|11 formes| spk-026["Jordi Farràs Forné"]
  spk-012["Casimir Arajol"] ---|11 formes| spk-035["Ladislau Baró Solà"]
  spk-012["Casimir Arajol"] ---|11 formes| spk-039["Miquel Aleix Areny"]
  spk-012["Casimir Arajol"] ---|11 formes| spk-040["Miquel Armengol Pons"]
  spk-012["Casimir Arajol"] ---|11 formes| spk-042["Mossèn Ramon de Canillo"]
  spk-012["Casimir Arajol"] ---|11 formes| spk-045["Patrick Pérez"]
  spk-012["Casimir Arajol"] ---|11 formes| spk-054["Roser Jordana"]
  spk-014["Daniel Armengol"] ---|11 formes| spk-015["Enric Casadevall Medrano"]
  spk-014["Daniel Armengol"] ---|11 formes| spk-026["Jordi Farràs Forné"]
  spk-014["Daniel Armengol"] ---|11 formes| spk-035["Ladislau Baró Solà"]
  spk-014["Daniel Armengol"] ---|11 formes| spk-044["Olga Adellach Coma"]
  spk-014["Daniel Armengol"] ---|11 formes| spk-051["Rosa Maria Mandicó Alcobé"]
  spk-015["Enric Casadevall Medrano"] ---|11 formes| spk-022["Guillem Areny Argelich"]
  spk-015["Enric Casadevall Medrano"] ---|11 formes| spk-028["Jordi Mas Torres"]
  spk-015["Enric Casadevall Medrano"] ---|11 formes| spk-031["Josep Areny Fité"]
  spk-016["Enric Dolsa Font"] ---|11 formes| spk-019["Francina Pons"]
  spk-016["Enric Dolsa Font"] ---|11 formes| spk-020["Gabriel Dallerès Codina"]
  spk-016["Enric Dolsa Font"] ---|11 formes| spk-022["Guillem Areny Argelich"]
  spk-016["Enric Dolsa Font"] ---|11 formes| spk-036["Ludmilla Lacueva"]
  spk-016["Enric Dolsa Font"] ---|11 formes| spk-038["Mercè Segura"]
  spk-016["Enric Dolsa Font"] ---|11 formes| spk-045["Patrick Pérez"]
  spk-017["Esther Jover"] ---|11 formes| spk-024["Jaume Bartumeu Cassany"]
  spk-018["Eudald Guillamet"] ---|11 formes| spk-021["Gualbert Osorio"]
  spk-018["Eudald Guillamet"] ---|11 formes| spk-026["Jordi Farràs Forné"]
  spk-018["Eudald Guillamet"] ---|11 formes| spk-028["Jordi Mas Torres"]
  spk-018["Eudald Guillamet"] ---|11 formes| spk-039["Miquel Aleix Areny"]
  spk-018["Eudald Guillamet"] ---|11 formes| spk-040["Miquel Armengol Pons"]
  spk-018["Eudald Guillamet"] ---|11 formes| spk-043["Nadia Aleix Tugas"]
  spk-018["Eudald Guillamet"] ---|11 formes| spk-051["Rosa Maria Mandicó Alcobé"]
  spk-018["Eudald Guillamet"] ---|11 formes| spk-057["Teo Armengol"]
  spk-020["Gabriel Dallerès Codina"] ---|11 formes| spk-026["Jordi Farràs Forné"]
  spk-020["Gabriel Dallerès Codina"] ---|11 formes| spk-042["Mossèn Ramon de Canillo"]
  spk-020["Gabriel Dallerès Codina"] ---|11 formes| spk-046["Pere Altimir Pintat"]
  spk-021["Gualbert Osorio"] ---|11 formes| spk-024["Jaume Bartumeu Cassany"]
  spk-021["Gualbert Osorio"] ---|11 formes| spk-035["Ladislau Baró Solà"]
  spk-022["Guillem Areny Argelich"] ---|11 formes| spk-025["Joan Santamaria Terré"]
  spk-022["Guillem Areny Argelich"] ---|11 formes| spk-037["Maria Reig Moles"]
  spk-022["Guillem Areny Argelich"] ---|11 formes| spk-043["Nadia Aleix Tugas"]
  spk-022["Guillem Areny Argelich"] ---|11 formes| spk-051["Rosa Maria Mandicó Alcobé"]
  spk-024["Jaume Bartumeu Cassany"] ---|11 formes| spk-030["Josep Areny"]
  spk-024["Jaume Bartumeu Cassany"] ---|11 formes| spk-034["Josep Marsal Riba"]
  spk-024["Jaume Bartumeu Cassany"] ---|11 formes| spk-036["Ludmilla Lacueva"]
  spk-024["Jaume Bartumeu Cassany"] ---|11 formes| spk-046["Pere Altimir Pintat"]
  spk-024["Jaume Bartumeu Cassany"] ---|11 formes| spk-050["Robert Lizarte"]
  spk-024["Jaume Bartumeu Cassany"] ---|11 formes| spk-054["Roser Jordana"]
  spk-025["Joan Santamaria Terré"] ---|11 formes| spk-027["Jordi Marquet"]
  spk-025["Joan Santamaria Terré"] ---|11 formes| spk-028["Jordi Mas Torres"]
  spk-025["Joan Santamaria Terré"] ---|11 formes| spk-039["Miquel Aleix Areny"]
  spk-025["Joan Santamaria Terré"] ---|11 formes| spk-044["Olga Adellach Coma"]
  spk-025["Joan Santamaria Terré"] ---|11 formes| spk-050["Robert Lizarte"]
  spk-025["Joan Santamaria Terré"] ---|11 formes| spk-051["Rosa Maria Mandicó Alcobé"]
  spk-026["Jordi Farràs Forné"] ---|11 formes| spk-031["Josep Areny Fité"]
  spk-026["Jordi Farràs Forné"] ---|11 formes| spk-040["Miquel Armengol Pons"]
  spk-026["Jordi Farràs Forné"] ---|11 formes| spk-050["Robert Lizarte"]
  spk-027["Jordi Marquet"] ---|11 formes| spk-030["Josep Areny"]
  spk-027["Jordi Marquet"] ---|11 formes| spk-040["Miquel Armengol Pons"]
  spk-028["Jordi Mas Torres"] ---|11 formes| spk-050["Robert Lizarte"]
  spk-030["Josep Areny"] ---|11 formes| spk-040["Miquel Armengol Pons"]
  spk-030["Josep Areny"] ---|11 formes| spk-044["Olga Adellach Coma"]
  spk-030["Josep Areny"] ---|11 formes| spk-048["Ramon Canut Bové"]
  spk-030["Josep Areny"] ---|11 formes| spk-051["Rosa Maria Mandicó Alcobé"]
  spk-031["Josep Areny Fité"] ---|11 formes| spk-039["Miquel Aleix Areny"]
  spk-031["Josep Areny Fité"] ---|11 formes| spk-048["Ramon Canut Bové"]
  spk-031["Josep Areny Fité"] ---|11 formes| spk-051["Rosa Maria Mandicó Alcobé"]
  spk-034["Josep Marsal Riba"] ---|11 formes| spk-039["Miquel Aleix Areny"]
  spk-035["Ladislau Baró Solà"] ---|11 formes| spk-045["Patrick Pérez"]
  spk-035["Ladislau Baró Solà"] ---|11 formes| spk-046["Pere Altimir Pintat"]
  spk-035["Ladislau Baró Solà"] ---|11 formes| spk-054["Roser Jordana"]
  spk-035["Ladislau Baró Solà"] ---|11 formes| spk-057["Teo Armengol"]
  spk-036["Ludmilla Lacueva"] ---|11 formes| spk-048["Ramon Canut Bové"]
  spk-036["Ludmilla Lacueva"] ---|11 formes| spk-050["Robert Lizarte"]
  spk-037["Maria Reig Moles"] ---|11 formes| spk-040["Miquel Armengol Pons"]
  spk-037["Maria Reig Moles"] ---|11 formes| spk-042["Mossèn Ramon de Canillo"]
  spk-037["Maria Reig Moles"] ---|11 formes| spk-045["Patrick Pérez"]
  spk-037["Maria Reig Moles"] ---|11 formes| spk-054["Roser Jordana"]
  spk-038["Mercè Segura"] ---|11 formes| spk-044["Olga Adellach Coma"]
  spk-038["Mercè Segura"] ---|11 formes| spk-048["Ramon Canut Bové"]
  spk-039["Miquel Aleix Areny"] ---|11 formes| spk-040["Miquel Armengol Pons"]
  spk-039["Miquel Aleix Areny"] ---|11 formes| spk-041["Miquel Naudi Casal"]
  spk-039["Miquel Aleix Areny"] ---|11 formes| spk-046["Pere Altimir Pintat"]
  spk-039["Miquel Aleix Areny"] ---|11 formes| spk-057["Teo Armengol"]
  spk-040["Miquel Armengol Pons"] ---|11 formes| spk-042["Mossèn Ramon de Canillo"]
  spk-040["Miquel Armengol Pons"] ---|11 formes| spk-045["Patrick Pérez"]
  spk-041["Miquel Naudi Casal"] ---|11 formes| spk-051["Rosa Maria Mandicó Alcobé"]
  spk-042["Mossèn Ramon de Canillo"] ---|11 formes| spk-057["Teo Armengol"]
  spk-044["Olga Adellach Coma"] ---|11 formes| spk-046["Pere Altimir Pintat"]
  spk-044["Olga Adellach Coma"] ---|11 formes| spk-050["Robert Lizarte"]
  spk-045["Patrick Pérez"] ---|11 formes| spk-051["Rosa Maria Mandicó Alcobé"]
  spk-045["Patrick Pérez"] ---|11 formes| spk-054["Roser Jordana"]
  spk-046["Pere Altimir Pintat"] ---|11 formes| spk-048["Ramon Canut Bové"]
  spk-046["Pere Altimir Pintat"] ---|11 formes| spk-051["Rosa Maria Mandicó Alcobé"]
  spk-048["Ramon Canut Bové"] ---|11 formes| spk-050["Robert Lizarte"]
  spk-050["Robert Lizarte"] ---|11 formes| spk-051["Rosa Maria Mandicó Alcobé"]
  spk-050["Robert Lizarte"] ---|11 formes| spk-057["Teo Armengol"]
  spk-001["Alan Ward"] ---|10 formes| spk-003["Albert Roig"]
  spk-001["Alan Ward"] ---|10 formes| spk-005["Alfred Llahí"]
  spk-001["Alan Ward"] ---|10 formes| spk-007["Angelina Mas"]
  spk-001["Alan Ward"] ---|10 formes| spk-015["Enric Casadevall Medrano"]
  spk-001["Alan Ward"] ---|10 formes| spk-035["Ladislau Baró Solà"]
  spk-001["Alan Ward"] ---|10 formes| spk-048["Ramon Canut Bové"]
  spk-001["Alan Ward"] ---|10 formes| spk-050["Robert Lizarte"]
  spk-002["Albert Gelabert Grau"] ---|10 formes| spk-003["Albert Roig"]
  spk-002["Albert Gelabert Grau"] ---|10 formes| spk-008["Antoni Armengol Vila"]
  spk-002["Albert Gelabert Grau"] ---|10 formes| spk-022["Guillem Areny Argelich"]
  spk-002["Albert Gelabert Grau"] ---|10 formes| spk-027["Jordi Marquet"]
  spk-002["Albert Gelabert Grau"] ---|10 formes| spk-030["Josep Areny"]
  spk-002["Albert Gelabert Grau"] ---|10 formes| spk-031["Josep Areny Fité"]
  spk-002["Albert Gelabert Grau"] ---|10 formes| spk-038["Mercè Segura"]
  spk-002["Albert Gelabert Grau"] ---|10 formes| spk-053["Roser Bastida"]
  spk-002["Albert Gelabert Grau"] ---|10 formes| spk-057["Teo Armengol"]
  spk-002["Albert Gelabert Grau"] ---|10 formes| spk-060["Àngels Mach"]
  spk-003["Albert Roig"] ---|10 formes| spk-017["Esther Jover"]
  spk-003["Albert Roig"] ---|10 formes| spk-022["Guillem Areny Argelich"]
  spk-003["Albert Roig"] ---|10 formes| spk-031["Josep Areny Fité"]
  spk-003["Albert Roig"] ---|10 formes| spk-034["Josep Marsal Riba"]
  spk-003["Albert Roig"] ---|10 formes| spk-037["Maria Reig Moles"]
  spk-003["Albert Roig"] ---|10 formes| spk-040["Miquel Armengol Pons"]
  spk-003["Albert Roig"] ---|10 formes| spk-043["Nadia Aleix Tugas"]
  spk-003["Albert Roig"] ---|10 formes| spk-050["Robert Lizarte"]
  spk-005["Alfred Llahí"] ---|10 formes| spk-008["Antoni Armengol Vila"]
  spk-005["Alfred Llahí"] ---|10 formes| spk-010["Antoni Morell"]
  spk-005["Alfred Llahí"] ---|10 formes| spk-014["Daniel Armengol"]
  spk-005["Alfred Llahí"] ---|10 formes| spk-018["Eudald Guillamet"]
  spk-005["Alfred Llahí"] ---|10 formes| spk-027["Jordi Marquet"]
  spk-005["Alfred Llahí"] ---|10 formes| spk-031["Josep Areny Fité"]
  spk-005["Alfred Llahí"] ---|10 formes| spk-034["Josep Marsal Riba"]
  spk-005["Alfred Llahí"] ---|10 formes| spk-042["Mossèn Ramon de Canillo"]
  spk-005["Alfred Llahí"] ---|10 formes| spk-046["Pere Altimir Pintat"]
  spk-006["Andreu Gaspà Picart"] ---|10 formes| spk-007["Angelina Mas"]
  spk-006["Andreu Gaspà Picart"] ---|10 formes| spk-010["Antoni Morell"]
  spk-006["Andreu Gaspà Picart"] ---|10 formes| spk-018["Eudald Guillamet"]
  spk-006["Andreu Gaspà Picart"] ---|10 formes| spk-024["Jaume Bartumeu Cassany"]
  spk-006["Andreu Gaspà Picart"] ---|10 formes| spk-044["Olga Adellach Coma"]
  spk-006["Andreu Gaspà Picart"] ---|10 formes| spk-048["Ramon Canut Bové"]
  spk-006["Andreu Gaspà Picart"] ---|10 formes| spk-054["Roser Jordana"]
  spk-007["Angelina Mas"] ---|10 formes| spk-014["Daniel Armengol"]
  spk-007["Angelina Mas"] ---|10 formes| spk-019["Francina Pons"]
  spk-007["Angelina Mas"] ---|10 formes| spk-025["Joan Santamaria Terré"]
  spk-007["Angelina Mas"] ---|10 formes| spk-038["Mercè Segura"]
  spk-007["Angelina Mas"] ---|10 formes| spk-041["Miquel Naudi Casal"]
  spk-007["Angelina Mas"] ---|10 formes| spk-050["Robert Lizarte"]
  spk-008["Antoni Armengol Vila"] ---|10 formes| spk-009["Antoni Jordi Areny"]
  spk-008["Antoni Armengol Vila"] ---|10 formes| spk-010["Antoni Morell"]
  spk-008["Antoni Armengol Vila"] ---|10 formes| spk-020["Gabriel Dallerès Codina"]
  spk-008["Antoni Armengol Vila"] ---|10 formes| spk-021["Gualbert Osorio"]
  spk-008["Antoni Armengol Vila"] ---|10 formes| spk-028["Jordi Mas Torres"]
  spk-008["Antoni Armengol Vila"] ---|10 formes| spk-031["Josep Areny Fité"]
  spk-008["Antoni Armengol Vila"] ---|10 formes| spk-040["Miquel Armengol Pons"]
  spk-009["Antoni Jordi Areny"] ---|10 formes| spk-015["Enric Casadevall Medrano"]
  spk-009["Antoni Jordi Areny"] ---|10 formes| spk-024["Jaume Bartumeu Cassany"]
  spk-009["Antoni Jordi Areny"] ---|10 formes| spk-026["Jordi Farràs Forné"]
  spk-009["Antoni Jordi Areny"] ---|10 formes| spk-035["Ladislau Baró Solà"]
  spk-009["Antoni Jordi Areny"] ---|10 formes| spk-037["Maria Reig Moles"]
  spk-009["Antoni Jordi Areny"] ---|10 formes| spk-044["Olga Adellach Coma"]
  spk-009["Antoni Jordi Areny"] ---|10 formes| spk-051["Rosa Maria Mandicó Alcobé"]
  spk-010["Antoni Morell"] ---|10 formes| spk-015["Enric Casadevall Medrano"]
  spk-010["Antoni Morell"] ---|10 formes| spk-026["Jordi Farràs Forné"]
  spk-010["Antoni Morell"] ---|10 formes| spk-030["Josep Areny"]
  spk-010["Antoni Morell"] ---|10 formes| spk-031["Josep Areny Fité"]
  spk-010["Antoni Morell"] ---|10 formes| spk-043["Nadia Aleix Tugas"]
  spk-010["Antoni Morell"] ---|10 formes| spk-057["Teo Armengol"]
  spk-011["Carles Sasplugas"] ---|10 formes| spk-048["Ramon Canut Bové"]
  spk-012["Casimir Arajol"] ---|10 formes| spk-014["Daniel Armengol"]
  spk-012["Casimir Arajol"] ---|10 formes| spk-043["Nadia Aleix Tugas"]
  spk-014["Daniel Armengol"] ---|10 formes| spk-027["Jordi Marquet"]
  spk-014["Daniel Armengol"] ---|10 formes| spk-040["Miquel Armengol Pons"]
  spk-014["Daniel Armengol"] ---|10 formes| spk-057["Teo Armengol"]
  spk-015["Enric Casadevall Medrano"] ---|10 formes| spk-018["Eudald Guillamet"]
  spk-015["Enric Casadevall Medrano"] ---|10 formes| spk-019["Francina Pons"]
  spk-015["Enric Casadevall Medrano"] ---|10 formes| spk-021["Gualbert Osorio"]
  spk-015["Enric Casadevall Medrano"] ---|10 formes| spk-036["Ludmilla Lacueva"]
  spk-015["Enric Casadevall Medrano"] ---|10 formes| spk-038["Mercè Segura"]
  spk-015["Enric Casadevall Medrano"] ---|10 formes| spk-041["Miquel Naudi Casal"]
  spk-015["Enric Casadevall Medrano"] ---|10 formes| spk-045["Patrick Pérez"]
  spk-015["Enric Casadevall Medrano"] ---|10 formes| spk-054["Roser Jordana"]
  spk-015["Enric Casadevall Medrano"] ---|10 formes| spk-057["Teo Armengol"]
  spk-015["Enric Casadevall Medrano"] ---|10 formes| spk-059["Xavier Planas"]
  spk-016["Enric Dolsa Font"] ---|10 formes| spk-017["Esther Jover"]
  spk-016["Enric Dolsa Font"] ---|10 formes| spk-033["Josep Garrallà Rossell"]
  spk-016["Enric Dolsa Font"] ---|10 formes| spk-034["Josep Marsal Riba"]
  spk-016["Enric Dolsa Font"] ---|10 formes| spk-046["Pere Altimir Pintat"]
  spk-017["Esther Jover"] ---|10 formes| spk-044["Olga Adellach Coma"]
  spk-018["Eudald Guillamet"] ---|10 formes| spk-020["Gabriel Dallerès Codina"]
  spk-018["Eudald Guillamet"] ---|10 formes| spk-022["Guillem Areny Argelich"]
  spk-018["Eudald Guillamet"] ---|10 formes| spk-030["Josep Areny"]
  spk-018["Eudald Guillamet"] ---|10 formes| spk-031["Josep Areny Fité"]
  spk-019["Francina Pons"] ---|10 formes| spk-022["Guillem Areny Argelich"]
  spk-019["Francina Pons"] ---|10 formes| spk-028["Jordi Mas Torres"]
  spk-019["Francina Pons"] ---|10 formes| spk-035["Ladislau Baró Solà"]
  spk-019["Francina Pons"] ---|10 formes| spk-044["Olga Adellach Coma"]
  spk-019["Francina Pons"] ---|10 formes| spk-048["Ramon Canut Bové"]
  spk-020["Gabriel Dallerès Codina"] ---|10 formes| spk-021["Gualbert Osorio"]
  spk-020["Gabriel Dallerès Codina"] ---|10 formes| spk-022["Guillem Areny Argelich"]
  spk-020["Gabriel Dallerès Codina"] ---|10 formes| spk-030["Josep Areny"]
  spk-020["Gabriel Dallerès Codina"] ---|10 formes| spk-045["Patrick Pérez"]
  spk-020["Gabriel Dallerès Codina"] ---|10 formes| spk-054["Roser Jordana"]
  spk-021["Gualbert Osorio"] ---|10 formes| spk-026["Jordi Farràs Forné"]
  spk-021["Gualbert Osorio"] ---|10 formes| spk-037["Maria Reig Moles"]
  spk-021["Gualbert Osorio"] ---|10 formes| spk-039["Miquel Aleix Areny"]
  spk-021["Gualbert Osorio"] ---|10 formes| spk-040["Miquel Armengol Pons"]
  spk-021["Gualbert Osorio"] ---|10 formes| spk-043["Nadia Aleix Tugas"]
  spk-021["Gualbert Osorio"] ---|10 formes| spk-045["Patrick Pérez"]
  spk-022["Guillem Areny Argelich"] ---|10 formes| spk-046["Pere Altimir Pintat"]
  spk-022["Guillem Areny Argelich"] ---|10 formes| spk-057["Teo Armengol"]
  spk-024["Jaume Bartumeu Cassany"] ---|10 formes| spk-033["Josep Garrallà Rossell"]
  spk-024["Jaume Bartumeu Cassany"] ---|10 formes| spk-038["Mercè Segura"]
  spk-024["Jaume Bartumeu Cassany"] ---|10 formes| spk-045["Patrick Pérez"]
  spk-024["Jaume Bartumeu Cassany"] ---|10 formes| spk-059["Xavier Planas"]
  spk-025["Joan Santamaria Terré"] ---|10 formes| spk-030["Josep Areny"]
  spk-025["Joan Santamaria Terré"] ---|10 formes| spk-035["Ladislau Baró Solà"]
  spk-025["Joan Santamaria Terré"] ---|10 formes| spk-043["Nadia Aleix Tugas"]
  spk-025["Joan Santamaria Terré"] ---|10 formes| spk-046["Pere Altimir Pintat"]
  spk-026["Jordi Farràs Forné"] ---|10 formes| spk-027["Jordi Marquet"]
  spk-026["Jordi Farràs Forné"] ---|10 formes| spk-034["Josep Marsal Riba"]
  spk-026["Jordi Farràs Forné"] ---|10 formes| spk-036["Ludmilla Lacueva"]
  spk-026["Jordi Farràs Forné"] ---|10 formes| spk-038["Mercè Segura"]
  spk-026["Jordi Farràs Forné"] ---|10 formes| spk-045["Patrick Pérez"]
  spk-026["Jordi Farràs Forné"] ---|10 formes| spk-046["Pere Altimir Pintat"]
  spk-026["Jordi Farràs Forné"] ---|10 formes| spk-054["Roser Jordana"]
  spk-027["Jordi Marquet"] ---|10 formes| spk-031["Josep Areny Fité"]
  spk-027["Jordi Marquet"] ---|10 formes| spk-035["Ladislau Baró Solà"]
  spk-027["Jordi Marquet"] ---|10 formes| spk-037["Maria Reig Moles"]
  spk-027["Jordi Marquet"] ---|10 formes| spk-039["Miquel Aleix Areny"]
  spk-027["Jordi Marquet"] ---|10 formes| spk-042["Mossèn Ramon de Canillo"]
  spk-027["Jordi Marquet"] ---|10 formes| spk-043["Nadia Aleix Tugas"]
  spk-027["Jordi Marquet"] ---|10 formes| spk-046["Pere Altimir Pintat"]
  spk-027["Jordi Marquet"] ---|10 formes| spk-050["Robert Lizarte"]
  spk-028["Jordi Mas Torres"] ---|10 formes| spk-036["Ludmilla Lacueva"]
  spk-028["Jordi Mas Torres"] ---|10 formes| spk-038["Mercè Segura"]
  spk-028["Jordi Mas Torres"] ---|10 formes| spk-045["Patrick Pérez"]
  spk-028["Jordi Mas Torres"] ---|10 formes| spk-054["Roser Jordana"]
  spk-030["Josep Areny"] ---|10 formes| spk-031["Josep Areny Fité"]
  spk-030["Josep Areny"] ---|10 formes| spk-035["Ladislau Baró Solà"]
  spk-030["Josep Areny"] ---|10 formes| spk-037["Maria Reig Moles"]
  spk-030["Josep Areny"] ---|10 formes| spk-039["Miquel Aleix Areny"]
  spk-030["Josep Areny"] ---|10 formes| spk-042["Mossèn Ramon de Canillo"]
  spk-030["Josep Areny"] ---|10 formes| spk-046["Pere Altimir Pintat"]
  spk-031["Josep Areny Fité"] ---|10 formes| spk-035["Ladislau Baró Solà"]
  spk-031["Josep Areny Fité"] ---|10 formes| spk-037["Maria Reig Moles"]
  spk-031["Josep Areny Fité"] ---|10 formes| spk-040["Miquel Armengol Pons"]
  spk-031["Josep Areny Fité"] ---|10 formes| spk-042["Mossèn Ramon de Canillo"]
  spk-033["Josep Garrallà Rossell"] ---|10 formes| spk-042["Mossèn Ramon de Canillo"]
  spk-034["Josep Marsal Riba"] ---|10 formes| spk-035["Ladislau Baró Solà"]
  spk-035["Ladislau Baró Solà"] ---|10 formes| spk-038["Mercè Segura"]
  spk-035["Ladislau Baró Solà"] ---|10 formes| spk-050["Robert Lizarte"]
  spk-036["Ludmilla Lacueva"] ---|10 formes| spk-039["Miquel Aleix Areny"]
  spk-036["Ludmilla Lacueva"] ---|10 formes| spk-044["Olga Adellach Coma"]
  spk-037["Maria Reig Moles"] ---|10 formes| spk-041["Miquel Naudi Casal"]
  spk-037["Maria Reig Moles"] ---|10 formes| spk-046["Pere Altimir Pintat"]
  spk-038["Mercè Segura"] ---|10 formes| spk-040["Miquel Armengol Pons"]
  spk-038["Mercè Segura"] ---|10 formes| spk-042["Mossèn Ramon de Canillo"]
  spk-038["Mercè Segura"] ---|10 formes| spk-043["Nadia Aleix Tugas"]
  spk-038["Mercè Segura"] ---|10 formes| spk-051["Rosa Maria Mandicó Alcobé"]
  spk-039["Miquel Aleix Areny"] ---|10 formes| spk-045["Patrick Pérez"]
  spk-039["Miquel Aleix Areny"] ---|10 formes| spk-050["Robert Lizarte"]
  spk-039["Miquel Aleix Areny"] ---|10 formes| spk-054["Roser Jordana"]
  spk-040["Miquel Armengol Pons"] ---|10 formes| spk-043["Nadia Aleix Tugas"]
  spk-040["Miquel Armengol Pons"] ---|10 formes| spk-046["Pere Altimir Pintat"]
  spk-040["Miquel Armengol Pons"] ---|10 formes| spk-054["Roser Jordana"]
  spk-040["Miquel Armengol Pons"] ---|10 formes| spk-057["Teo Armengol"]
  spk-042["Mossèn Ramon de Canillo"] ---|10 formes| spk-045["Patrick Pérez"]
  spk-042["Mossèn Ramon de Canillo"] ---|10 formes| spk-050["Robert Lizarte"]
  spk-043["Nadia Aleix Tugas"] ---|10 formes| spk-045["Patrick Pérez"]
  spk-043["Nadia Aleix Tugas"] ---|10 formes| spk-046["Pere Altimir Pintat"]
  spk-043["Nadia Aleix Tugas"] ---|10 formes| spk-050["Robert Lizarte"]
  spk-043["Nadia Aleix Tugas"] ---|10 formes| spk-054["Roser Jordana"]
  spk-051["Rosa Maria Mandicó Alcobé"] ---|10 formes| spk-057["Teo Armengol"]
  spk-001["Alan Ward"] ---|9 formes| spk-018["Eudald Guillamet"]
  spk-001["Alan Ward"] ---|9 formes| spk-020["Gabriel Dallerès Codina"]
  spk-001["Alan Ward"] ---|9 formes| spk-026["Jordi Farràs Forné"]
  spk-001["Alan Ward"] ---|9 formes| spk-028["Jordi Mas Torres"]
  spk-001["Alan Ward"] ---|9 formes| spk-030["Josep Areny"]
  spk-001["Alan Ward"] ---|9 formes| spk-040["Miquel Armengol Pons"]
  spk-001["Alan Ward"] ---|9 formes| spk-043["Nadia Aleix Tugas"]
  spk-001["Alan Ward"] ---|9 formes| spk-044["Olga Adellach Coma"]
  spk-002["Albert Gelabert Grau"] ---|9 formes| spk-006["Andreu Gaspà Picart"]
  spk-002["Albert Gelabert Grau"] ---|9 formes| spk-011["Carles Sasplugas"]
  spk-002["Albert Gelabert Grau"] ---|9 formes| spk-017["Esther Jover"]
  spk-003["Albert Roig"] ---|9 formes| spk-006["Andreu Gaspà Picart"]
  spk-003["Albert Roig"] ---|9 formes| spk-009["Antoni Jordi Areny"]
  spk-003["Albert Roig"] ---|9 formes| spk-010["Antoni Morell"]
  spk-003["Albert Roig"] ---|9 formes| spk-018["Eudald Guillamet"]
  spk-003["Albert Roig"] ---|9 formes| spk-021["Gualbert Osorio"]
  spk-003["Albert Roig"] ---|9 formes| spk-027["Jordi Marquet"]
  spk-003["Albert Roig"] ---|9 formes| spk-030["Josep Areny"]
  spk-003["Albert Roig"] ---|9 formes| spk-036["Ludmilla Lacueva"]
  spk-003["Albert Roig"] ---|9 formes| spk-046["Pere Altimir Pintat"]
  spk-003["Albert Roig"] ---|9 formes| spk-054["Roser Jordana"]
  spk-003["Albert Roig"] ---|9 formes| spk-059["Xavier Planas"]
  spk-005["Alfred Llahí"] ---|9 formes| spk-006["Andreu Gaspà Picart"]
  spk-005["Alfred Llahí"] ---|9 formes| spk-012["Casimir Arajol"]
  spk-005["Alfred Llahí"] ---|9 formes| spk-019["Francina Pons"]
  spk-005["Alfred Llahí"] ---|9 formes| spk-036["Ludmilla Lacueva"]
  spk-005["Alfred Llahí"] ---|9 formes| spk-038["Mercè Segura"]
  spk-005["Alfred Llahí"] ---|9 formes| spk-041["Miquel Naudi Casal"]
  spk-005["Alfred Llahí"] ---|9 formes| spk-045["Patrick Pérez"]
  spk-006["Andreu Gaspà Picart"] ---|9 formes| spk-012["Casimir Arajol"]
  spk-006["Andreu Gaspà Picart"] ---|9 formes| spk-015["Enric Casadevall Medrano"]
  spk-006["Andreu Gaspà Picart"] ---|9 formes| spk-020["Gabriel Dallerès Codina"]
  spk-006["Andreu Gaspà Picart"] ---|9 formes| spk-021["Gualbert Osorio"]
  spk-006["Andreu Gaspà Picart"] ---|9 formes| spk-026["Jordi Farràs Forné"]
  spk-006["Andreu Gaspà Picart"] ---|9 formes| spk-028["Jordi Mas Torres"]
  spk-006["Andreu Gaspà Picart"] ---|9 formes| spk-031["Josep Areny Fité"]
  spk-006["Andreu Gaspà Picart"] ---|9 formes| spk-037["Maria Reig Moles"]
  spk-006["Andreu Gaspà Picart"] ---|9 formes| spk-039["Miquel Aleix Areny"]
  spk-006["Andreu Gaspà Picart"] ---|9 formes| spk-040["Miquel Armengol Pons"]
  spk-006["Andreu Gaspà Picart"] ---|9 formes| spk-042["Mossèn Ramon de Canillo"]
  spk-006["Andreu Gaspà Picart"] ---|9 formes| spk-045["Patrick Pérez"]
  spk-006["Andreu Gaspà Picart"] ---|9 formes| spk-051["Rosa Maria Mandicó Alcobé"]
  spk-006["Andreu Gaspà Picart"] ---|9 formes| spk-057["Teo Armengol"]
  spk-007["Angelina Mas"] ---|9 formes| spk-011["Carles Sasplugas"]
  spk-008["Antoni Armengol Vila"] ---|9 formes| spk-012["Casimir Arajol"]
  spk-008["Antoni Armengol Vila"] ---|9 formes| spk-018["Eudald Guillamet"]
  spk-008["Antoni Armengol Vila"] ---|9 formes| spk-030["Josep Areny"]
  spk-008["Antoni Armengol Vila"] ---|9 formes| spk-033["Josep Garrallà Rossell"]
  spk-008["Antoni Armengol Vila"] ---|9 formes| spk-041["Miquel Naudi Casal"]
  spk-008["Antoni Armengol Vila"] ---|9 formes| spk-043["Nadia Aleix Tugas"]
  spk-008["Antoni Armengol Vila"] ---|9 formes| spk-054["Roser Jordana"]
  spk-008["Antoni Armengol Vila"] ---|9 formes| spk-057["Teo Armengol"]
  spk-009["Antoni Jordi Areny"] ---|9 formes| spk-016["Enric Dolsa Font"]
  spk-009["Antoni Jordi Areny"] ---|9 formes| spk-020["Gabriel Dallerès Codina"]
  spk-009["Antoni Jordi Areny"] ---|9 formes| spk-040["Miquel Armengol Pons"]
  spk-009["Antoni Jordi Areny"] ---|9 formes| spk-042["Mossèn Ramon de Canillo"]
  spk-009["Antoni Jordi Areny"] ---|9 formes| spk-043["Nadia Aleix Tugas"]
  spk-009["Antoni Jordi Areny"] ---|9 formes| spk-048["Ramon Canut Bové"]
  spk-010["Antoni Morell"] ---|9 formes| spk-014["Daniel Armengol"]
  spk-010["Antoni Morell"] ---|9 formes| spk-027["Jordi Marquet"]
  spk-010["Antoni Morell"] ---|9 formes| spk-028["Jordi Mas Torres"]
  spk-010["Antoni Morell"] ---|9 formes| spk-038["Mercè Segura"]
  spk-010["Antoni Morell"] ---|9 formes| spk-046["Pere Altimir Pintat"]
  spk-011["Carles Sasplugas"] ---|9 formes| spk-016["Enric Dolsa Font"]
  spk-011["Carles Sasplugas"] ---|9 formes| spk-019["Francina Pons"]
  spk-011["Carles Sasplugas"] ---|9 formes| spk-024["Jaume Bartumeu Cassany"]
  spk-011["Carles Sasplugas"] ---|9 formes| spk-028["Jordi Mas Torres"]
  spk-011["Carles Sasplugas"] ---|9 formes| spk-043["Nadia Aleix Tugas"]
  spk-011["Carles Sasplugas"] ---|9 formes| spk-044["Olga Adellach Coma"]
  spk-012["Casimir Arajol"] ---|9 formes| spk-027["Jordi Marquet"]
  spk-012["Casimir Arajol"] ---|9 formes| spk-028["Jordi Mas Torres"]
  spk-012["Casimir Arajol"] ---|9 formes| spk-030["Josep Areny"]
  spk-012["Casimir Arajol"] ---|9 formes| spk-031["Josep Areny Fité"]
  spk-012["Casimir Arajol"] ---|9 formes| spk-038["Mercè Segura"]
  spk-012["Casimir Arajol"] ---|9 formes| spk-046["Pere Altimir Pintat"]
  spk-012["Casimir Arajol"] ---|9 formes| spk-057["Teo Armengol"]
  spk-014["Daniel Armengol"] ---|9 formes| spk-018["Eudald Guillamet"]
  spk-014["Daniel Armengol"] ---|9 formes| spk-020["Gabriel Dallerès Codina"]
  spk-014["Daniel Armengol"] ---|9 formes| spk-021["Gualbert Osorio"]
  spk-014["Daniel Armengol"] ---|9 formes| spk-030["Josep Areny"]
  spk-014["Daniel Armengol"] ---|9 formes| spk-037["Maria Reig Moles"]
  spk-014["Daniel Armengol"] ---|9 formes| spk-038["Mercè Segura"]
  spk-014["Daniel Armengol"] ---|9 formes| spk-042["Mossèn Ramon de Canillo"]
  spk-014["Daniel Armengol"] ---|9 formes| spk-043["Nadia Aleix Tugas"]
  spk-014["Daniel Armengol"] ---|9 formes| spk-045["Patrick Pérez"]
  spk-014["Daniel Armengol"] ---|9 formes| spk-046["Pere Altimir Pintat"]
  spk-014["Daniel Armengol"] ---|9 formes| spk-050["Robert Lizarte"]
  spk-014["Daniel Armengol"] ---|9 formes| spk-054["Roser Jordana"]
  spk-014["Daniel Armengol"] ---|9 formes| spk-060["Àngels Mach"]
  spk-015["Enric Casadevall Medrano"] ---|9 formes| spk-017["Esther Jover"]
  spk-015["Enric Casadevall Medrano"] ---|9 formes| spk-034["Josep Marsal Riba"]
  spk-015["Enric Casadevall Medrano"] ---|9 formes| spk-049["Robert Cassany Vila"]
  spk-016["Enric Dolsa Font"] ---|9 formes| spk-041["Miquel Naudi Casal"]
  spk-016["Enric Dolsa Font"] ---|9 formes| spk-059["Xavier Planas"]
  spk-016["Enric Dolsa Font"] ---|9 formes| spk-060["Àngels Mach"]
  spk-017["Esther Jover"] ---|9 formes| spk-026["Jordi Farràs Forné"]
  spk-017["Esther Jover"] ---|9 formes| spk-035["Ladislau Baró Solà"]
  spk-017["Esther Jover"] ---|9 formes| spk-048["Ramon Canut Bové"]
  spk-018["Eudald Guillamet"] ---|9 formes| spk-027["Jordi Marquet"]
  spk-018["Eudald Guillamet"] ---|9 formes| spk-038["Mercè Segura"]
  spk-018["Eudald Guillamet"] ---|9 formes| spk-046["Pere Altimir Pintat"]
  spk-019["Francina Pons"] ---|9 formes| spk-025["Joan Santamaria Terré"]
  spk-019["Francina Pons"] ---|9 formes| spk-036["Ludmilla Lacueva"]
  spk-019["Francina Pons"] ---|9 formes| spk-039["Miquel Aleix Areny"]
  spk-019["Francina Pons"] ---|9 formes| spk-043["Nadia Aleix Tugas"]
  spk-019["Francina Pons"] ---|9 formes| spk-050["Robert Lizarte"]
  spk-019["Francina Pons"] ---|9 formes| spk-057["Teo Armengol"]
  spk-020["Gabriel Dallerès Codina"] ---|9 formes| spk-025["Joan Santamaria Terré"]
  spk-020["Gabriel Dallerès Codina"] ---|9 formes| spk-027["Jordi Marquet"]
  spk-020["Gabriel Dallerès Codina"] ---|9 formes| spk-028["Jordi Mas Torres"]
  spk-020["Gabriel Dallerès Codina"] ---|9 formes| spk-043["Nadia Aleix Tugas"]
  spk-020["Gabriel Dallerès Codina"] ---|9 formes| spk-049["Robert Cassany Vila"]
  spk-020["Gabriel Dallerès Codina"] ---|9 formes| spk-053["Roser Bastida"]
  spk-020["Gabriel Dallerès Codina"] ---|9 formes| spk-057["Teo Armengol"]
  spk-020["Gabriel Dallerès Codina"] ---|9 formes| spk-059["Xavier Planas"]
  spk-021["Gualbert Osorio"] ---|9 formes| spk-027["Jordi Marquet"]
  spk-021["Gualbert Osorio"] ---|9 formes| spk-028["Jordi Mas Torres"]
  spk-021["Gualbert Osorio"] ---|9 formes| spk-030["Josep Areny"]
  spk-021["Gualbert Osorio"] ---|9 formes| spk-031["Josep Areny Fité"]
  spk-021["Gualbert Osorio"] ---|9 formes| spk-038["Mercè Segura"]
  spk-021["Gualbert Osorio"] ---|9 formes| spk-046["Pere Altimir Pintat"]
  spk-021["Gualbert Osorio"] ---|9 formes| spk-057["Teo Armengol"]
  spk-022["Guillem Areny Argelich"] ---|9 formes| spk-027["Jordi Marquet"]
  spk-022["Guillem Areny Argelich"] ---|9 formes| spk-035["Ladislau Baró Solà"]
  spk-022["Guillem Areny Argelich"] ---|9 formes| spk-036["Ludmilla Lacueva"]
  spk-022["Guillem Areny Argelich"] ---|9 formes| spk-040["Miquel Armengol Pons"]
  spk-022["Guillem Areny Argelich"] ---|9 formes| spk-045["Patrick Pérez"]
  spk-022["Guillem Areny Argelich"] ---|9 formes| spk-050["Robert Lizarte"]
  spk-024["Jaume Bartumeu Cassany"] ---|9 formes| spk-053["Roser Bastida"]
  spk-024["Jaume Bartumeu Cassany"] ---|9 formes| spk-060["Àngels Mach"]
  spk-025["Joan Santamaria Terré"] ---|9 formes| spk-031["Josep Areny Fité"]
  spk-025["Joan Santamaria Terré"] ---|9 formes| spk-040["Miquel Armengol Pons"]
  spk-025["Joan Santamaria Terré"] ---|9 formes| spk-042["Mossèn Ramon de Canillo"]
  spk-025["Joan Santamaria Terré"] ---|9 formes| spk-057["Teo Armengol"]
  spk-026["Jordi Farràs Forné"] ---|9 formes| spk-030["Josep Areny"]
  spk-026["Jordi Farràs Forné"] ---|9 formes| spk-033["Josep Garrallà Rossell"]
  spk-026["Jordi Farràs Forné"] ---|9 formes| spk-041["Miquel Naudi Casal"]
  spk-026["Jordi Farràs Forné"] ---|9 formes| spk-059["Xavier Planas"]
  spk-027["Jordi Marquet"] ---|9 formes| spk-028["Jordi Mas Torres"]
  spk-027["Jordi Marquet"] ---|9 formes| spk-038["Mercè Segura"]
  spk-027["Jordi Marquet"] ---|9 formes| spk-045["Patrick Pérez"]
  spk-027["Jordi Marquet"] ---|9 formes| spk-054["Roser Jordana"]
  spk-027["Jordi Marquet"] ---|9 formes| spk-057["Teo Armengol"]
  spk-028["Jordi Mas Torres"] ---|9 formes| spk-031["Josep Areny Fité"]
  spk-028["Jordi Mas Torres"] ---|9 formes| spk-034["Josep Marsal Riba"]
  spk-028["Jordi Mas Torres"] ---|9 formes| spk-040["Miquel Armengol Pons"]
  spk-028["Jordi Mas Torres"] ---|9 formes| spk-041["Miquel Naudi Casal"]
  spk-028["Jordi Mas Torres"] ---|9 formes| spk-046["Pere Altimir Pintat"]
  spk-030["Josep Areny"] ---|9 formes| spk-043["Nadia Aleix Tugas"]
  spk-030["Josep Areny"] ---|9 formes| spk-045["Patrick Pérez"]
  spk-030["Josep Areny"] ---|9 formes| spk-050["Robert Lizarte"]
  spk-030["Josep Areny"] ---|9 formes| spk-054["Roser Jordana"]
  spk-030["Josep Areny"] ---|9 formes| spk-057["Teo Armengol"]
  spk-031["Josep Areny Fité"] ---|9 formes| spk-033["Josep Garrallà Rossell"]
  spk-031["Josep Areny Fité"] ---|9 formes| spk-034["Josep Marsal Riba"]
  spk-031["Josep Areny Fité"] ---|9 formes| spk-038["Mercè Segura"]
  spk-031["Josep Areny Fité"] ---|9 formes| spk-045["Patrick Pérez"]
  spk-031["Josep Areny Fité"] ---|9 formes| spk-054["Roser Jordana"]
  spk-031["Josep Areny Fité"] ---|9 formes| spk-057["Teo Armengol"]
  spk-033["Josep Garrallà Rossell"] ---|9 formes| spk-044["Olga Adellach Coma"]
  spk-033["Josep Garrallà Rossell"] ---|9 formes| spk-048["Ramon Canut Bové"]
  spk-033["Josep Garrallà Rossell"] ---|9 formes| spk-051["Rosa Maria Mandicó Alcobé"]
  spk-034["Josep Marsal Riba"] ---|9 formes| spk-037["Maria Reig Moles"]
  spk-034["Josep Marsal Riba"] ---|9 formes| spk-043["Nadia Aleix Tugas"]
  spk-034["Josep Marsal Riba"] ---|9 formes| spk-044["Olga Adellach Coma"]
  spk-034["Josep Marsal Riba"] ---|9 formes| spk-048["Ramon Canut Bové"]
  spk-034["Josep Marsal Riba"] ---|9 formes| spk-051["Rosa Maria Mandicó Alcobé"]
  spk-034["Josep Marsal Riba"] ---|9 formes| spk-057["Teo Armengol"]
  spk-035["Ladislau Baró Solà"] ---|9 formes| spk-036["Ludmilla Lacueva"]
  spk-035["Ladislau Baró Solà"] ---|9 formes| spk-059["Xavier Planas"]
  spk-035["Ladislau Baró Solà"] ---|9 formes| spk-060["Àngels Mach"]
  spk-036["Ludmilla Lacueva"] ---|9 formes| spk-037["Maria Reig Moles"]
  spk-036["Ludmilla Lacueva"] ---|9 formes| spk-043["Nadia Aleix Tugas"]
  spk-036["Ludmilla Lacueva"] ---|9 formes| spk-051["Rosa Maria Mandicó Alcobé"]
  spk-036["Ludmilla Lacueva"] ---|9 formes| spk-057["Teo Armengol"]
  spk-037["Maria Reig Moles"] ---|9 formes| spk-050["Robert Lizarte"]
  spk-037["Maria Reig Moles"] ---|9 formes| spk-057["Teo Armengol"]
  spk-038["Mercè Segura"] ---|9 formes| spk-039["Miquel Aleix Areny"]
  spk-038["Mercè Segura"] ---|9 formes| spk-045["Patrick Pérez"]
  spk-038["Mercè Segura"] ---|9 formes| spk-046["Pere Altimir Pintat"]
  spk-038["Mercè Segura"] ---|9 formes| spk-054["Roser Jordana"]
  spk-038["Mercè Segura"] ---|9 formes| spk-057["Teo Armengol"]
  spk-040["Miquel Armengol Pons"] ---|9 formes| spk-049["Robert Cassany Vila"]
  spk-041["Miquel Naudi Casal"] ---|9 formes| spk-042["Mossèn Ramon de Canillo"]
  spk-041["Miquel Naudi Casal"] ---|9 formes| spk-044["Olga Adellach Coma"]
  spk-041["Miquel Naudi Casal"] ---|9 formes| spk-050["Robert Lizarte"]
  spk-042["Mossèn Ramon de Canillo"] ---|9 formes| spk-046["Pere Altimir Pintat"]
  spk-042["Mossèn Ramon de Canillo"] ---|9 formes| spk-060["Àngels Mach"]
  spk-044["Olga Adellach Coma"] ---|9 formes| spk-053["Roser Bastida"]
  spk-044["Olga Adellach Coma"] ---|9 formes| spk-059["Xavier Planas"]
  spk-044["Olga Adellach Coma"] ---|9 formes| spk-060["Àngels Mach"]
  spk-045["Patrick Pérez"] ---|9 formes| spk-046["Pere Altimir Pintat"]
  spk-045["Patrick Pérez"] ---|9 formes| spk-057["Teo Armengol"]
  spk-046["Pere Altimir Pintat"] ---|9 formes| spk-054["Roser Jordana"]
  spk-048["Ramon Canut Bové"] ---|9 formes| spk-059["Xavier Planas"]
  spk-054["Roser Jordana"] ---|9 formes| spk-057["Teo Armengol"]
  spk-054["Roser Jordana"] ---|9 formes| spk-060["Àngels Mach"]
  spk-001["Alan Ward"] ---|8 formes| spk-002["Albert Gelabert Grau"]
  spk-001["Alan Ward"] ---|8 formes| spk-008["Antoni Armengol Vila"]
  spk-001["Alan Ward"] ---|8 formes| spk-009["Antoni Jordi Areny"]
  spk-001["Alan Ward"] ---|8 formes| spk-019["Francina Pons"]
  spk-001["Alan Ward"] ---|8 formes| spk-022["Guillem Areny Argelich"]
  spk-001["Alan Ward"] ---|8 formes| spk-025["Joan Santamaria Terré"]
  spk-001["Alan Ward"] ---|8 formes| spk-036["Ludmilla Lacueva"]
  spk-001["Alan Ward"] ---|8 formes| spk-037["Maria Reig Moles"]
  spk-001["Alan Ward"] ---|8 formes| spk-039["Miquel Aleix Areny"]
  spk-001["Alan Ward"] ---|8 formes| spk-042["Mossèn Ramon de Canillo"]
  spk-001["Alan Ward"] ---|8 formes| spk-059["Xavier Planas"]
  spk-002["Albert Gelabert Grau"] ---|8 formes| spk-009["Antoni Jordi Areny"]
  spk-002["Albert Gelabert Grau"] ---|8 formes| spk-025["Joan Santamaria Terré"]
  spk-002["Albert Gelabert Grau"] ---|8 formes| spk-033["Josep Garrallà Rossell"]
  spk-002["Albert Gelabert Grau"] ---|8 formes| spk-034["Josep Marsal Riba"]
  spk-002["Albert Gelabert Grau"] ---|8 formes| spk-059["Xavier Planas"]
  spk-003["Albert Roig"] ---|8 formes| spk-011["Carles Sasplugas"]
  spk-003["Albert Roig"] ---|8 formes| spk-012["Casimir Arajol"]
  spk-003["Albert Roig"] ---|8 formes| spk-014["Daniel Armengol"]
  spk-003["Albert Roig"] ---|8 formes| spk-033["Josep Garrallà Rossell"]
  spk-003["Albert Roig"] ---|8 formes| spk-038["Mercè Segura"]
  spk-003["Albert Roig"] ---|8 formes| spk-041["Miquel Naudi Casal"]
  spk-003["Albert Roig"] ---|8 formes| spk-049["Robert Cassany Vila"]
  spk-003["Albert Roig"] ---|8 formes| spk-053["Roser Bastida"]
  spk-003["Albert Roig"] ---|8 formes| spk-060["Àngels Mach"]
  spk-005["Alfred Llahí"] ---|8 formes| spk-009["Antoni Jordi Areny"]
  spk-005["Alfred Llahí"] ---|8 formes| spk-011["Carles Sasplugas"]
  spk-005["Alfred Llahí"] ---|8 formes| spk-017["Esther Jover"]
  spk-005["Alfred Llahí"] ---|8 formes| spk-021["Gualbert Osorio"]
  spk-005["Alfred Llahí"] ---|8 formes| spk-033["Josep Garrallà Rossell"]
  spk-005["Alfred Llahí"] ---|8 formes| spk-049["Robert Cassany Vila"]
  spk-005["Alfred Llahí"] ---|8 formes| spk-053["Roser Bastida"]
  spk-005["Alfred Llahí"] ---|8 formes| spk-054["Roser Jordana"]
  spk-005["Alfred Llahí"] ---|8 formes| spk-059["Xavier Planas"]
  spk-006["Andreu Gaspà Picart"] ---|8 formes| spk-008["Antoni Armengol Vila"]
  spk-006["Andreu Gaspà Picart"] ---|8 formes| spk-022["Guillem Areny Argelich"]
  spk-006["Andreu Gaspà Picart"] ---|8 formes| spk-030["Josep Areny"]
  spk-006["Andreu Gaspà Picart"] ---|8 formes| spk-033["Josep Garrallà Rossell"]
  spk-006["Andreu Gaspà Picart"] ---|8 formes| spk-035["Ladislau Baró Solà"]
  spk-006["Andreu Gaspà Picart"] ---|8 formes| spk-038["Mercè Segura"]
  spk-007["Angelina Mas"] ---|8 formes| spk-017["Esther Jover"]
  spk-007["Angelina Mas"] ---|8 formes| spk-033["Josep Garrallà Rossell"]
  spk-007["Angelina Mas"] ---|8 formes| spk-036["Ludmilla Lacueva"]
  spk-007["Angelina Mas"] ---|8 formes| spk-049["Robert Cassany Vila"]
  spk-007["Angelina Mas"] ---|8 formes| spk-060["Àngels Mach"]
  spk-008["Antoni Armengol Vila"] ---|8 formes| spk-022["Guillem Areny Argelich"]
  spk-008["Antoni Armengol Vila"] ---|8 formes| spk-025["Joan Santamaria Terré"]
  spk-008["Antoni Armengol Vila"] ---|8 formes| spk-027["Jordi Marquet"]
  spk-008["Antoni Armengol Vila"] ---|8 formes| spk-038["Mercè Segura"]
  spk-008["Antoni Armengol Vila"] ---|8 formes| spk-045["Patrick Pérez"]
  spk-008["Antoni Armengol Vila"] ---|8 formes| spk-046["Pere Altimir Pintat"]
  spk-008["Antoni Armengol Vila"] ---|8 formes| spk-050["Robert Lizarte"]
  spk-008["Antoni Armengol Vila"] ---|8 formes| spk-053["Roser Bastida"]
  spk-009["Antoni Jordi Areny"] ---|8 formes| spk-010["Antoni Morell"]
  spk-009["Antoni Jordi Areny"] ---|8 formes| spk-012["Casimir Arajol"]
  spk-009["Antoni Jordi Areny"] ---|8 formes| spk-018["Eudald Guillamet"]
  spk-009["Antoni Jordi Areny"] ---|8 formes| spk-028["Jordi Mas Torres"]
  spk-009["Antoni Jordi Areny"] ---|8 formes| spk-041["Miquel Naudi Casal"]
  spk-009["Antoni Jordi Areny"] ---|8 formes| spk-046["Pere Altimir Pintat"]
  spk-009["Antoni Jordi Areny"] ---|8 formes| spk-057["Teo Armengol"]
  spk-009["Antoni Jordi Areny"] ---|8 formes| spk-059["Xavier Planas"]
  spk-010["Antoni Morell"] ---|8 formes| spk-022["Guillem Areny Argelich"]
  spk-010["Antoni Morell"] ---|8 formes| spk-033["Josep Garrallà Rossell"]
  spk-010["Antoni Morell"] ---|8 formes| spk-053["Roser Bastida"]
  spk-010["Antoni Morell"] ---|8 formes| spk-060["Àngels Mach"]
  spk-011["Carles Sasplugas"] ---|8 formes| spk-015["Enric Casadevall Medrano"]
  spk-011["Carles Sasplugas"] ---|8 formes| spk-018["Eudald Guillamet"]
  spk-011["Carles Sasplugas"] ---|8 formes| spk-039["Miquel Aleix Areny"]
  spk-011["Carles Sasplugas"] ---|8 formes| spk-046["Pere Altimir Pintat"]
  spk-012["Casimir Arajol"] ---|8 formes| spk-022["Guillem Areny Argelich"]
  spk-014["Daniel Armengol"] ---|8 formes| spk-017["Esther Jover"]
  spk-014["Daniel Armengol"] ---|8 formes| spk-025["Joan Santamaria Terré"]
  spk-014["Daniel Armengol"] ---|8 formes| spk-028["Jordi Mas Torres"]
  spk-014["Daniel Armengol"] ---|8 formes| spk-031["Josep Areny Fité"]
  spk-014["Daniel Armengol"] ---|8 formes| spk-039["Miquel Aleix Areny"]
  spk-015["Enric Casadevall Medrano"] ---|8 formes| spk-033["Josep Garrallà Rossell"]
  spk-015["Enric Casadevall Medrano"] ---|8 formes| spk-053["Roser Bastida"]
  spk-015["Enric Casadevall Medrano"] ---|8 formes| spk-060["Àngels Mach"]
  spk-017["Esther Jover"] ---|8 formes| spk-019["Francina Pons"]
  spk-017["Esther Jover"] ---|8 formes| spk-020["Gabriel Dallerès Codina"]
  spk-017["Esther Jover"] ---|8 formes| spk-021["Gualbert Osorio"]
  spk-017["Esther Jover"] ---|8 formes| spk-025["Joan Santamaria Terré"]
  spk-017["Esther Jover"] ---|8 formes| spk-031["Josep Areny Fité"]
  spk-017["Esther Jover"] ---|8 formes| spk-040["Miquel Armengol Pons"]
  spk-017["Esther Jover"] ---|8 formes| spk-042["Mossèn Ramon de Canillo"]
  spk-017["Esther Jover"] ---|8 formes| spk-057["Teo Armengol"]
  spk-018["Eudald Guillamet"] ---|8 formes| spk-019["Francina Pons"]
  spk-018["Eudald Guillamet"] ---|8 formes| spk-033["Josep Garrallà Rossell"]
  spk-018["Eudald Guillamet"] ---|8 formes| spk-034["Josep Marsal Riba"]
  spk-018["Eudald Guillamet"] ---|8 formes| spk-050["Robert Lizarte"]
  spk-018["Eudald Guillamet"] ---|8 formes| spk-060["Àngels Mach"]
  spk-019["Francina Pons"] ---|8 formes| spk-051["Rosa Maria Mandicó Alcobé"]
  spk-020["Gabriel Dallerès Codina"] ---|8 formes| spk-031["Josep Areny Fité"]
  spk-020["Gabriel Dallerès Codina"] ---|8 formes| spk-034["Josep Marsal Riba"]
  spk-020["Gabriel Dallerès Codina"] ---|8 formes| spk-038["Mercè Segura"]
  spk-020["Gabriel Dallerès Codina"] ---|8 formes| spk-050["Robert Lizarte"]
  spk-020["Gabriel Dallerès Codina"] ---|8 formes| spk-060["Àngels Mach"]
  spk-021["Gualbert Osorio"] ---|8 formes| spk-060["Àngels Mach"]
  spk-022["Guillem Areny Argelich"] ---|8 formes| spk-030["Josep Areny"]
  spk-022["Guillem Areny Argelich"] ---|8 formes| spk-031["Josep Areny Fité"]
  spk-022["Guillem Areny Argelich"] ---|8 formes| spk-034["Josep Marsal Riba"]
  spk-022["Guillem Areny Argelich"] ---|8 formes| spk-041["Miquel Naudi Casal"]
  spk-022["Guillem Areny Argelich"] ---|8 formes| spk-042["Mossèn Ramon de Canillo"]
  spk-022["Guillem Areny Argelich"] ---|8 formes| spk-053["Roser Bastida"]
  spk-022["Guillem Areny Argelich"] ---|8 formes| spk-054["Roser Jordana"]
  spk-024["Jaume Bartumeu Cassany"] ---|8 formes| spk-041["Miquel Naudi Casal"]
  spk-024["Jaume Bartumeu Cassany"] ---|8 formes| spk-049["Robert Cassany Vila"]
  spk-025["Joan Santamaria Terré"] ---|8 formes| spk-034["Josep Marsal Riba"]
  spk-025["Joan Santamaria Terré"] ---|8 formes| spk-036["Ludmilla Lacueva"]
  spk-025["Joan Santamaria Terré"] ---|8 formes| spk-037["Maria Reig Moles"]
  spk-025["Joan Santamaria Terré"] ---|8 formes| spk-038["Mercè Segura"]
  spk-025["Joan Santamaria Terré"] ---|8 formes| spk-041["Miquel Naudi Casal"]
  spk-026["Jordi Farràs Forné"] ---|8 formes| spk-053["Roser Bastida"]
  spk-026["Jordi Farràs Forné"] ---|8 formes| spk-060["Àngels Mach"]
  spk-027["Jordi Marquet"] ---|8 formes| spk-041["Miquel Naudi Casal"]
  spk-028["Jordi Mas Torres"] ---|8 formes| spk-030["Josep Areny"]
  spk-028["Jordi Mas Torres"] ---|8 formes| spk-033["Josep Garrallà Rossell"]
  spk-028["Jordi Mas Torres"] ---|8 formes| spk-059["Xavier Planas"]
  spk-030["Josep Areny"] ---|8 formes| spk-038["Mercè Segura"]
  spk-030["Josep Areny"] ---|8 formes| spk-041["Miquel Naudi Casal"]
  spk-030["Josep Areny"] ---|8 formes| spk-049["Robert Cassany Vila"]
  spk-030["Josep Areny"] ---|8 formes| spk-053["Roser Bastida"]
  spk-031["Josep Areny Fité"] ---|8 formes| spk-041["Miquel Naudi Casal"]
  spk-031["Josep Areny Fité"] ---|8 formes| spk-043["Nadia Aleix Tugas"]
  spk-031["Josep Areny Fité"] ---|8 formes| spk-046["Pere Altimir Pintat"]
  spk-033["Josep Garrallà Rossell"] ---|8 formes| spk-037["Maria Reig Moles"]
  spk-033["Josep Garrallà Rossell"] ---|8 formes| spk-039["Miquel Aleix Areny"]
  spk-033["Josep Garrallà Rossell"] ---|8 formes| spk-040["Miquel Armengol Pons"]
  spk-033["Josep Garrallà Rossell"] ---|8 formes| spk-054["Roser Jordana"]
  spk-034["Josep Marsal Riba"] ---|8 formes| spk-038["Mercè Segura"]
  spk-034["Josep Marsal Riba"] ---|8 formes| spk-040["Miquel Armengol Pons"]
  spk-034["Josep Marsal Riba"] ---|8 formes| spk-042["Mossèn Ramon de Canillo"]
  spk-034["Josep Marsal Riba"] ---|8 formes| spk-046["Pere Altimir Pintat"]
  spk-035["Ladislau Baró Solà"] ---|8 formes| spk-049["Robert Cassany Vila"]
  spk-035["Ladislau Baró Solà"] ---|8 formes| spk-053["Roser Bastida"]
  spk-036["Ludmilla Lacueva"] ---|8 formes| spk-042["Mossèn Ramon de Canillo"]
  spk-036["Ludmilla Lacueva"] ---|8 formes| spk-059["Xavier Planas"]
  spk-037["Maria Reig Moles"] ---|8 formes| spk-038["Mercè Segura"]
  spk-037["Maria Reig Moles"] ---|8 formes| spk-049["Robert Cassany Vila"]
  spk-039["Miquel Aleix Areny"] ---|8 formes| spk-049["Robert Cassany Vila"]
  spk-039["Miquel Aleix Areny"] ---|8 formes| spk-053["Roser Bastida"]
  spk-039["Miquel Aleix Areny"] ---|8 formes| spk-059["Xavier Planas"]
  spk-040["Miquel Armengol Pons"] ---|8 formes| spk-041["Miquel Naudi Casal"]
  spk-040["Miquel Armengol Pons"] ---|8 formes| spk-050["Robert Lizarte"]
  spk-040["Miquel Armengol Pons"] ---|8 formes| spk-053["Roser Bastida"]
  spk-040["Miquel Armengol Pons"] ---|8 formes| spk-060["Àngels Mach"]
  spk-041["Miquel Naudi Casal"] ---|8 formes| spk-043["Nadia Aleix Tugas"]
  spk-041["Miquel Naudi Casal"] ---|8 formes| spk-048["Ramon Canut Bové"]
  spk-042["Mossèn Ramon de Canillo"] ---|8 formes| spk-053["Roser Bastida"]
  spk-042["Mossèn Ramon de Canillo"] ---|8 formes| spk-059["Xavier Planas"]
  spk-043["Nadia Aleix Tugas"] ---|8 formes| spk-059["Xavier Planas"]
  spk-044["Olga Adellach Coma"] ---|8 formes| spk-049["Robert Cassany Vila"]
  spk-046["Pere Altimir Pintat"] ---|8 formes| spk-049["Robert Cassany Vila"]
  spk-046["Pere Altimir Pintat"] ---|8 formes| spk-050["Robert Lizarte"]
  spk-046["Pere Altimir Pintat"] ---|8 formes| spk-053["Roser Bastida"]
  spk-046["Pere Altimir Pintat"] ---|8 formes| spk-059["Xavier Planas"]
  spk-048["Ramon Canut Bové"] ---|8 formes| spk-060["Àngels Mach"]
  spk-049["Robert Cassany Vila"] ---|8 formes| spk-051["Rosa Maria Mandicó Alcobé"]
  spk-051["Rosa Maria Mandicó Alcobé"] ---|8 formes| spk-060["Àngels Mach"]
  spk-057["Teo Armengol"] ---|8 formes| spk-059["Xavier Planas"]
  spk-057["Teo Armengol"] ---|8 formes| spk-060["Àngels Mach"]
  spk-001["Alan Ward"] ---|7 formes| spk-006["Andreu Gaspà Picart"]
  spk-001["Alan Ward"] ---|7 formes| spk-010["Antoni Morell"]
  spk-001["Alan Ward"] ---|7 formes| spk-011["Carles Sasplugas"]
  spk-001["Alan Ward"] ---|7 formes| spk-014["Daniel Armengol"]
  spk-001["Alan Ward"] ---|7 formes| spk-017["Esther Jover"]
  spk-001["Alan Ward"] ---|7 formes| spk-027["Jordi Marquet"]
  spk-001["Alan Ward"] ---|7 formes| spk-045["Patrick Pérez"]
  spk-001["Alan Ward"] ---|7 formes| spk-046["Pere Altimir Pintat"]
  spk-001["Alan Ward"] ---|7 formes| spk-049["Robert Cassany Vila"]
  spk-001["Alan Ward"] ---|7 formes| spk-051["Rosa Maria Mandicó Alcobé"]
  spk-001["Alan Ward"] ---|7 formes| spk-053["Roser Bastida"]
  spk-001["Alan Ward"] ---|7 formes| spk-054["Roser Jordana"]
  spk-001["Alan Ward"] ---|7 formes| spk-060["Àngels Mach"]
  spk-002["Albert Gelabert Grau"] ---|7 formes| spk-019["Francina Pons"]
  spk-002["Albert Gelabert Grau"] ---|7 formes| spk-049["Robert Cassany Vila"]
  spk-002["Albert Gelabert Grau"] ---|7 formes| spk-050["Robert Lizarte"]
  spk-003["Albert Roig"] ---|7 formes| spk-045["Patrick Pérez"]
  spk-005["Alfred Llahí"] ---|7 formes| spk-058["Trini Mandicó Baró"]
  spk-006["Andreu Gaspà Picart"] ---|7 formes| spk-014["Daniel Armengol"]
  spk-006["Andreu Gaspà Picart"] ---|7 formes| spk-017["Esther Jover"]
  spk-006["Andreu Gaspà Picart"] ---|7 formes| spk-025["Joan Santamaria Terré"]
  spk-006["Andreu Gaspà Picart"] ---|7 formes| spk-027["Jordi Marquet"]
  spk-006["Andreu Gaspà Picart"] ---|7 formes| spk-041["Miquel Naudi Casal"]
  spk-006["Andreu Gaspà Picart"] ---|7 formes| spk-043["Nadia Aleix Tugas"]
  spk-006["Andreu Gaspà Picart"] ---|7 formes| spk-046["Pere Altimir Pintat"]
  spk-006["Andreu Gaspà Picart"] ---|7 formes| spk-049["Robert Cassany Vila"]
  spk-006["Andreu Gaspà Picart"] ---|7 formes| spk-060["Àngels Mach"]
  spk-007["Angelina Mas"] ---|7 formes| spk-059["Xavier Planas"]
  spk-008["Antoni Armengol Vila"] ---|7 formes| spk-011["Carles Sasplugas"]
  spk-008["Antoni Armengol Vila"] ---|7 formes| spk-017["Esther Jover"]
  spk-008["Antoni Armengol Vila"] ---|7 formes| spk-019["Francina Pons"]
  spk-008["Antoni Armengol Vila"] ---|7 formes| spk-034["Josep Marsal Riba"]
  spk-008["Antoni Armengol Vila"] ---|7 formes| spk-049["Robert Cassany Vila"]
  spk-009["Antoni Jordi Areny"] ---|7 formes| spk-019["Francina Pons"]
  spk-009["Antoni Jordi Areny"] ---|7 formes| spk-021["Gualbert Osorio"]
  spk-009["Antoni Jordi Areny"] ---|7 formes| spk-022["Guillem Areny Argelich"]
  spk-009["Antoni Jordi Areny"] ---|7 formes| spk-027["Jordi Marquet"]
  spk-009["Antoni Jordi Areny"] ---|7 formes| spk-030["Josep Areny"]
  spk-009["Antoni Jordi Areny"] ---|7 formes| spk-031["Josep Areny Fité"]
  spk-009["Antoni Jordi Areny"] ---|7 formes| spk-034["Josep Marsal Riba"]
  spk-009["Antoni Jordi Areny"] ---|7 formes| spk-038["Mercè Segura"]
  spk-009["Antoni Jordi Areny"] ---|7 formes| spk-045["Patrick Pérez"]
  spk-009["Antoni Jordi Areny"] ---|7 formes| spk-049["Robert Cassany Vila"]
  spk-009["Antoni Jordi Areny"] ---|7 formes| spk-050["Robert Lizarte"]
  spk-009["Antoni Jordi Areny"] ---|7 formes| spk-053["Roser Bastida"]
  spk-009["Antoni Jordi Areny"] ---|7 formes| spk-054["Roser Jordana"]
  spk-010["Antoni Morell"] ---|7 formes| spk-017["Esther Jover"]
  spk-010["Antoni Morell"] ---|7 formes| spk-025["Joan Santamaria Terré"]
  spk-010["Antoni Morell"] ---|7 formes| spk-034["Josep Marsal Riba"]
  spk-010["Antoni Morell"] ---|7 formes| spk-041["Miquel Naudi Casal"]
  spk-010["Antoni Morell"] ---|7 formes| spk-049["Robert Cassany Vila"]
  spk-010["Antoni Morell"] ---|7 formes| spk-050["Robert Lizarte"]
  spk-011["Carles Sasplugas"] ---|7 formes| spk-020["Gabriel Dallerès Codina"]
  spk-011["Carles Sasplugas"] ---|7 formes| spk-021["Gualbert Osorio"]
  spk-011["Carles Sasplugas"] ---|7 formes| spk-022["Guillem Areny Argelich"]
  spk-011["Carles Sasplugas"] ---|7 formes| spk-025["Joan Santamaria Terré"]
  spk-011["Carles Sasplugas"] ---|7 formes| spk-037["Maria Reig Moles"]
  spk-011["Carles Sasplugas"] ---|7 formes| spk-040["Miquel Armengol Pons"]
  spk-011["Carles Sasplugas"] ---|7 formes| spk-042["Mossèn Ramon de Canillo"]
  spk-011["Carles Sasplugas"] ---|7 formes| spk-045["Patrick Pérez"]
  spk-011["Carles Sasplugas"] ---|7 formes| spk-051["Rosa Maria Mandicó Alcobé"]
  spk-011["Carles Sasplugas"] ---|7 formes| spk-054["Roser Jordana"]
  spk-012["Casimir Arajol"] ---|7 formes| spk-025["Joan Santamaria Terré"]
  spk-012["Casimir Arajol"] ---|7 formes| spk-033["Josep Garrallà Rossell"]
  spk-012["Casimir Arajol"] ---|7 formes| spk-034["Josep Marsal Riba"]
  spk-012["Casimir Arajol"] ---|7 formes| spk-041["Miquel Naudi Casal"]
  spk-012["Casimir Arajol"] ---|7 formes| spk-049["Robert Cassany Vila"]
  spk-012["Casimir Arajol"] ---|7 formes| spk-060["Àngels Mach"]
  spk-014["Daniel Armengol"] ---|7 formes| spk-022["Guillem Areny Argelich"]
  spk-014["Daniel Armengol"] ---|7 formes| spk-034["Josep Marsal Riba"]
  spk-014["Daniel Armengol"] ---|7 formes| spk-059["Xavier Planas"]
  spk-015["Enric Casadevall Medrano"] ---|7 formes| spk-029["Jordi Torres Alís"]
  spk-016["Enric Dolsa Font"] ---|7 formes| spk-049["Robert Cassany Vila"]
  spk-016["Enric Dolsa Font"] ---|7 formes| spk-053["Roser Bastida"]
  spk-016["Enric Dolsa Font"] ---|7 formes| spk-055["Ruth Casabella"]
  spk-016["Enric Dolsa Font"] ---|7 formes| spk-058["Trini Mandicó Baró"]
  spk-017["Esther Jover"] ---|7 formes| spk-018["Eudald Guillamet"]
  spk-017["Esther Jover"] ---|7 formes| spk-027["Jordi Marquet"]
  spk-017["Esther Jover"] ---|7 formes| spk-028["Jordi Mas Torres"]
  spk-017["Esther Jover"] ---|7 formes| spk-030["Josep Areny"]
  spk-017["Esther Jover"] ---|7 formes| spk-038["Mercè Segura"]
  spk-017["Esther Jover"] ---|7 formes| spk-046["Pere Altimir Pintat"]
  spk-017["Esther Jover"] ---|7 formes| spk-051["Rosa Maria Mandicó Alcobé"]
  spk-017["Esther Jover"] ---|7 formes| spk-054["Roser Jordana"]
  spk-017["Esther Jover"] ---|7 formes| spk-059["Xavier Planas"]
  spk-017["Esther Jover"] ---|7 formes| spk-060["Àngels Mach"]
  spk-018["Eudald Guillamet"] ---|7 formes| spk-025["Joan Santamaria Terré"]
  spk-018["Eudald Guillamet"] ---|7 formes| spk-036["Ludmilla Lacueva"]
  spk-018["Eudald Guillamet"] ---|7 formes| spk-041["Miquel Naudi Casal"]
  spk-018["Eudald Guillamet"] ---|7 formes| spk-049["Robert Cassany Vila"]
  spk-018["Eudald Guillamet"] ---|7 formes| spk-053["Roser Bastida"]
  spk-019["Francina Pons"] ---|7 formes| spk-027["Jordi Marquet"]
  spk-019["Francina Pons"] ---|7 formes| spk-031["Josep Areny Fité"]
  spk-019["Francina Pons"] ---|7 formes| spk-034["Josep Marsal Riba"]
  spk-019["Francina Pons"] ---|7 formes| spk-037["Maria Reig Moles"]
  spk-019["Francina Pons"] ---|7 formes| spk-040["Miquel Armengol Pons"]
  spk-019["Francina Pons"] ---|7 formes| spk-042["Mossèn Ramon de Canillo"]
  spk-019["Francina Pons"] ---|7 formes| spk-059["Xavier Planas"]
  spk-020["Gabriel Dallerès Codina"] ---|7 formes| spk-033["Josep Garrallà Rossell"]
  spk-020["Gabriel Dallerès Codina"] ---|7 formes| spk-036["Ludmilla Lacueva"]
  spk-020["Gabriel Dallerès Codina"] ---|7 formes| spk-041["Miquel Naudi Casal"]
  spk-021["Gualbert Osorio"] ---|7 formes| spk-022["Guillem Areny Argelich"]
  spk-021["Gualbert Osorio"] ---|7 formes| spk-025["Joan Santamaria Terré"]
  spk-021["Gualbert Osorio"] ---|7 formes| spk-033["Josep Garrallà Rossell"]
  spk-022["Guillem Areny Argelich"] ---|7 formes| spk-033["Josep Garrallà Rossell"]
  spk-022["Guillem Areny Argelich"] ---|7 formes| spk-038["Mercè Segura"]
  spk-022["Guillem Areny Argelich"] ---|7 formes| spk-049["Robert Cassany Vila"]
  spk-024["Jaume Bartumeu Cassany"] ---|7 formes| spk-029["Jordi Torres Alís"]
  spk-024["Jaume Bartumeu Cassany"] ---|7 formes| spk-055["Ruth Casabella"]
  spk-025["Joan Santamaria Terré"] ---|7 formes| spk-045["Patrick Pérez"]
  spk-025["Joan Santamaria Terré"] ---|7 formes| spk-049["Robert Cassany Vila"]
  spk-025["Joan Santamaria Terré"] ---|7 formes| spk-053["Roser Bastida"]
  spk-025["Joan Santamaria Terré"] ---|7 formes| spk-054["Roser Jordana"]
  spk-025["Joan Santamaria Terré"] ---|7 formes| spk-059["Xavier Planas"]
  spk-026["Jordi Farràs Forné"] ---|7 formes| spk-049["Robert Cassany Vila"]
  spk-026["Jordi Farràs Forné"] ---|7 formes| spk-058["Trini Mandicó Baró"]
  spk-027["Jordi Marquet"] ---|7 formes| spk-033["Josep Garrallà Rossell"]
  spk-027["Jordi Marquet"] ---|7 formes| spk-034["Josep Marsal Riba"]
  spk-027["Jordi Marquet"] ---|7 formes| spk-049["Robert Cassany Vila"]
  spk-027["Jordi Marquet"] ---|7 formes| spk-053["Roser Bastida"]
  spk-027["Jordi Marquet"] ---|7 formes| spk-060["Àngels Mach"]
  spk-028["Jordi Mas Torres"] ---|7 formes| spk-058["Trini Mandicó Baró"]
  spk-029["Jordi Torres Alís"] ---|7 formes| spk-035["Ladislau Baró Solà"]
  spk-029["Jordi Torres Alís"] ---|7 formes| spk-044["Olga Adellach Coma"]
  spk-030["Josep Areny"] ---|7 formes| spk-033["Josep Garrallà Rossell"]
  spk-030["Josep Areny"] ---|7 formes| spk-034["Josep Marsal Riba"]
  spk-030["Josep Areny"] ---|7 formes| spk-060["Àngels Mach"]
  spk-031["Josep Areny Fité"] ---|7 formes| spk-050["Robert Lizarte"]
  spk-031["Josep Areny Fité"] ---|7 formes| spk-053["Roser Bastida"]
  spk-033["Josep Garrallà Rossell"] ---|7 formes| spk-035["Ladislau Baró Solà"]
  spk-033["Josep Garrallà Rossell"] ---|7 formes| spk-038["Mercè Segura"]
  spk-033["Josep Garrallà Rossell"] ---|7 formes| spk-041["Miquel Naudi Casal"]
  spk-033["Josep Garrallà Rossell"] ---|7 formes| spk-045["Patrick Pérez"]
  spk-033["Josep Garrallà Rossell"] ---|7 formes| spk-057["Teo Armengol"]
  spk-034["Josep Marsal Riba"] ---|7 formes| spk-036["Ludmilla Lacueva"]
  spk-034["Josep Marsal Riba"] ---|7 formes| spk-041["Miquel Naudi Casal"]
  spk-034["Josep Marsal Riba"] ---|7 formes| spk-045["Patrick Pérez"]
  spk-034["Josep Marsal Riba"] ---|7 formes| spk-050["Robert Lizarte"]
  spk-034["Josep Marsal Riba"] ---|7 formes| spk-059["Xavier Planas"]
  spk-035["Ladislau Baró Solà"] ---|7 formes| spk-041["Miquel Naudi Casal"]
  spk-035["Ladislau Baró Solà"] ---|7 formes| spk-055["Ruth Casabella"]
  spk-035["Ladislau Baró Solà"] ---|7 formes| spk-058["Trini Mandicó Baró"]
  spk-036["Ludmilla Lacueva"] ---|7 formes| spk-041["Miquel Naudi Casal"]
  spk-037["Maria Reig Moles"] ---|7 formes| spk-059["Xavier Planas"]
  spk-037["Maria Reig Moles"] ---|7 formes| spk-060["Àngels Mach"]
  spk-038["Mercè Segura"] ---|7 formes| spk-041["Miquel Naudi Casal"]
  spk-038["Mercè Segura"] ---|7 formes| spk-050["Robert Lizarte"]
  spk-038["Mercè Segura"] ---|7 formes| spk-059["Xavier Planas"]
  spk-039["Miquel Aleix Areny"] ---|7 formes| spk-058["Trini Mandicó Baró"]
  spk-040["Miquel Armengol Pons"] ---|7 formes| spk-059["Xavier Planas"]
  spk-041["Miquel Naudi Casal"] ---|7 formes| spk-045["Patrick Pérez"]
  spk-041["Miquel Naudi Casal"] ---|7 formes| spk-046["Pere Altimir Pintat"]
  spk-041["Miquel Naudi Casal"] ---|7 formes| spk-049["Robert Cassany Vila"]
  spk-041["Miquel Naudi Casal"] ---|7 formes| spk-054["Roser Jordana"]
  spk-041["Miquel Naudi Casal"] ---|7 formes| spk-057["Teo Armengol"]
  spk-042["Mossèn Ramon de Canillo"] ---|7 formes| spk-049["Robert Cassany Vila"]
  spk-043["Nadia Aleix Tugas"] ---|7 formes| spk-053["Roser Bastida"]
  spk-043["Nadia Aleix Tugas"] ---|7 formes| spk-055["Ruth Casabella"]
  spk-045["Patrick Pérez"] ---|7 formes| spk-049["Robert Cassany Vila"]
  spk-045["Patrick Pérez"] ---|7 formes| spk-050["Robert Lizarte"]
  spk-045["Patrick Pérez"] ---|7 formes| spk-060["Àngels Mach"]
  spk-046["Pere Altimir Pintat"] ---|7 formes| spk-057["Teo Armengol"]
  spk-048["Ramon Canut Bové"] ---|7 formes| spk-049["Robert Cassany Vila"]
  spk-048["Ramon Canut Bové"] ---|7 formes| spk-053["Roser Bastida"]
  spk-048["Ramon Canut Bové"] ---|7 formes| spk-055["Ruth Casabella"]
  spk-048["Ramon Canut Bové"] ---|7 formes| spk-058["Trini Mandicó Baró"]
  spk-049["Robert Cassany Vila"] ---|7 formes| spk-054["Roser Jordana"]
  spk-050["Robert Lizarte"] ---|7 formes| spk-054["Roser Jordana"]
  spk-050["Robert Lizarte"] ---|7 formes| spk-059["Xavier Planas"]
  spk-050["Robert Lizarte"] ---|7 formes| spk-060["Àngels Mach"]
  spk-051["Rosa Maria Mandicó Alcobé"] ---|7 formes| spk-053["Roser Bastida"]
  spk-051["Rosa Maria Mandicó Alcobé"] ---|7 formes| spk-059["Xavier Planas"]
  spk-053["Roser Bastida"] ---|7 formes| spk-057["Teo Armengol"]
  spk-001["Alan Ward"] ---|6 formes| spk-012["Casimir Arajol"]
  spk-001["Alan Ward"] ---|6 formes| spk-021["Gualbert Osorio"]
  spk-001["Alan Ward"] ---|6 formes| spk-029["Jordi Torres Alís"]
  spk-001["Alan Ward"] ---|6 formes| spk-031["Josep Areny Fité"]
  spk-001["Alan Ward"] ---|6 formes| spk-033["Josep Garrallà Rossell"]
  spk-001["Alan Ward"] ---|6 formes| spk-034["Josep Marsal Riba"]
  spk-001["Alan Ward"] ---|6 formes| spk-038["Mercè Segura"]
  spk-001["Alan Ward"] ---|6 formes| spk-041["Miquel Naudi Casal"]
  spk-002["Albert Gelabert Grau"] ---|6 formes| spk-036["Ludmilla Lacueva"]
  spk-002["Albert Gelabert Grau"] ---|6 formes| spk-041["Miquel Naudi Casal"]
  spk-003["Albert Roig"] ---|6 formes| spk-055["Ruth Casabella"]
  spk-003["Albert Roig"] ---|6 formes| spk-058["Trini Mandicó Baró"]
  spk-005["Alfred Llahí"] ---|6 formes| spk-055["Ruth Casabella"]
  spk-005["Alfred Llahí"] ---|6 formes| spk-060["Àngels Mach"]
  spk-006["Andreu Gaspà Picart"] ---|6 formes| spk-009["Antoni Jordi Areny"]
  spk-006["Andreu Gaspà Picart"] ---|6 formes| spk-019["Francina Pons"]
  spk-006["Andreu Gaspà Picart"] ---|6 formes| spk-034["Josep Marsal Riba"]
  spk-006["Andreu Gaspà Picart"] ---|6 formes| spk-050["Robert Lizarte"]
  spk-006["Andreu Gaspà Picart"] ---|6 formes| spk-059["Xavier Planas"]
  spk-007["Angelina Mas"] ---|6 formes| spk-029["Jordi Torres Alís"]
  spk-007["Angelina Mas"] ---|6 formes| spk-055["Ruth Casabella"]
  spk-007["Angelina Mas"] ---|6 formes| spk-056["Sara Ubach"]
  spk-007["Angelina Mas"] ---|6 formes| spk-058["Trini Mandicó Baró"]
  spk-008["Antoni Armengol Vila"] ---|6 formes| spk-014["Daniel Armengol"]
  spk-008["Antoni Armengol Vila"] ---|6 formes| spk-036["Ludmilla Lacueva"]
  spk-008["Antoni Armengol Vila"] ---|6 formes| spk-058["Trini Mandicó Baró"]
  spk-008["Antoni Armengol Vila"] ---|6 formes| spk-059["Xavier Planas"]
  spk-008["Antoni Armengol Vila"] ---|6 formes| spk-060["Àngels Mach"]
  spk-009["Antoni Jordi Areny"] ---|6 formes| spk-011["Carles Sasplugas"]
  spk-009["Antoni Jordi Areny"] ---|6 formes| spk-014["Daniel Armengol"]
  spk-009["Antoni Jordi Areny"] ---|6 formes| spk-025["Joan Santamaria Terré"]
  spk-009["Antoni Jordi Areny"] ---|6 formes| spk-033["Josep Garrallà Rossell"]
  spk-009["Antoni Jordi Areny"] ---|6 formes| spk-036["Ludmilla Lacueva"]
  spk-010["Antoni Morell"] ---|6 formes| spk-011["Carles Sasplugas"]
  spk-010["Antoni Morell"] ---|6 formes| spk-059["Xavier Planas"]
  spk-011["Carles Sasplugas"] ---|6 formes| spk-012["Casimir Arajol"]
  spk-011["Carles Sasplugas"] ---|6 formes| spk-014["Daniel Armengol"]
  spk-011["Carles Sasplugas"] ---|6 formes| spk-017["Esther Jover"]
  spk-011["Carles Sasplugas"] ---|6 formes| spk-027["Jordi Marquet"]
  spk-011["Carles Sasplugas"] ---|6 formes| spk-030["Josep Areny"]
  spk-011["Carles Sasplugas"] ---|6 formes| spk-038["Mercè Segura"]
  spk-011["Carles Sasplugas"] ---|6 formes| spk-049["Robert Cassany Vila"]
  spk-011["Carles Sasplugas"] ---|6 formes| spk-050["Robert Lizarte"]
  spk-011["Carles Sasplugas"] ---|6 formes| spk-053["Roser Bastida"]
  spk-011["Carles Sasplugas"] ---|6 formes| spk-057["Teo Armengol"]
  spk-011["Carles Sasplugas"] ---|6 formes| spk-058["Trini Mandicó Baró"]
  spk-011["Carles Sasplugas"] ---|6 formes| spk-059["Xavier Planas"]
  spk-011["Carles Sasplugas"] ---|6 formes| spk-060["Àngels Mach"]
  spk-012["Casimir Arajol"] ---|6 formes| spk-017["Esther Jover"]
  spk-012["Casimir Arajol"] ---|6 formes| spk-050["Robert Lizarte"]
  spk-012["Casimir Arajol"] ---|6 formes| spk-053["Roser Bastida"]
  spk-012["Casimir Arajol"] ---|6 formes| spk-059["Xavier Planas"]
  spk-014["Daniel Armengol"] ---|6 formes| spk-019["Francina Pons"]
  spk-014["Daniel Armengol"] ---|6 formes| spk-033["Josep Garrallà Rossell"]
  spk-014["Daniel Armengol"] ---|6 formes| spk-036["Ludmilla Lacueva"]
  spk-014["Daniel Armengol"] ---|6 formes| spk-049["Robert Cassany Vila"]
  spk-014["Daniel Armengol"] ---|6 formes| spk-055["Ruth Casabella"]
  spk-015["Enric Casadevall Medrano"] ---|6 formes| spk-055["Ruth Casabella"]
  spk-015["Enric Casadevall Medrano"] ---|6 formes| spk-056["Sara Ubach"]
  spk-016["Enric Dolsa Font"] ---|6 formes| spk-029["Jordi Torres Alís"]
  spk-016["Enric Dolsa Font"] ---|6 formes| spk-056["Sara Ubach"]
  spk-017["Esther Jover"] ---|6 formes| spk-022["Guillem Areny Argelich"]
  spk-017["Esther Jover"] ---|6 formes| spk-033["Josep Garrallà Rossell"]
  spk-017["Esther Jover"] ---|6 formes| spk-034["Josep Marsal Riba"]
  spk-017["Esther Jover"] ---|6 formes| spk-039["Miquel Aleix Areny"]
  spk-017["Esther Jover"] ---|6 formes| spk-043["Nadia Aleix Tugas"]
  spk-017["Esther Jover"] ---|6 formes| spk-045["Patrick Pérez"]
  spk-017["Esther Jover"] ---|6 formes| spk-050["Robert Lizarte"]
  spk-017["Esther Jover"] ---|6 formes| spk-053["Roser Bastida"]
  spk-017["Esther Jover"] ---|6 formes| spk-055["Ruth Casabella"]
  spk-018["Eudald Guillamet"] ---|6 formes| spk-058["Trini Mandicó Baró"]
  spk-018["Eudald Guillamet"] ---|6 formes| spk-059["Xavier Planas"]
  spk-019["Francina Pons"] ---|6 formes| spk-020["Gabriel Dallerès Codina"]
  spk-019["Francina Pons"] ---|6 formes| spk-021["Gualbert Osorio"]
  spk-019["Francina Pons"] ---|6 formes| spk-029["Jordi Torres Alís"]
  spk-019["Francina Pons"] ---|6 formes| spk-038["Mercè Segura"]
  spk-019["Francina Pons"] ---|6 formes| spk-041["Miquel Naudi Casal"]
  spk-019["Francina Pons"] ---|6 formes| spk-045["Patrick Pérez"]
  spk-019["Francina Pons"] ---|6 formes| spk-046["Pere Altimir Pintat"]
  spk-019["Francina Pons"] ---|6 formes| spk-054["Roser Jordana"]
  spk-019["Francina Pons"] ---|6 formes| spk-055["Ruth Casabella"]
  spk-021["Gualbert Osorio"] ---|6 formes| spk-034["Josep Marsal Riba"]
  spk-021["Gualbert Osorio"] ---|6 formes| spk-041["Miquel Naudi Casal"]
  spk-021["Gualbert Osorio"] ---|6 formes| spk-049["Robert Cassany Vila"]
  spk-021["Gualbert Osorio"] ---|6 formes| spk-050["Robert Lizarte"]
  spk-021["Gualbert Osorio"] ---|6 formes| spk-053["Roser Bastida"]
  spk-021["Gualbert Osorio"] ---|6 formes| spk-059["Xavier Planas"]
  spk-022["Guillem Areny Argelich"] ---|6 formes| spk-059["Xavier Planas"]
  spk-024["Jaume Bartumeu Cassany"] ---|6 formes| spk-058["Trini Mandicó Baró"]
  spk-025["Joan Santamaria Terré"] ---|6 formes| spk-033["Josep Garrallà Rossell"]
  spk-025["Joan Santamaria Terré"] ---|6 formes| spk-055["Ruth Casabella"]
  spk-026["Jordi Farràs Forné"] ---|6 formes| spk-032["Josep Casal"]
  spk-026["Jordi Farràs Forné"] ---|6 formes| spk-055["Ruth Casabella"]
  spk-027["Jordi Marquet"] ---|6 formes| spk-036["Ludmilla Lacueva"]
  spk-027["Jordi Marquet"] ---|6 formes| spk-055["Ruth Casabella"]
  spk-027["Jordi Marquet"] ---|6 formes| spk-059["Xavier Planas"]
  spk-028["Jordi Mas Torres"] ---|6 formes| spk-049["Robert Cassany Vila"]
  spk-028["Jordi Mas Torres"] ---|6 formes| spk-053["Roser Bastida"]
  spk-028["Jordi Mas Torres"] ---|6 formes| spk-055["Ruth Casabella"]
  spk-028["Jordi Mas Torres"] ---|6 formes| spk-060["Àngels Mach"]
  spk-029["Jordi Torres Alís"] ---|6 formes| spk-040["Miquel Armengol Pons"]
  spk-029["Jordi Torres Alís"] ---|6 formes| spk-050["Robert Lizarte"]
  spk-030["Josep Areny"] ---|6 formes| spk-036["Ludmilla Lacueva"]
  spk-030["Josep Areny"] ---|6 formes| spk-059["Xavier Planas"]
  spk-031["Josep Areny Fité"] ---|6 formes| spk-049["Robert Cassany Vila"]
  spk-031["Josep Areny Fité"] ---|6 formes| spk-060["Àngels Mach"]
  spk-032["Josep Casal"] ---|6 formes| spk-042["Mossèn Ramon de Canillo"]
  spk-032["Josep Casal"] ---|6 formes| spk-044["Olga Adellach Coma"]
  spk-033["Josep Garrallà Rossell"] ---|6 formes| spk-034["Josep Marsal Riba"]
  spk-033["Josep Garrallà Rossell"] ---|6 formes| spk-043["Nadia Aleix Tugas"]
  spk-033["Josep Garrallà Rossell"] ---|6 formes| spk-049["Robert Cassany Vila"]
  spk-033["Josep Garrallà Rossell"] ---|6 formes| spk-053["Roser Bastida"]
  spk-033["Josep Garrallà Rossell"] ---|6 formes| spk-060["Àngels Mach"]
  spk-034["Josep Marsal Riba"] ---|6 formes| spk-053["Roser Bastida"]
  spk-034["Josep Marsal Riba"] ---|6 formes| spk-054["Roser Jordana"]
  spk-034["Josep Marsal Riba"] ---|6 formes| spk-055["Ruth Casabella"]
  spk-035["Ladislau Baró Solà"] ---|6 formes| spk-056["Sara Ubach"]
  spk-036["Ludmilla Lacueva"] ---|6 formes| spk-046["Pere Altimir Pintat"]
  spk-036["Ludmilla Lacueva"] ---|6 formes| spk-054["Roser Jordana"]
  spk-037["Maria Reig Moles"] ---|6 formes| spk-053["Roser Bastida"]
  spk-037["Maria Reig Moles"] ---|6 formes| spk-056["Sara Ubach"]
  spk-037["Maria Reig Moles"] ---|6 formes| spk-058["Trini Mandicó Baró"]
  spk-038["Mercè Segura"] ---|6 formes| spk-049["Robert Cassany Vila"]
  spk-038["Mercè Segura"] ---|6 formes| spk-053["Roser Bastida"]
  spk-038["Mercè Segura"] ---|6 formes| spk-055["Ruth Casabella"]
  spk-038["Mercè Segura"] ---|6 formes| spk-060["Àngels Mach"]
  spk-039["Miquel Aleix Areny"] ---|6 formes| spk-060["Àngels Mach"]
  spk-043["Nadia Aleix Tugas"] ---|6 formes| spk-049["Robert Cassany Vila"]
  spk-043["Nadia Aleix Tugas"] ---|6 formes| spk-058["Trini Mandicó Baró"]
  spk-043["Nadia Aleix Tugas"] ---|6 formes| spk-060["Àngels Mach"]
  spk-044["Olga Adellach Coma"] ---|6 formes| spk-055["Ruth Casabella"]
  spk-044["Olga Adellach Coma"] ---|6 formes| spk-056["Sara Ubach"]
  spk-045["Patrick Pérez"] ---|6 formes| spk-053["Roser Bastida"]
  spk-046["Pere Altimir Pintat"] ---|6 formes| spk-055["Ruth Casabella"]
  spk-046["Pere Altimir Pintat"] ---|6 formes| spk-060["Àngels Mach"]
  spk-049["Robert Cassany Vila"] ---|6 formes| spk-050["Robert Lizarte"]
  spk-049["Robert Cassany Vila"] ---|6 formes| spk-053["Roser Bastida"]
  spk-049["Robert Cassany Vila"] ---|6 formes| spk-059["Xavier Planas"]
  spk-049["Robert Cassany Vila"] ---|6 formes| spk-060["Àngels Mach"]
  spk-050["Robert Lizarte"] ---|6 formes| spk-056["Sara Ubach"]
  spk-051["Rosa Maria Mandicó Alcobé"] ---|6 formes| spk-056["Sara Ubach"]
  spk-053["Roser Bastida"] ---|6 formes| spk-054["Roser Jordana"]
  spk-054["Roser Jordana"] ---|6 formes| spk-059["Xavier Planas"]
  spk-055["Ruth Casabella"] ---|6 formes| spk-057["Teo Armengol"]
  spk-055["Ruth Casabella"] ---|6 formes| spk-059["Xavier Planas"]
  spk-057["Teo Armengol"] ---|6 formes| spk-058["Trini Mandicó Baró"]
  spk-059["Xavier Planas"] ---|6 formes| spk-060["Àngels Mach"]
  spk-001["Alan Ward"] ---|5 formes| spk-055["Ruth Casabella"]
  spk-001["Alan Ward"] ---|5 formes| spk-056["Sara Ubach"]
  spk-001["Alan Ward"] ---|5 formes| spk-058["Trini Mandicó Baró"]
  spk-002["Albert Gelabert Grau"] ---|5 formes| spk-029["Jordi Torres Alís"]
  spk-002["Albert Gelabert Grau"] ---|5 formes| spk-032["Josep Casal"]
  spk-002["Albert Gelabert Grau"] ---|5 formes| spk-055["Ruth Casabella"]
  spk-002["Albert Gelabert Grau"] ---|5 formes| spk-058["Trini Mandicó Baró"]
  spk-003["Albert Roig"] ---|5 formes| spk-004["Albert Rossa Naudí"]
  spk-003["Albert Roig"] ---|5 formes| spk-029["Jordi Torres Alís"]
  spk-003["Albert Roig"] ---|5 formes| spk-032["Josep Casal"]
  spk-004["Albert Rossa Naudí"] ---|5 formes| spk-016["Enric Dolsa Font"]
  spk-004["Albert Rossa Naudí"] ---|5 formes| spk-017["Esther Jover"]
  spk-004["Albert Rossa Naudí"] ---|5 formes| spk-021["Gualbert Osorio"]
  spk-004["Albert Rossa Naudí"] ---|5 formes| spk-024["Jaume Bartumeu Cassany"]
  spk-004["Albert Rossa Naudí"] ---|5 formes| spk-042["Mossèn Ramon de Canillo"]
  spk-004["Albert Rossa Naudí"] ---|5 formes| spk-054["Roser Jordana"]
  spk-005["Alfred Llahí"] ---|5 formes| spk-032["Josep Casal"]
  spk-006["Andreu Gaspà Picart"] ---|5 formes| spk-011["Carles Sasplugas"]
  spk-006["Andreu Gaspà Picart"] ---|5 formes| spk-036["Ludmilla Lacueva"]
  spk-006["Andreu Gaspà Picart"] ---|5 formes| spk-053["Roser Bastida"]
  spk-006["Andreu Gaspà Picart"] ---|5 formes| spk-058["Trini Mandicó Baró"]
  spk-007["Angelina Mas"] ---|5 formes| spk-032["Josep Casal"]
  spk-008["Antoni Armengol Vila"] ---|5 formes| spk-029["Jordi Torres Alís"]
  spk-008["Antoni Armengol Vila"] ---|5 formes| spk-056["Sara Ubach"]
  spk-009["Antoni Jordi Areny"] ---|5 formes| spk-017["Esther Jover"]
  spk-009["Antoni Jordi Areny"] ---|5 formes| spk-029["Jordi Torres Alís"]
  spk-009["Antoni Jordi Areny"] ---|5 formes| spk-055["Ruth Casabella"]
  spk-009["Antoni Jordi Areny"] ---|5 formes| spk-056["Sara Ubach"]
  spk-009["Antoni Jordi Areny"] ---|5 formes| spk-060["Àngels Mach"]
  spk-010["Antoni Morell"] ---|5 formes| spk-019["Francina Pons"]
  spk-010["Antoni Morell"] ---|5 formes| spk-036["Ludmilla Lacueva"]
  spk-010["Antoni Morell"] ---|5 formes| spk-056["Sara Ubach"]
  spk-010["Antoni Morell"] ---|5 formes| spk-058["Trini Mandicó Baró"]
  spk-011["Carles Sasplugas"] ---|5 formes| spk-031["Josep Areny Fité"]
  spk-011["Carles Sasplugas"] ---|5 formes| spk-034["Josep Marsal Riba"]
  spk-011["Carles Sasplugas"] ---|5 formes| spk-036["Ludmilla Lacueva"]
  spk-011["Carles Sasplugas"] ---|5 formes| spk-055["Ruth Casabella"]
  spk-012["Casimir Arajol"] ---|5 formes| spk-019["Francina Pons"]
  spk-012["Casimir Arajol"] ---|5 formes| spk-036["Ludmilla Lacueva"]
  spk-012["Casimir Arajol"] ---|5 formes| spk-056["Sara Ubach"]
  spk-012["Casimir Arajol"] ---|5 formes| spk-058["Trini Mandicó Baró"]
  spk-014["Daniel Armengol"] ---|5 formes| spk-029["Jordi Torres Alís"]
  spk-014["Daniel Armengol"] ---|5 formes| spk-041["Miquel Naudi Casal"]
  spk-014["Daniel Armengol"] ---|5 formes| spk-053["Roser Bastida"]
  spk-014["Daniel Armengol"] ---|5 formes| spk-056["Sara Ubach"]
  spk-015["Enric Casadevall Medrano"] ---|5 formes| spk-032["Josep Casal"]
  spk-017["Esther Jover"] ---|5 formes| spk-029["Jordi Torres Alís"]
  spk-017["Esther Jover"] ---|5 formes| spk-037["Maria Reig Moles"]
  spk-017["Esther Jover"] ---|5 formes| spk-049["Robert Cassany Vila"]
  spk-018["Eudald Guillamet"] ---|5 formes| spk-029["Jordi Torres Alís"]
  spk-018["Eudald Guillamet"] ---|5 formes| spk-055["Ruth Casabella"]
  spk-018["Eudald Guillamet"] ---|5 formes| spk-056["Sara Ubach"]
  spk-019["Francina Pons"] ---|5 formes| spk-030["Josep Areny"]
  spk-019["Francina Pons"] ---|5 formes| spk-033["Josep Garrallà Rossell"]
  spk-019["Francina Pons"] ---|5 formes| spk-049["Robert Cassany Vila"]
  spk-019["Francina Pons"] ---|5 formes| spk-060["Àngels Mach"]
  spk-020["Gabriel Dallerès Codina"] ---|5 formes| spk-029["Jordi Torres Alís"]
  spk-020["Gabriel Dallerès Codina"] ---|5 formes| spk-032["Josep Casal"]
  spk-020["Gabriel Dallerès Codina"] ---|5 formes| spk-056["Sara Ubach"]
  spk-020["Gabriel Dallerès Codina"] ---|5 formes| spk-058["Trini Mandicó Baró"]
  spk-021["Gualbert Osorio"] ---|5 formes| spk-036["Ludmilla Lacueva"]
  spk-021["Gualbert Osorio"] ---|5 formes| spk-055["Ruth Casabella"]
  spk-021["Gualbert Osorio"] ---|5 formes| spk-056["Sara Ubach"]
  spk-021["Gualbert Osorio"] ---|5 formes| spk-058["Trini Mandicó Baró"]
  spk-022["Guillem Areny Argelich"] ---|5 formes| spk-032["Josep Casal"]
  spk-024["Jaume Bartumeu Cassany"] ---|5 formes| spk-032["Josep Casal"]
  spk-024["Jaume Bartumeu Cassany"] ---|5 formes| spk-056["Sara Ubach"]
  spk-025["Joan Santamaria Terré"] ---|5 formes| spk-060["Àngels Mach"]
  spk-026["Jordi Farràs Forné"] ---|5 formes| spk-029["Jordi Torres Alís"]
  spk-027["Jordi Marquet"] ---|5 formes| spk-029["Jordi Torres Alís"]
  spk-028["Jordi Mas Torres"] ---|5 formes| spk-032["Josep Casal"]
  spk-029["Jordi Torres Alís"] ---|5 formes| spk-030["Josep Areny"]
  spk-029["Jordi Torres Alís"] ---|5 formes| spk-031["Josep Areny Fité"]
  spk-029["Jordi Torres Alís"] ---|5 formes| spk-034["Josep Marsal Riba"]
  spk-029["Jordi Torres Alís"] ---|5 formes| spk-037["Maria Reig Moles"]
  spk-029["Jordi Torres Alís"] ---|5 formes| spk-042["Mossèn Ramon de Canillo"]
  spk-029["Jordi Torres Alís"] ---|5 formes| spk-043["Nadia Aleix Tugas"]
  spk-029["Jordi Torres Alís"] ---|5 formes| spk-045["Patrick Pérez"]
  spk-029["Jordi Torres Alís"] ---|5 formes| spk-048["Ramon Canut Bové"]
  spk-029["Jordi Torres Alís"] ---|5 formes| spk-051["Rosa Maria Mandicó Alcobé"]
  spk-029["Jordi Torres Alís"] ---|5 formes| spk-056["Sara Ubach"]
  spk-029["Jordi Torres Alís"] ---|5 formes| spk-057["Teo Armengol"]
  spk-030["Josep Areny"] ---|5 formes| spk-055["Ruth Casabella"]
  spk-030["Josep Areny"] ---|5 formes| spk-056["Sara Ubach"]
  spk-031["Josep Areny Fité"] ---|5 formes| spk-036["Ludmilla Lacueva"]
  spk-031["Josep Areny Fité"] ---|5 formes| spk-055["Ruth Casabella"]
  spk-031["Josep Areny Fité"] ---|5 formes| spk-059["Xavier Planas"]
  spk-032["Josep Casal"] ---|5 formes| spk-035["Ladislau Baró Solà"]
  spk-032["Josep Casal"] ---|5 formes| spk-039["Miquel Aleix Areny"]
  spk-032["Josep Casal"] ---|5 formes| spk-040["Miquel Armengol Pons"]
  spk-032["Josep Casal"] ---|5 formes| spk-041["Miquel Naudi Casal"]
  spk-032["Josep Casal"] ---|5 formes| spk-043["Nadia Aleix Tugas"]
  spk-032["Josep Casal"] ---|5 formes| spk-048["Ramon Canut Bové"]
  spk-032["Josep Casal"] ---|5 formes| spk-049["Robert Cassany Vila"]
  spk-032["Josep Casal"] ---|5 formes| spk-051["Rosa Maria Mandicó Alcobé"]
  spk-033["Josep Garrallà Rossell"] ---|5 formes| spk-046["Pere Altimir Pintat"]
  spk-033["Josep Garrallà Rossell"] ---|5 formes| spk-050["Robert Lizarte"]
  spk-033["Josep Garrallà Rossell"] ---|5 formes| spk-059["Xavier Planas"]
  spk-034["Josep Marsal Riba"] ---|5 formes| spk-049["Robert Cassany Vila"]
  spk-034["Josep Marsal Riba"] ---|5 formes| spk-058["Trini Mandicó Baró"]
  spk-036["Ludmilla Lacueva"] ---|5 formes| spk-038["Mercè Segura"]
  spk-036["Ludmilla Lacueva"] ---|5 formes| spk-040["Miquel Armengol Pons"]
  spk-036["Ludmilla Lacueva"] ---|5 formes| spk-045["Patrick Pérez"]
  spk-036["Ludmilla Lacueva"] ---|5 formes| spk-056["Sara Ubach"]
  spk-036["Ludmilla Lacueva"] ---|5 formes| spk-060["Àngels Mach"]
  spk-038["Mercè Segura"] ---|5 formes| spk-058["Trini Mandicó Baró"]
  spk-039["Miquel Aleix Areny"] ---|5 formes| spk-055["Ruth Casabella"]
  spk-039["Miquel Aleix Areny"] ---|5 formes| spk-056["Sara Ubach"]
  spk-040["Miquel Armengol Pons"] ---|5 formes| spk-055["Ruth Casabella"]
  spk-040["Miquel Armengol Pons"] ---|5 formes| spk-056["Sara Ubach"]
  spk-040["Miquel Armengol Pons"] ---|5 formes| spk-058["Trini Mandicó Baró"]
  spk-041["Miquel Naudi Casal"] ---|5 formes| spk-053["Roser Bastida"]
  spk-041["Miquel Naudi Casal"] ---|5 formes| spk-056["Sara Ubach"]
  spk-041["Miquel Naudi Casal"] ---|5 formes| spk-059["Xavier Planas"]
  spk-042["Mossèn Ramon de Canillo"] ---|5 formes| spk-055["Ruth Casabella"]
  spk-042["Mossèn Ramon de Canillo"] ---|5 formes| spk-056["Sara Ubach"]
  spk-042["Mossèn Ramon de Canillo"] ---|5 formes| spk-058["Trini Mandicó Baró"]
  spk-043["Nadia Aleix Tugas"] ---|5 formes| spk-056["Sara Ubach"]
  spk-044["Olga Adellach Coma"] ---|5 formes| spk-058["Trini Mandicó Baró"]
  spk-045["Patrick Pérez"] ---|5 formes| spk-056["Sara Ubach"]
  spk-045["Patrick Pérez"] ---|5 formes| spk-058["Trini Mandicó Baró"]
  spk-045["Patrick Pérez"] ---|5 formes| spk-059["Xavier Planas"]
  spk-048["Ramon Canut Bové"] ---|5 formes| spk-056["Sara Ubach"]
  spk-049["Robert Cassany Vila"] ---|5 formes| spk-057["Teo Armengol"]
  spk-050["Robert Lizarte"] ---|5 formes| spk-053["Roser Bastida"]
  spk-050["Robert Lizarte"] ---|5 formes| spk-055["Ruth Casabella"]
  spk-051["Rosa Maria Mandicó Alcobé"] ---|5 formes| spk-055["Ruth Casabella"]
  spk-051["Rosa Maria Mandicó Alcobé"] ---|5 formes| spk-058["Trini Mandicó Baró"]
  spk-053["Roser Bastida"] ---|5 formes| spk-059["Xavier Planas"]
  spk-053["Roser Bastida"] ---|5 formes| spk-060["Àngels Mach"]
  spk-054["Roser Jordana"] ---|5 formes| spk-056["Sara Ubach"]
  spk-054["Roser Jordana"] ---|5 formes| spk-058["Trini Mandicó Baró"]
  spk-056["Sara Ubach"] ---|5 formes| spk-057["Teo Armengol"]
