graph TD
  spk-015[Enric Casadevall Medrano] ---|5 formes| spk-053[Roser Bastida]
  spk-016[Enric Dolsa Font] ---|5 formes| spk-038[Mercè Segura]
  spk-016[Enric Dolsa Font] ---|5 formes| spk-043[Nadia Aleix Tugas]
  spk-005[Alfred Llahí] ---|4 formes| spk-016[Enric Dolsa Font]
  spk-005[Alfred Llahí] ---|4 formes| spk-028[Jordi Mas Torres]
  spk-005[Alfred Llahí] ---|4 formes| spk-038[Mercè Segura]
  spk-010[Antoni Morell] ---|4 formes| spk-016[Enric Dolsa Font]
  spk-010[Antoni Morell] ---|4 formes| spk-037[Maria Reig Moles]
  spk-010[Antoni Morell] ---|4 formes| spk-057[Teo Armengol]
  spk-011[Carles Sasplugas] ---|4 formes| spk-037[Maria Reig Moles]
  spk-016[Enric Dolsa Font] ---|4 formes| spk-040[Miquel Armengol Pons]
  spk-016[Enric Dolsa Font] ---|4 formes| spk-044[Olga Adellach Coma]
  spk-016[Enric Dolsa Font] ---|4 formes| spk-053[Roser Bastida]
  spk-026[Jordi Farràs Forné] ---|4 formes| spk-037[Maria Reig Moles]
  spk-037[Maria Reig Moles] ---|4 formes| spk-038[Mercè Segura]
  spk-037[Maria Reig Moles] ---|4 formes| spk-057[Teo Armengol]
  spk-038[Mercè Segura] ---|4 formes| spk-057[Teo Armengol]
  spk-043[Nadia Aleix Tugas] ---|4 formes| spk-044[Olga Adellach Coma]
  spk-043[Nadia Aleix Tugas] ---|4 formes| spk-053[Roser Bastida]
