"""Model and dataset cards, and the publication gate — PLAN M6.02-M6.04.

*"Bilingual (ca/en) model card: motivation, data + method, the F4 4-config matrix
table, limitations (synthetic, no oral dialect, no legal advice), licenses (model
Apache 2.0; dataset CC-BY-4.0 with per-source attribution)."*

A card is the only part of this project most people will ever read, which makes it
the one artifact where an omission is not a documentation debt but a
misrepresentation. So the required sections are a **checked list**, not a template
someone fills in.

**Limitations are required, and each names a real constraint from the build.**
*Synthetic* (a frontier model wrote the answers, and only a sample was reviewed by
hand), *no oral dialect* (M1.13's spoken subcorpora were used for register only,
never to clone a voice — D7), and *not legal advice* (the model is trained on
consolidated Andorran law, which is exactly what makes someone ask). A card missing
any of them describes a model that does not exist.

**Bilingual means both languages carry the same sections.** A Catalan card whose
English half quietly drops the limitations is worse than a monolingual one: it
presents a complete document to a reader who cannot check. So
:func:`missing_sections` and :func:`missing_limitations` check **per language**.

**The evaluation table is the F4 matrix, rendered, not retyped.** M4.05 already
produces it; a hand-copied table is a second source of truth that drifts, and this
one drifts *towards* flattering numbers.

**The upload is gated on M6.01.** :func:`publish` refuses to run when the legal gate
has not passed, because the ordering — check, then publish — is the only thing that
makes the gate a gate.
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass, field
from enum import StrEnum
from pathlib import Path
from typing import Protocol

from maia.evaluation.matrix import Matrix, render_matrix
from maia.publication.compliance import ComplianceReport, attribution_section
from maia.schemas import Source

#: The plan's repo names.
MODEL_REPO = "ericrisco/maia-12b-it"
GGUF_REPO = "ericrisco/maia-12b-it-GGUF"
DATASET_REPO = "ericrisco/andorra-instruct-ca"

#: The plan's licences: the model is Apache 2.0, the dataset CC-BY-4.0.
MODEL_LICENSE = "apache-2.0"
#: The dataset licence. **CC-BY-SA-4.0, not CC-BY-4.0** — see D-0043(1). Share-alike is viral:
#: the corpus includes CC-BY-SA-3.0 Viquipèdia text, and an instruction example generated from a
#: passage is a derivative of it. Shipping that derivative under a non-share-alike licence would be
#: incompatible, and publishing under the wrong licence is not something a later commit can undo.
DATASET_LICENSE = "cc-by-sa-4.0"


class Language(StrEnum):
    """The two languages every card must carry."""

    CA = "ca"
    EN = "en"


#: The limitations the plan requires, in both languages. Each names a real constraint
#: from the build, which is why they are text rather than a checkbox.
LIMITATIONS: Mapping[Language, Mapping[str, str]] = {
    Language.CA: {
        "synthetic": (
            "Les respostes van ser generades per un model frontera a partir de "
            "passatges reals del corpus. Una mostra es va revisar a mà (DoD-F2); "
            "la resta, no."
        ),
        "oral": (
            "Els subcorpus parlats es van fer servir només per al registre i el "
            "lèxic, mai per imitar la parla d'una persona identificable. El model "
            "no reprodueix dialecte oral."
        ),
        "legal": (
            "No és assessorament jurídic. Està entrenat amb text legal consolidat, "
            "cosa que fa especialment temptador aquest ús: cal consultar la font "
            "oficial i un professional."
        ),
    },
    Language.EN: {
        "synthetic": (
            "Answers were generated by a frontier model from real corpus passages. "
            "A sample was reviewed by hand (DoD-F2); the rest was not."
        ),
        "oral": (
            "The spoken subcorpora were used for register and lexicon only, never "
            "to imitate an identifiable person's speech. The model does not "
            "reproduce oral dialect."
        ),
        "legal": (
            "This is not legal advice. It is trained on consolidated Andorran law, "
            "which is exactly what makes that use tempting: consult the official "
            "source and a professional."
        ),
    },
}

#: Sections a card must have. The gate checks these, so an omission fails a test.
REQUIRED_SECTIONS = ("motivation", "data", "method", "evaluation", "limitations", "licence")

#: Section headings per language.
HEADINGS: Mapping[Language, Mapping[str, str]] = {
    Language.CA: {
        "motivation": "Per què existeix",
        "data": "Dades",
        "method": "Mètode",
        "evaluation": "Avaluació",
        "limitations": "Límits",
        "licence": "Llicència",
    },
    Language.EN: {
        "motivation": "Why this exists",
        "data": "Data",
        "method": "Method",
        "evaluation": "Evaluation",
        "limitations": "Limitations",
        "licence": "Licence",
    },
}

#: Distinctive phrases from each limitation. Matched instead of the heading, because a
#: "Limitations" section listing two of the three reads as complete.
MARKERS: Mapping[Language, Mapping[str, str]] = {
    Language.CA: {
        "synthetic": "model frontera",
        "oral": "persona identificable",
        "legal": "assessorament jurídic",
    },
    Language.EN: {
        "synthetic": "frontier model",
        "oral": "identifiable person",
        "legal": "not legal advice",
    },
}

#: The prose of each card section, per language.
PROSE: Mapping[Language, Mapping[str, str]] = {
    Language.CA: {
        "motivation": (
            "Els models generalistes coneixen Catalunya i confonen Andorra amb ella: "
            "institucions, dret i lèxic propis hi queden diluïts. MAIA és un model "
            "obert entrenat per conèixer el Principat, amb els fets recuperats per "
            "RAG i no memoritzats."
        ),
        "method": (
            "QLoRA sobre el model base, entrenant només la resposta visible. L'split "
            "de test està congelat i mai s'ha entrenat."
        ),
        "no_matrix": "> ⚠ La matriu de 4 configuracions encara no s'ha mesurat.",
    },
    Language.EN: {
        "motivation": (
            "General models know Catalonia and mistake Andorra for it: its "
            "institutions, law and lexicon get diluted. MAIA is an open model "
            "trained to know the Principality, with facts retrieved by RAG rather "
            "than memorised."
        ),
        "method": (
            "QLoRA over the base model, training on the visible response only. The "
            "test split is frozen and was never trained on."
        ),
        "no_matrix": "> ⚠ The 4-config matrix has not been measured yet.",
    },
}


class ModelHub(Protocol):
    """The slice of ``huggingface_hub.HfApi`` used here. Blocked-by-resource."""

    def create_repo(self, repo_id: str, *, repo_type: str, private: bool, exist_ok: bool) -> object:
        """Create (or accept the existence of) a repo."""

    def upload_folder(
        self, *, repo_id: str, folder_path: str, repo_type: str, commit_message: str
    ) -> object:
        """Commit a local folder."""


class NotPublishableError(RuntimeError):
    """Raised when publication is attempted before the M6.01 gate passes."""


@dataclass(frozen=True)
class CardFacts:
    """What a card states, gathered from the artifacts that produced it."""

    examples: int
    corpus_documents: int
    sources: tuple[Source, ...]
    matrix: Matrix | None = None
    base_model: str = "google/gemma-4-12b-it"
    candidate: str = "cand1"
    andbench_url: str = "https://github.com/ericrisco/andbench"


def _data_prose(facts: CardFacts, language: Language) -> str:
    """The data paragraph, which is the one that carries numbers."""
    if language is Language.CA:
        return (
            f"{facts.examples:,} exemples d'instrucció en català, generats a partir "
            f"de {facts.corpus_documents:,} documents d'un corpus andorrà, i sempre "
            "citant-los."
        )
    return (
        f"{facts.examples:,} Catalan instruction examples, generated from "
        f"{facts.corpus_documents:,} documents of an Andorran corpus, always citing "
        "them."
    )


def _evaluation_prose(facts: CardFacts, language: Language) -> str:
    """The evaluation paragraph. MAIA keeps no benchmark of its own (D-0032)."""
    if language is Language.CA:
        return f"Avaluat amb [AndBench]({facts.andbench_url}), no amb un benchmark propi."
    return f"Evaluated with [AndBench]({facts.andbench_url}), not with an in-house benchmark."


def _language_section(facts: CardFacts, language: Language) -> list[str]:
    """One language's half of the model card. Both halves carry the same sections."""
    heads = HEADINGS[language]
    prose = PROSE[language]
    lines = [f"## {'Català' if language is Language.CA else 'English'}", ""]
    for key, text in (
        ("motivation", prose["motivation"]),
        ("data", _data_prose(facts, language)),
        ("method", prose["method"]),
        ("evaluation", _evaluation_prose(facts, language)),
    ):
        lines += [f"### {heads[key]}", "", text, ""]
    if facts.matrix is not None:
        lines += [render_matrix(facts.matrix), ""]
    else:
        lines += [prose["no_matrix"], ""]
    lines += [f"### {heads['limitations']}", ""]
    lines += [f"- {text}" for text in LIMITATIONS[language].values()]
    lines += [
        "",
        f"### {heads['licence']}",
        "",
        f"Model: **{MODEL_LICENSE}**. Dataset: **{DATASET_LICENSE}**.",
        "",
    ]
    return lines


def model_card(facts: CardFacts) -> str:
    """The bilingual model card."""
    front = [
        "---",
        f"license: {MODEL_LICENSE}",
        "language:",
        "  - ca",
        "base_model:",
        f"  - {facts.base_model}",
        "pipeline_tag: text-generation",
        "tags:",
        "  - andorra",
        "  - catalan",
        "  - qlora",
        "---",
        "",
        "# MAIA — Model Andorrà d'Intel·ligència Artificial",
        "",
    ]
    body: list[str] = []
    for language in Language:
        body += _language_section(facts, language)
    return "\n".join([*front, *body])


def dataset_card(facts: CardFacts) -> str:
    """The dataset card, with the per-source attribution the licence requires."""
    lines = [
        "---",
        f"license: {DATASET_LICENSE}",
        "language:",
        "  - ca",
        "task_categories:",
        "  - text-generation",
        "  - question-answering",
        "---",
        "",
        "# andorra-instruct-ca",
        "",
        f"{facts.examples:,} Catalan instruction examples about Andorra, each citing "
        "the corpus passages it was generated from (`grounding_ids`).",
        "",
        "## Limitations",
        "",
    ]
    lines += [f"- {text}" for text in LIMITATIONS[Language.EN].values()]
    lines += ["", attribution_section(facts.sources), ""]
    return "\n".join(lines)


def missing_sections(card: str, *, language: Language | None = None) -> list[str]:
    """Required sections a card does not have.

    Checked **per language**, because that is where the real failure lives: a card can
    have every section somewhere and still drop the limitations from its English half.
    """
    languages = [language] if language is not None else list(Language)
    lowered = card.lower()
    return [
        f"{lang.value}: {key}"
        for lang in languages
        for key in REQUIRED_SECTIONS
        if HEADINGS[lang][key].lower() not in lowered
    ]


def missing_limitations(card: str, *, language: Language | None = None) -> list[str]:
    """Required limitations a card does not state."""
    languages = [language] if language is not None else list(Language)
    lowered = card.lower()
    return [
        f"{lang.value}: {name}"
        for lang in languages
        for name, marker in MARKERS[lang].items()
        if marker.lower() not in lowered
    ]


@dataclass
class PublicationReport:
    """What M6.04 published, and what it refused to."""

    repos: list[str] = field(default_factory=list)
    card_problems: list[str] = field(default_factory=list)
    blocked_by: str = ""

    @property
    def passed(self) -> bool:
        """Whether every repo went out with a complete card."""
        return bool(self.repos) and not self.card_problems and not self.blocked_by


def check_cards(model: str, dataset: str) -> list[str]:
    """Everything wrong with the two cards, as one list."""
    problems = [f"model card missing {item}" for item in missing_sections(model)]
    problems += [f"model card missing limitation {item}" for item in missing_limitations(model)]
    problems += [
        f"dataset card missing limitation {item}"
        for item in missing_limitations(dataset, language=Language.EN)
    ]
    if DATASET_LICENSE not in dataset.lower():
        problems.append("dataset card missing the dataset licence")
    return problems


def publish(
    facts: CardFacts,
    compliance: ComplianceReport,
    hub: ModelHub,
    staging: Mapping[str, Path],
    *,
    private: bool = True,
) -> PublicationReport:
    """Publish the model, GGUF and dataset repos.

    Raises:
        NotPublishableError: if the M6.01 gate has not passed, or the cards are
            incomplete. The ordering — check, then publish — is the only thing that
            makes that gate a gate, so it is enforced here rather than written down as
            a step someone should remember.
    """
    report = PublicationReport()
    if not compliance.passed:
        report.blocked_by = (
            f"the M6.01 legal gate has not passed ({len(compliance.blocking)} blocking finding(s))"
        )
        raise NotPublishableError(
            report.blocked_by + "; publication is gated on it, because a check that "
            "runs after the upload is not a gate"
        )

    model = model_card(facts)
    dataset = dataset_card(facts)
    report.card_problems = check_cards(model, dataset)
    if report.card_problems:
        raise NotPublishableError(
            "the cards are incomplete, and a card is the only part of this project "
            "most people will read:\n"
            + "\n".join(f"  - {problem}" for problem in report.card_problems)
        )

    for repo_id, folder in staging.items():
        repo_type = "dataset" if repo_id == DATASET_REPO else "model"
        card = dataset if repo_type == "dataset" else model
        folder.mkdir(parents=True, exist_ok=True)
        (folder / "README.md").write_text(card, encoding="utf-8")
        hub.create_repo(repo_id, repo_type=repo_type, private=private, exist_ok=True)
        hub.upload_folder(
            repo_id=repo_id,
            folder_path=str(folder),
            repo_type=repo_type,
            commit_message=f"MAIA {facts.candidate}: {facts.examples:,} examples",
        )
        report.repos.append(repo_id)
    return report


def render(report: PublicationReport) -> str:
    """Human-readable summary of a publication run."""
    lines = ["✓ published" if report.passed else "✗ not published"]
    lines += [f"  {repo}" for repo in report.repos]
    if report.blocked_by:
        lines.append(f"  blocked: {report.blocked_by}")
    lines += [f"  ✗ {problem}" for problem in report.card_problems]
    if report.passed:
        lines.append(
            "  the PO validates DoD-F6; this only says the repos went out with complete cards"
        )
    return "\n".join(lines)


def expected_repos() -> tuple[str, str, str]:
    """The three repos the plan names."""
    return (MODEL_REPO, GGUF_REPO, DATASET_REPO)
